import type {AstryxBlockTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'block',
  name: 'AI Meeting Notes Card',
  description:
    "Post-meeting AI summary card for the Kestrel Labs 'Atlas Q3 · Launch Sync' (Wed Jul 15, 2026), shown as three frozen specimens side by side on a soft AI-purple-tinted stage, each under a mono caption row: specimen 01 is the ready recap — sparkle-marked Kestrel AI header with meeting title, time, and a five-attendee facepile; three key-point bullets whose facts match the Atlas Q3 canon; a Decided row whose chip links to the team decision log; and three action items with assignee Avatars, due Tokens, and Add-to-Tasks buttons (Sofia's already added with a checkmark) above a 'Generated by Kestrel AI — review before sharing' footer with regenerate/edit affordances and a Share-to-#atlas-q3 button; specimen 02 is the processing state — Spinner note ('Summarizing 30 min of audio from 5 speakers…'), shimmer Skeleton bullets, and a step-2-of-3 progress hint with every affordance disabled; specimen 03 is the low-confidence state — the third bullet carries an amber wavy 'Verify this' underline with the reason, a dismiss, and an 18:24 source-timestamp link into the recording. Choose over meet-recap when the deliverable is the compact shareable notes CARD (the artifact that gets pinned in a channel or the team-space home) and its generation states, not the full recap page with recording player, transcript pane, and talk-time analytics; choose over team-decision-log when a decision appears as one outbound link chip on the recap rather than the filterable register of decision records itself; choose over meeting-agenda-builder when the moment is AFTER the meeting (summarized outcomes and action items), not collaboratively time-boxing the agenda beforehand; choose over messaging-shell when the surface is the embedded card specimen itself, not the live channel stream it would be shared into.",
  category: 'Team Workspace',
  componentsUsed: [
    'Avatar',
    'AvatarGroup',
    'Badge',
    'Button',
    'Card',
    'Divider',
    'Heading',
    'HStack',
    'Icon',
    'IconButton',
    'Skeleton',
    'Spinner',
    'StackItem',
    'Text',
    'Token',
    'VStack',
  ],
} satisfies AstryxBlockTemplate;

export default template;
