// Copyright (c) Meta Platforms, Inc. and affiliates.

'use client';

/**
 * @file page.tsx
 * @input Deterministic fixtures only (180 SaaS accounts generated by a
 *   seeded PRNG at module load — spend, engagement, seats, segment, region —
 *   so identical fixtures always produce identical pixels)
 * @output Brushing-and-linking metric lab: a hand-rolled SVG scatter of
 *   monthly spend vs engagement (dot radius maps seats, dot color maps
 *   segment) with a draggable rectangle brush — pointer events with capture,
 *   move/resize via corner handles that grow to ~44px hit targets on touch,
 *   plus a full keyboard path (Enter creates, arrows nudge, Shift+arrows
 *   resize, Escape clears) driving the identical reducer actions — linked
 *   bidirectionally to a 12-bin spend histogram (drag across bins or
 *   click / Shift+click bin buttons to brush a spend range that filters the
 *   scatter back) and a segment bar chart with toggle buttons, all above a
 *   compact brushed-accounts Table. Active selections render as removable
 *   Token chips, and a lasso-stats strip (count, median spend, total seats)
 *   recomputes from the brushed set on every pointer move.
 * @position Page template; emitted by `astryx template metric-brush-explorer`
 *
 * Frame: Layout height="fill". LayoutHeader carries the chrome (title, live
 * "N of 180 brushed" readout, Clear-all Button). LayoutContent scrolls a
 * centered max-w-6xl column: filter-chip strip, lasso-stats Stat row, the
 * three linked chart Cards, then the account Table Card.
 *
 * Container policy: this is an analytics explorable, so each chart is a Card
 * widget and the table lives in its own Card; the page chrome stays
 * frame-first (Layout/LayoutHeader/LayoutContent, no ad hoc shells).
 *
 * Responsive contract:
 * - Page column: maxWidth 1152, centered; the whole content area scrolls.
 * - >640px: charts sit in a 2-column CSS grid — the scatter spans both rows
 *   on the left (3fr), histogram and segment bars stack on the right (2fr).
 * - <=640px: single-pane fallback — the three chart Cards become a
 *   horizontal scroll-snap carousel (each slide 100% wide, snap-start,
 *   deliberate overflowX) with a swipe hint line; the brush stays fully
 *   touch-operable because corner-handle hit zones grow to ~44px and the
 *   whole gesture runs on pointer events with capture, never hover.
 * - Stats row: Grid columns={{minWidth: 180, max: 3}} — 3-up wide, 1-up on
 *   phones. Chip strip wraps. Table scrolls horizontally inside its Card
 *   below ~640px (pixel numeric columns keep digits stable).
 * - Tap targets: segment-toggle rows and histogram bins are >=40px-tall
 *   buttons; preset-brush and clear Buttons are standard >=32px controls
 *   with padded rows; nothing is hover-only (the histogram bin summary uses
 *   a native title on hover pointers but the same numbers always render in
 *   the bin caption line).
 * - Motion: dot dim/undim and bar-width transitions are suppressed when
 *   prefers-reduced-motion is set (state changes still apply instantly).
 *
 * Color policy: token-pure — every color resolves through var(--color-*)
 * tokens or color-mix() over those tokens (translucent brush fills and
 * ghost bars included), so the whole surface re-themes in dark mode with no
 * raw hex/rgb literals anywhere in this file.
 *
 * Fixture policy: fixed seeded data only; no Date.now, no Math.random at
 * render time, no network assets. Every derived number is a pure function
 * of the fixture array and the selection-reducer state.
 */

import {
  useMemo,
  useReducer,
  useRef,
  useState,
  type CSSProperties,
  type Dispatch,
  type KeyboardEvent as ReactKeyboardEvent,
  type PointerEvent as ReactPointerEvent,
} from 'react';

import {
  HStack,
  Layout,
  LayoutContent,
  LayoutHeader,
  StackItem,
  VStack,
} from '@astryxdesign/core/Layout';
import {Text, Heading} from '@astryxdesign/core/Text';
import {Badge} from '@astryxdesign/core/Badge';
import {Button} from '@astryxdesign/core/Button';
import {Card} from '@astryxdesign/core/Card';
import {EmptyState} from '@astryxdesign/core/EmptyState';
import {Grid} from '@astryxdesign/core/Grid';
import {Icon} from '@astryxdesign/core/Icon';
import {Stat} from '@astryxdesign/core/Stat';
import {Table, pixel, proportional} from '@astryxdesign/core/Table';
import type {TableColumn} from '@astryxdesign/core/Table';
import {Token} from '@astryxdesign/core/Token';
import {useMediaQuery} from '@astryxdesign/core/hooks';
import {BoxSelectIcon, InboxIcon} from 'lucide-react';

// ============= STYLES =============

// Token-pure palette: series colors are categorical data tokens; every
// translucent surface (brush fill, ghost bars, gridlines) is a color-mix()
// over a token so it stays legible on both light and dark card surfaces.
const colors = {
  enterprise: 'var(--color-data-categorical-blue)',
  midmarket: 'var(--color-data-categorical-purple)',
  smb: 'var(--color-data-categorical-green)',
  startup: 'var(--color-data-categorical-orange)',
  axis: 'var(--color-border)',
  gridline: 'color-mix(in srgb, var(--color-border) 55%, transparent)',
  tickText: 'var(--color-text-secondary)',
  brushFill:
    'color-mix(in srgb, var(--color-data-categorical-blue) 16%, transparent)',
  brushStroke: 'var(--color-data-categorical-blue)',
  handleFill: 'var(--color-background)',
  histBar: 'var(--color-data-categorical-blue)',
  histGhost: 'color-mix(in srgb, var(--color-border) 45%, transparent)',
  histRange:
    'color-mix(in srgb, var(--color-data-categorical-blue) 12%, transparent)',
  segGhost: 'color-mix(in srgb, var(--color-border) 45%, transparent)',
};

const styles: Record<string, CSSProperties> = {
  // Centered scrollable page column (max-w-6xl).
  page: {maxWidth: 1152, marginInline: 'auto', width: '100%'},
  numeric: {fontVariantNumeric: 'tabular-nums'},
  // Desktop chart grid: scatter spans both rows on the left.
  chartGrid: {
    display: 'grid',
    gridTemplateColumns: '3fr 2fr',
    gridTemplateRows: 'auto auto',
    gap: 'var(--spacing-4)',
    alignItems: 'stretch',
  },
  scatterCell: {gridRow: '1 / span 2', minWidth: 0},
  sideCell: {minWidth: 0},
  // <=640px: horizontal scroll-snap carousel of the three chart Cards.
  chartSnapRow: {
    display: 'flex',
    gap: 'var(--spacing-3)',
    overflowX: 'auto',
    scrollSnapType: 'x mandatory',
    paddingBottom: 'var(--spacing-1)',
    WebkitOverflowScrolling: 'touch',
  },
  chartSnapSlide: {
    flex: '0 0 100%',
    minWidth: 0,
    scrollSnapAlign: 'start',
  },
  chipRow: {minHeight: 32},
  // Scatter SVG scales with its Card via the viewBox; touch-action none so
  // the brush gesture owns the pointer instead of the page scroll.
  scatterSvg: {
    width: '100%',
    height: 'auto',
    display: 'block',
    touchAction: 'none',
    cursor: 'crosshair',
    borderRadius: 'var(--radius-control, 6px)',
  },
  legendSwatch: {
    width: 10,
    height: 10,
    borderRadius: '50%',
    flexShrink: 0,
  },
  // Histogram: fixed-height strip of bin buttons; drag runs on the wrapper.
  histWrap: {
    position: 'relative',
    display: 'flex',
    gap: 3,
    height: 180,
    alignItems: 'flex-end',
    touchAction: 'none',
  },
  histBin: {
    position: 'relative',
    flex: 1,
    minWidth: 0,
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    padding: 0,
    border: 'none',
    background: 'transparent',
    font: 'inherit',
    cursor: 'pointer',
    borderRadius: 'var(--radius-control, 6px)',
  },
  histBinInRange: {
    backgroundColor: colors.histRange,
    boxShadow: `inset 0 0 0 1px ${colors.brushStroke}`,
  },
  histGhostBar: {
    width: '100%',
    backgroundColor: colors.histGhost,
    borderRadius: '3px 3px 0 0',
  },
  histActiveBar: {
    position: 'absolute',
    insetInline: 0,
    bottom: 0,
    backgroundColor: colors.histBar,
    borderRadius: '3px 3px 0 0',
  },
  histAxisRow: {display: 'flex', justifyContent: 'space-between'},
  // Segment bars: each row is a >=40px toggle button.
  segRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--spacing-3)',
    width: '100%',
    minHeight: 44,
    padding: '0 var(--spacing-2)',
    border: 'none',
    background: 'transparent',
    font: 'inherit',
    cursor: 'pointer',
    borderRadius: 'var(--radius-control, 6px)',
    textAlign: 'start',
  },
  segRowActive: {
    boxShadow: 'inset 0 0 0 1px var(--color-accent)',
    backgroundColor: 'color-mix(in srgb, var(--color-accent) 8%, transparent)',
  },
  segLabelCol: {width: 92, flexShrink: 0},
  segTrack: {
    position: 'relative',
    flex: 1,
    minWidth: 0,
    height: 16,
    borderRadius: 'var(--radius-control, 6px)',
    backgroundColor: 'var(--color-background-muted)',
    overflow: 'hidden',
  },
  segGhostBar: {
    position: 'absolute',
    insetBlock: 0,
    insetInlineStart: 0,
    backgroundColor: colors.segGhost,
  },
  segActiveBar: {
    position: 'absolute',
    insetBlock: 0,
    insetInlineStart: 0,
    borderRadius: 'inherit',
  },
  segCountCol: {width: 72, flexShrink: 0, textAlign: 'end'},
  // Table wrapper: deliberate horizontal scroll on narrow phones.
  tableScroll: {overflowX: 'auto', minWidth: 0},
  emptyBody: {padding: 'var(--spacing-6) 0'},
};

// ============= FIXTURES =============
// 180 SaaS accounts from a seeded mulberry32 PRNG evaluated once at module
// load — pure, replayable, and identical on every render and every machine.

type SegmentId = 'enterprise' | 'midmarket' | 'smb' | 'startup';
type RegionId = 'na' | 'emea' | 'apac' | 'latam';

interface Account {
  id: string;
  name: string;
  segment: SegmentId;
  region: RegionId;
  /** Monthly spend in dollars, 0–10,000. */
  spend: number;
  /** Weekly active engagement, 0–100%. */
  engagement: number;
  /** Provisioned seats. */
  seats: number;
}

const SEGMENTS: ReadonlyArray<{
  id: SegmentId;
  label: string;
  color: string;
}> = [
  {id: 'enterprise', label: 'Enterprise', color: colors.enterprise},
  {id: 'midmarket', label: 'Mid-market', color: colors.midmarket},
  {id: 'smb', label: 'SMB', color: colors.smb},
  {id: 'startup', label: 'Startup', color: colors.startup},
];

const SEGMENT_LABEL: Record<SegmentId, string> = {
  enterprise: 'Enterprise',
  midmarket: 'Mid-market',
  smb: 'SMB',
  startup: 'Startup',
};

const SEGMENT_COLOR: Record<SegmentId, string> = {
  enterprise: colors.enterprise,
  midmarket: colors.midmarket,
  smb: colors.smb,
  startup: colors.startup,
};

const REGION_LABEL: Record<RegionId, string> = {
  na: 'North America',
  emea: 'EMEA',
  apac: 'APAC',
  latam: 'LATAM',
};

const REGION_IDS: ReadonlyArray<RegionId> = ['na', 'emea', 'apac', 'latam'];

// 20 x 9 name parts = exactly 180 unique account names.
const NAME_HEADS = [
  'Alder', 'Basalt', 'Cinder', 'Dovetail', 'Emberline', 'Foxglove', 'Granite',
  'Harborlight', 'Ironwood', 'Juniper', 'Kestrel', 'Larkspur', 'Meridian',
  'Northbeam', 'Opaline', 'Pinewood', 'Quarry', 'Riverbend', 'Saltgrass',
  'Timberline',
] as const;
const NAME_TAILS = [
  'Labs', 'Systems', 'Logistics', 'Analytics', 'Health', 'Robotics',
  'Financial', 'Media', 'Manufacturing',
] as const;

/** Standard mulberry32: deterministic 32-bit PRNG, fixed seed. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Per-segment envelopes keep spend/engagement/seats plausibly clustered. */
const SEGMENT_ENVELOPE: Record<
  SegmentId,
  {
    spend: [number, number];
    engagement: [number, number];
    seats: [number, number];
  }
> = {
  enterprise: {spend: [4200, 9800], engagement: [38, 92], seats: [120, 420]},
  midmarket: {spend: [2200, 6400], engagement: [30, 88], seats: [40, 170]},
  smb: {spend: [700, 3300], engagement: [18, 82], seats: [8, 64]},
  startup: {spend: [200, 1700], engagement: [10, 96], seats: [3, 26]},
};

// Segment mix: 0.2 enterprise / 0.3 mid-market / 0.3 SMB / 0.2 startup.
function segmentFor(roll: number): SegmentId {
  if (roll < 0.2) {
    return 'enterprise';
  }
  if (roll < 0.5) {
    return 'midmarket';
  }
  if (roll < 0.8) {
    return 'smb';
  }
  return 'startup';
}

function buildAccounts(): Account[] {
  const rand = mulberry32(20260703);
  const accounts: Account[] = [];
  for (let i = 0; i < 180; i++) {
    const segment = segmentFor(rand());
    const env = SEGMENT_ENVELOPE[segment];
    const spendT = rand();
    const spend =
      Math.round((env.spend[0] + (env.spend[1] - env.spend[0]) * spendT) / 10) *
      10;
    // Engagement is loosely correlated with spend (0.55 weight) plus noise,
    // clamped to the segment envelope so clusters stay readable.
    const engT = Math.min(1, Math.max(0, spendT * 0.55 + rand() * 0.45));
    const engagement = Math.round(
      env.engagement[0] + (env.engagement[1] - env.engagement[0]) * engT,
    );
    const seatT = Math.min(1, Math.max(0, spendT * 0.7 + rand() * 0.3));
    const seats = Math.round(
      env.seats[0] + (env.seats[1] - env.seats[0]) * seatT,
    );
    accounts.push({
      id: `acct-${String(i + 1).padStart(3, '0')}`,
      name: `${NAME_HEADS[i % NAME_HEADS.length]} ${
        NAME_TAILS[Math.floor(i / NAME_HEADS.length) % NAME_TAILS.length]
      }`,
      segment,
      region: REGION_IDS[Math.floor(rand() * REGION_IDS.length)],
      spend,
      engagement,
      seats,
    });
  }
  return accounts;
}

const ACCOUNTS: ReadonlyArray<Account> = buildAccounts();
const TOTAL_SEATS = ACCOUNTS.reduce((sum, a) => sum + a.seats, 0);

// ============= SCALES & FORMATTERS (hand-rolled, deterministic) =============

const SPEND_MAX = 10000;
const ENG_MAX = 100;
const SEATS_MAX = 420;

/** Evenly spaced axis ticks including both endpoints. */
function tickValues(max: number, step: number): number[] {
  const ticks: number[] = [];
  for (let v = 0; v <= max; v += step) {
    ticks.push(v);
  }
  return ticks;
}

const SPEND_TICKS = tickValues(SPEND_MAX, 2000);
const ENG_TICKS = tickValues(ENG_MAX, 20);

function formatMoney(value: number): string {
  return value >= 1000
    ? `$${(value / 1000).toFixed(value % 1000 === 0 ? 0 : 1)}k`
    : `$${Math.round(value)}`;
}

function formatCount(value: number): string {
  return value.toLocaleString('en-US');
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function median(values: number[]): number {
  if (values.length === 0) {
    return 0;
  }
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 1
    ? sorted[mid]
    : (sorted[mid - 1] + sorted[mid]) / 2;
}

// ============= SHARED SELECTION REDUCER =============
// One reducer owns every linked selection: the scatter's rectangle brush
// (data units), the histogram's spend range (snapped to bin edges), and the
// segment toggles. Pointer gestures, corner handles, keyboard nudges, bin
// clicks, and preset buttons all dispatch the same actions — direct
// manipulation IS the filter mechanism; no control panel mediates the data.

interface BrushRect {
  /** Ordered spend bounds in dollars, spend0 <= spend1. */
  spend0: number;
  spend1: number;
  /** Ordered engagement bounds in percent, eng0 <= eng1. */
  eng0: number;
  eng1: number;
}

interface SpendRange {
  min: number;
  max: number;
}

interface Selection {
  scatter: BrushRect | null;
  spend: SpendRange | null;
  segments: ReadonlyArray<SegmentId>;
}

type SelectionAction =
  | {type: 'scatter-brush'; rect: BrushRect}
  | {type: 'clear-scatter'}
  | {type: 'spend-range'; range: SpendRange}
  | {type: 'clear-spend'}
  | {type: 'toggle-segment'; segment: SegmentId}
  | {type: 'clear-all'};

const EMPTY_SELECTION: Selection = {scatter: null, spend: null, segments: []};

function selectionReducer(state: Selection, action: SelectionAction): Selection {
  switch (action.type) {
    case 'scatter-brush':
      return {...state, scatter: action.rect};
    case 'clear-scatter':
      return {...state, scatter: null};
    case 'spend-range':
      return {...state, spend: action.range};
    case 'clear-spend':
      return {...state, spend: null};
    case 'toggle-segment': {
      const has = state.segments.includes(action.segment);
      return {
        ...state,
        segments: has
          ? state.segments.filter(s => s !== action.segment)
          : [...state.segments, action.segment],
      };
    }
    case 'clear-all':
      return EMPTY_SELECTION;
  }
}

type Facet = 'scatter' | 'spend' | 'segments';

/**
 * Cross-filter predicate. `ignore` implements the linking convention: each
 * chart draws its base data filtered by every facet except its own, so the
 * histogram reacts to the scatter brush and vice versa without feedback.
 */
function accountPasses(
  account: Account,
  selection: Selection,
  ignore?: Facet,
): boolean {
  if (ignore !== 'scatter' && selection.scatter != null) {
    const b = selection.scatter;
    if (
      account.spend < b.spend0 ||
      account.spend > b.spend1 ||
      account.engagement < b.eng0 ||
      account.engagement > b.eng1
    ) {
      return false;
    }
  }
  if (ignore !== 'spend' && selection.spend != null) {
    if (
      account.spend < selection.spend.min ||
      account.spend > selection.spend.max
    ) {
      return false;
    }
  }
  if (ignore !== 'segments' && selection.segments.length > 0) {
    if (!selection.segments.includes(account.segment)) {
      return false;
    }
  }
  return true;
}

// Preset brushes — the button path that drives the exact same commit logic
// as the drag gesture (and doubles as a one-tap entry point on touch).
const PRESET_BRUSHES: ReadonlyArray<{id: string; label: string; rect: BrushRect}> =
  [
    {
      id: 'top-spend',
      label: 'Top-spend quartile',
      rect: {spend0: 7500, spend1: SPEND_MAX, eng0: 0, eng1: ENG_MAX},
    },
    {
      id: 'high-eng',
      label: 'High engagement',
      rect: {spend0: 0, spend1: SPEND_MAX, eng0: 70, eng1: ENG_MAX},
    },
    {
      id: 'at-risk',
      label: 'Paying but idle',
      rect: {spend0: 3000, spend1: SPEND_MAX, eng0: 0, eng1: 35},
    },
  ];

// ============= SCATTER (hand-rolled SVG + rectangle brush) =============

const VB_W = 640;
const VB_H = 400;
const PAD = {top: 14, right: 14, bottom: 34, left: 50};
const PLOT_W = VB_W - PAD.left - PAD.right;
const PLOT_H = VB_H - PAD.top - PAD.bottom;

/** Data → viewBox px. Pure and deterministic: same fixtures, same pixels. */
function xOf(spend: number): number {
  return PAD.left + (spend / SPEND_MAX) * PLOT_W;
}
function yOf(engagement: number): number {
  return PAD.top + (1 - engagement / ENG_MAX) * PLOT_H;
}
/** ViewBox px → data, clamped to the plot domain. */
function spendAt(px: number): number {
  return clamp(((px - PAD.left) / PLOT_W) * SPEND_MAX, 0, SPEND_MAX);
}
function engAt(py: number): number {
  return clamp((1 - (py - PAD.top) / PLOT_H) * ENG_MAX, 0, ENG_MAX);
}
/** Dot radius from seats: sqrt scale so area tracks the value. */
function dotRadius(seats: number): number {
  return 3 + Math.sqrt(seats / SEATS_MAX) * 9;
}

type HandleId = 'nw' | 'ne' | 'sw' | 'se';

interface HandlePoint {
  id: HandleId;
  x: number;
  y: number;
}

function brushHandles(rect: BrushRect): HandlePoint[] {
  const x0 = xOf(rect.spend0);
  const x1 = xOf(rect.spend1);
  const yTop = yOf(rect.eng1);
  const yBottom = yOf(rect.eng0);
  return [
    {id: 'nw', x: x0, y: yTop},
    {id: 'ne', x: x1, y: yTop},
    {id: 'sw', x: x0, y: yBottom},
    {id: 'se', x: x1, y: yBottom},
  ];
}

function orderedRect(
  spendA: number,
  spendB: number,
  engA: number,
  engB: number,
): BrushRect {
  return {
    spend0: Math.min(spendA, spendB),
    spend1: Math.max(spendA, spendB),
    eng0: Math.min(engA, engB),
    eng1: Math.max(engA, engB),
  };
}

interface ScatterGesture {
  mode: 'draw' | 'move' | 'resize';
  pointerId: number;
  /** Anchor (draw) or grab point (move) in data units. */
  spend: number;
  eng: number;
  orig: BrushRect | null;
  handle: HandleId | null;
  moved: boolean;
}

const KEY_STEP_SPEND = SPEND_MAX * 0.05;
const KEY_STEP_ENG = ENG_MAX * 0.05;
const MIN_BRUSH_SPEND = SPEND_MAX * 0.04;
const MIN_BRUSH_ENG = ENG_MAX * 0.04;

function ScatterBrushChart({
  selection,
  selectedIds,
  dispatch,
  isTouch,
  reducedMotion,
}: {
  selection: Selection;
  selectedIds: ReadonlySet<string>;
  dispatch: Dispatch<SelectionAction>;
  isTouch: boolean;
  reducedMotion: boolean;
}) {
  const svgRef = useRef<SVGSVGElement | null>(null);
  const gestureRef = useRef<ScatterGesture | null>(null);
  const [isFocused, setIsFocused] = useState(false);
  const brush = selection.scatter;
  // Touch pointers get ~44px corner hit zones (viewBox units track CSS px
  // closely at typical card widths); mouse pointers get tighter 9px zones.
  const handleHit = isTouch ? 22 : 9;

  const toViewBox = (event: ReactPointerEvent<SVGSVGElement>) => {
    const node = svgRef.current;
    if (node == null) {
      return {x: 0, y: 0};
    }
    const bounds = node.getBoundingClientRect();
    return {
      x: ((event.clientX - bounds.left) / bounds.width) * VB_W,
      y: ((event.clientY - bounds.top) / bounds.height) * VB_H,
    };
  };

  const handlePointerDown = (event: ReactPointerEvent<SVGSVGElement>) => {
    if (event.pointerType === 'mouse' && event.button !== 0) {
      return;
    }
    const point = toViewBox(event);
    const spend = spendAt(point.x);
    const eng = engAt(point.y);
    let gesture: ScatterGesture = {
      mode: 'draw',
      pointerId: event.pointerId,
      spend,
      eng,
      orig: null,
      handle: null,
      moved: false,
    };
    if (brush != null) {
      // Hit-test corner handles first, then the brush body.
      const grabbed = brushHandles(brush).find(
        handle =>
          Math.abs(point.x - handle.x) <= handleHit &&
          Math.abs(point.y - handle.y) <= handleHit,
      );
      if (grabbed != null) {
        gesture = {...gesture, mode: 'resize', orig: brush, handle: grabbed.id};
      } else if (
        spend >= brush.spend0 &&
        spend <= brush.spend1 &&
        eng >= brush.eng0 &&
        eng <= brush.eng1
      ) {
        gesture = {...gesture, mode: 'move', orig: brush};
      }
    }
    gestureRef.current = gesture;
    event.currentTarget.setPointerCapture(event.pointerId);
    event.preventDefault();
  };

  const handlePointerMove = (event: ReactPointerEvent<SVGSVGElement>) => {
    const gesture = gestureRef.current;
    if (gesture == null || gesture.pointerId !== event.pointerId) {
      return;
    }
    const point = toViewBox(event);
    const spend = spendAt(point.x);
    const eng = engAt(point.y);
    gesture.moved = true;
    if (gesture.mode === 'draw') {
      dispatch({
        type: 'scatter-brush',
        rect: orderedRect(gesture.spend, spend, gesture.eng, eng),
      });
      return;
    }
    const orig = gesture.orig;
    if (orig == null) {
      return;
    }
    if (gesture.mode === 'move') {
      const width = orig.spend1 - orig.spend0;
      const height = orig.eng1 - orig.eng0;
      const spend0 = clamp(
        orig.spend0 + (spend - gesture.spend),
        0,
        SPEND_MAX - width,
      );
      const eng0 = clamp(orig.eng0 + (eng - gesture.eng), 0, ENG_MAX - height);
      dispatch({
        type: 'scatter-brush',
        rect: {spend0, spend1: spend0 + width, eng0, eng1: eng0 + height},
      });
      return;
    }
    // Resize: the grabbed corner follows the pointer; the opposite corner
    // stays anchored, and orderedRect handles crossing over it.
    const anchorSpend =
      gesture.handle === 'nw' || gesture.handle === 'sw'
        ? orig.spend1
        : orig.spend0;
    const anchorEng =
      gesture.handle === 'nw' || gesture.handle === 'ne' ? orig.eng0 : orig.eng1;
    dispatch({
      type: 'scatter-brush',
      rect: orderedRect(anchorSpend, spend, anchorEng, eng),
    });
  };

  const handlePointerEnd = (event: ReactPointerEvent<SVGSVGElement>) => {
    const gesture = gestureRef.current;
    if (gesture == null || gesture.pointerId !== event.pointerId) {
      return;
    }
    gestureRef.current = null;
    if (event.currentTarget.hasPointerCapture(event.pointerId)) {
      event.currentTarget.releasePointerCapture(event.pointerId);
    }
    // A tap on empty plot (no drag) clears the brush; a degenerate sliver
    // from a micro-drag clears too, so stray taps never leave ghost filters.
    if (gesture.mode === 'draw') {
      const current = brush;
      if (
        !gesture.moved ||
        (current != null &&
          current.spend1 - current.spend0 < MIN_BRUSH_SPEND &&
          current.eng1 - current.eng0 < MIN_BRUSH_ENG)
      ) {
        dispatch({type: 'clear-scatter'});
      }
    }
  };

  // Keyboard path — identical dispatches to the pointer gesture: Enter
  // creates a centered brush, arrows nudge, Shift+arrows resize the
  // spend1/eng1 edge, Escape/Delete clears.
  const handleKeyDown = (event: ReactKeyboardEvent<SVGSVGElement>) => {
    const key = event.key;
    if (key === 'Enter' || key === ' ') {
      if (brush == null) {
        dispatch({
          type: 'scatter-brush',
          rect: {
            spend0: SPEND_MAX * 0.25,
            spend1: SPEND_MAX * 0.75,
            eng0: ENG_MAX * 0.25,
            eng1: ENG_MAX * 0.75,
          },
        });
        event.preventDefault();
      }
      return;
    }
    if (key === 'Escape' || key === 'Delete' || key === 'Backspace') {
      if (brush != null) {
        dispatch({type: 'clear-scatter'});
        event.preventDefault();
      }
      return;
    }
    if (brush == null || !key.startsWith('Arrow')) {
      return;
    }
    event.preventDefault();
    if (event.shiftKey) {
      // Resize the far edges, never below the minimum brush size.
      let {spend1, eng1} = brush;
      if (key === 'ArrowRight') {
        spend1 = clamp(spend1 + KEY_STEP_SPEND, brush.spend0, SPEND_MAX);
      } else if (key === 'ArrowLeft') {
        spend1 = clamp(
          spend1 - KEY_STEP_SPEND,
          brush.spend0 + MIN_BRUSH_SPEND,
          SPEND_MAX,
        );
      } else if (key === 'ArrowUp') {
        eng1 = clamp(eng1 + KEY_STEP_ENG, brush.eng0, ENG_MAX);
      } else if (key === 'ArrowDown') {
        eng1 = clamp(eng1 - KEY_STEP_ENG, brush.eng0 + MIN_BRUSH_ENG, ENG_MAX);
      }
      dispatch({type: 'scatter-brush', rect: {...brush, spend1, eng1}});
      return;
    }
    // Nudge: shift the whole rect, clamped so its size is preserved.
    const width = brush.spend1 - brush.spend0;
    const height = brush.eng1 - brush.eng0;
    let spend0 = brush.spend0;
    let eng0 = brush.eng0;
    if (key === 'ArrowRight') {
      spend0 = clamp(spend0 + KEY_STEP_SPEND, 0, SPEND_MAX - width);
    } else if (key === 'ArrowLeft') {
      spend0 = clamp(spend0 - KEY_STEP_SPEND, 0, SPEND_MAX - width);
    } else if (key === 'ArrowUp') {
      eng0 = clamp(eng0 + KEY_STEP_ENG, 0, ENG_MAX - height);
    } else if (key === 'ArrowDown') {
      eng0 = clamp(eng0 - KEY_STEP_ENG, 0, ENG_MAX - height);
    }
    dispatch({
      type: 'scatter-brush',
      rect: {spend0, spend1: spend0 + width, eng0, eng1: eng0 + height},
    });
  };

  const brushLabel =
    brush == null
      ? 'No brush. Press Enter to create one.'
      : `Brush covering ${formatMoney(brush.spend0)} to ${formatMoney(
          brush.spend1,
        )} spend and ${Math.round(brush.eng0)} to ${Math.round(
          brush.eng1,
        )} percent engagement.`;
  const handleVisual = isTouch ? 7 : 4.5;

  return (
    <VStack gap={3}>
      <svg
        ref={svgRef}
        viewBox={`0 0 ${VB_W} ${VB_H}`}
        style={{
          ...styles.scatterSvg,
          outline: isFocused
            ? '2px solid var(--color-accent)'
            : '1px solid transparent',
          outlineOffset: 2,
        }}
        role="application"
        tabIndex={0}
        aria-label={`Spend versus engagement scatter with a rectangle brush. ${brushLabel} Arrow keys move the brush, Shift plus arrows resize it, Escape clears it.`}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={handlePointerEnd}
        onPointerCancel={handlePointerEnd}
        onKeyDown={handleKeyDown}
        onFocus={() => setIsFocused(true)}
        onBlur={() => setIsFocused(false)}>
        {/* Gridlines + axes (hand-rolled ticks; no chart library). */}
        {SPEND_TICKS.map(tick => (
          <g key={`x-${tick}`}>
            <line
              x1={xOf(tick)}
              x2={xOf(tick)}
              y1={PAD.top}
              y2={PAD.top + PLOT_H}
              stroke={colors.gridline}
              strokeWidth={1}
            />
            <text
              x={xOf(tick)}
              y={VB_H - 12}
              textAnchor="middle"
              fontSize={10}
              fill={colors.tickText}>
              {formatMoney(tick)}
            </text>
          </g>
        ))}
        {ENG_TICKS.map(tick => (
          <g key={`y-${tick}`}>
            <line
              x1={PAD.left}
              x2={PAD.left + PLOT_W}
              y1={yOf(tick)}
              y2={yOf(tick)}
              stroke={colors.gridline}
              strokeWidth={1}
            />
            <text
              x={PAD.left - 8}
              y={yOf(tick) + 3}
              textAnchor="end"
              fontSize={10}
              fill={colors.tickText}>
              {tick}%
            </text>
          </g>
        ))}
        <line
          x1={PAD.left}
          x2={PAD.left + PLOT_W}
          y1={PAD.top + PLOT_H}
          y2={PAD.top + PLOT_H}
          stroke={colors.axis}
          strokeWidth={1}
        />
        <line
          x1={PAD.left}
          x2={PAD.left}
          y1={PAD.top}
          y2={PAD.top + PLOT_H}
          stroke={colors.axis}
          strokeWidth={1}
        />

        {/* Dots: radius maps seats, color maps segment; anything failing any
            linked filter (including this brush) dims to 0.16 opacity. */}
        {ACCOUNTS.map(account => (
          <circle
            key={account.id}
            cx={xOf(account.spend)}
            cy={yOf(account.engagement)}
            r={dotRadius(account.seats)}
            fill={SEGMENT_COLOR[account.segment]}
            opacity={selectedIds.has(account.id) ? 0.85 : 0.16}
            style={
              reducedMotion ? undefined : {transition: 'opacity 140ms ease'}
            }
            pointerEvents="none"
          />
        ))}

        {/* Brush rectangle + corner handles (rendered inert; all hit-testing
            happens in the svg's pointer handlers so capture stays intact). */}
        {brush != null && (
          <g pointerEvents="none">
            <rect
              x={xOf(brush.spend0)}
              y={yOf(brush.eng1)}
              width={xOf(brush.spend1) - xOf(brush.spend0)}
              height={yOf(brush.eng0) - yOf(brush.eng1)}
              fill={colors.brushFill}
              stroke={colors.brushStroke}
              strokeWidth={1.5}
              rx={2}
            />
            {brushHandles(brush).map(handle => (
              <rect
                key={handle.id}
                x={handle.x - handleVisual}
                y={handle.y - handleVisual}
                width={handleVisual * 2}
                height={handleVisual * 2}
                fill={colors.handleFill}
                stroke={colors.brushStroke}
                strokeWidth={1.5}
                rx={2}
              />
            ))}
          </g>
        )}
      </svg>

      {/* Segment legend + interaction hint. */}
      <HStack gap={4} vAlign="center" wrap="wrap">
        {SEGMENTS.map(segment => (
          <HStack key={segment.id} gap={1.5} vAlign="center">
            <span
              style={{...styles.legendSwatch, backgroundColor: segment.color}}
              aria-hidden
            />
            <Text type="supporting" color="secondary" size="sm">
              {segment.label}
            </Text>
          </HStack>
        ))}
        <StackItem size="fill" />
        <Text type="supporting" color="secondary" size="sm">
          Dot size = seats
        </Text>
      </HStack>
    </VStack>
  );
}

// ============= SPEND HISTOGRAM (drag-brushable bins) =============

const BIN_COUNT = 12;
const BIN_WIDTH = SPEND_MAX / BIN_COUNT;

function binRange(bin0: number, bin1: number): SpendRange {
  const lo = Math.min(bin0, bin1);
  const hi = Math.max(bin0, bin1);
  return {min: lo * BIN_WIDTH, max: (hi + 1) * BIN_WIDTH};
}

function binsOfRange(range: SpendRange): [number, number] {
  return [
    clamp(Math.round(range.min / BIN_WIDTH), 0, BIN_COUNT - 1),
    clamp(Math.round(range.max / BIN_WIDTH) - 1, 0, BIN_COUNT - 1),
  ];
}

function histogramCounts(
  accounts: ReadonlyArray<Account>,
  predicate: (account: Account) => boolean,
): number[] {
  const counts = new Array<number>(BIN_COUNT).fill(0);
  for (const account of accounts) {
    if (predicate(account)) {
      const bin = clamp(Math.floor(account.spend / BIN_WIDTH), 0, BIN_COUNT - 1);
      counts[bin] += 1;
    }
  }
  return counts;
}

interface HistogramGesture {
  pointerId: number;
  startBin: number;
  dragged: boolean;
}

function SpendHistogram({
  selection,
  dispatch,
  reducedMotion,
}: {
  selection: Selection;
  dispatch: Dispatch<SelectionAction>;
  reducedMotion: boolean;
}) {
  const wrapRef = useRef<HTMLDivElement | null>(null);
  const gestureRef = useRef<HistogramGesture | null>(null);
  const suppressClickRef = useRef(false);

  // Linking convention: ghost bars are the full book; solid bars are the
  // accounts passing every OTHER facet (scatter brush + segments), so the
  // scatter re-filters this chart live while its own range stays brushable.
  const ghostCounts = useMemo(
    () => histogramCounts(ACCOUNTS, () => true),
    [],
  );
  const activeCounts = useMemo(
    () =>
      histogramCounts(ACCOUNTS, account =>
        accountPasses(account, selection, 'spend'),
      ),
    [selection],
  );
  const maxCount = Math.max(...ghostCounts, 1);
  const rangeBins =
    selection.spend == null ? null : binsOfRange(selection.spend);

  const binAtClientX = (clientX: number): number => {
    const node = wrapRef.current;
    if (node == null) {
      return 0;
    }
    const bounds = node.getBoundingClientRect();
    return clamp(
      Math.floor(((clientX - bounds.left) / bounds.width) * BIN_COUNT),
      0,
      BIN_COUNT - 1,
    );
  };

  const handlePointerDown = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (event.pointerType === 'mouse' && event.button !== 0) {
      return;
    }
    gestureRef.current = {
      pointerId: event.pointerId,
      startBin: binAtClientX(event.clientX),
      dragged: false,
    };
    event.currentTarget.setPointerCapture(event.pointerId);
  };

  const handlePointerMove = (event: ReactPointerEvent<HTMLDivElement>) => {
    const gesture = gestureRef.current;
    if (gesture == null || gesture.pointerId !== event.pointerId) {
      return;
    }
    const bin = binAtClientX(event.clientX);
    if (!gesture.dragged && bin === gesture.startBin) {
      return;
    }
    gesture.dragged = true;
    dispatch({type: 'spend-range', range: binRange(gesture.startBin, bin)});
  };

  const handlePointerEnd = (event: ReactPointerEvent<HTMLDivElement>) => {
    const gesture = gestureRef.current;
    if (gesture == null || gesture.pointerId !== event.pointerId) {
      return;
    }
    gestureRef.current = null;
    if (event.currentTarget.hasPointerCapture(event.pointerId)) {
      event.currentTarget.releasePointerCapture(event.pointerId);
    }
    // A drag already committed on every move; suppress the synthetic click
    // that follows so it can't collapse the range back to one bin.
    suppressClickRef.current = gesture.dragged;
  };

  // Click / keyboard path (bins are real buttons): click sets a single-bin
  // range, Shift+click extends the existing range, clicking the only
  // selected bin clears — all through the same reducer actions as the drag.
  const handleBinActivate = (
    bin: number,
    shiftKey: boolean,
  ) => {
    if (suppressClickRef.current) {
      suppressClickRef.current = false;
      return;
    }
    if (rangeBins != null && shiftKey) {
      dispatch({
        type: 'spend-range',
        range: binRange(Math.min(rangeBins[0], bin), Math.max(rangeBins[1], bin)),
      });
      return;
    }
    if (rangeBins != null && rangeBins[0] === bin && rangeBins[1] === bin) {
      dispatch({type: 'clear-spend'});
      return;
    }
    dispatch({type: 'spend-range', range: binRange(bin, bin)});
  };

  return (
    <VStack gap={2}>
      <div
        ref={wrapRef}
        style={styles.histWrap}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={handlePointerEnd}
        onPointerCancel={handlePointerEnd}>
        {ghostCounts.map((ghost, bin) => {
          const active = activeCounts[bin];
          const inRange =
            rangeBins != null && bin >= rangeBins[0] && bin <= rangeBins[1];
          const lo = bin * BIN_WIDTH;
          const hi = lo + BIN_WIDTH;
          return (
            <button
              key={bin}
              type="button"
              style={{
                ...styles.histBin,
                ...(inRange ? styles.histBinInRange : undefined),
              }}
              title={`${formatMoney(lo)}–${formatMoney(hi)}: ${active} of ${ghost} accounts`}
              aria-label={`Spend ${formatMoney(lo)} to ${formatMoney(
                hi,
              )}: ${active} brushed of ${ghost} accounts. ${
                inRange ? 'In the selected range.' : ''
              } Enter selects this bin, Shift+Enter extends the range.`}
              aria-pressed={inRange}
              onClick={event => handleBinActivate(bin, event.shiftKey)}>
              <span
                style={{
                  ...styles.histGhostBar,
                  height: `${(ghost / maxCount) * 100}%`,
                }}
                aria-hidden
              />
              <span
                style={{
                  ...styles.histActiveBar,
                  height: `${(active / maxCount) * 100}%`,
                  ...(reducedMotion
                    ? undefined
                    : {transition: 'height 140ms ease'}),
                }}
                aria-hidden
              />
            </button>
          );
        })}
      </div>
      <div style={styles.histAxisRow}>
        <Text type="supporting" color="secondary" size="sm" style={styles.numeric}>
          $0
        </Text>
        <Text type="supporting" color="secondary" size="sm" style={styles.numeric}>
          $5k
        </Text>
        <Text type="supporting" color="secondary" size="sm" style={styles.numeric}>
          $10k
        </Text>
      </div>
      <Text type="supporting" color="secondary" size="sm">
        {selection.spend == null
          ? 'Drag across bins (or click; Shift+click extends) to brush a spend range — the scatter filters in return.'
          : `Spend range ${formatMoney(selection.spend.min)}–${formatMoney(
              selection.spend.max,
            )} is filtering the scatter and table.`}
      </Text>
    </VStack>
  );
}

// ============= SEGMENT BAR CHART (toggle buttons) =============

function SegmentBars({
  selection,
  dispatch,
  reducedMotion,
}: {
  selection: Selection;
  dispatch: Dispatch<SelectionAction>;
  reducedMotion: boolean;
}) {
  // Base counts respect every facet except the segment toggles themselves,
  // so brushing the scatter or histogram reshapes these bars immediately.
  const counts = useMemo(() => {
    const totals: Record<SegmentId, {all: number; brushed: number}> = {
      enterprise: {all: 0, brushed: 0},
      midmarket: {all: 0, brushed: 0},
      smb: {all: 0, brushed: 0},
      startup: {all: 0, brushed: 0},
    };
    for (const account of ACCOUNTS) {
      totals[account.segment].all += 1;
      if (accountPasses(account, selection, 'segments')) {
        totals[account.segment].brushed += 1;
      }
    }
    return totals;
  }, [selection]);
  const maxAll = Math.max(...SEGMENTS.map(s => counts[s.id].all), 1);

  return (
    <VStack gap={1}>
      {SEGMENTS.map(segment => {
        const {all, brushed} = counts[segment.id];
        const isOn = selection.segments.includes(segment.id);
        const isDimmed = selection.segments.length > 0 && !isOn;
        return (
          <button
            key={segment.id}
            type="button"
            style={{
              ...styles.segRow,
              ...(isOn ? styles.segRowActive : undefined),
              opacity: isDimmed ? 0.45 : 1,
              ...(reducedMotion
                ? undefined
                : {transition: 'opacity 140ms ease'}),
            }}
            aria-pressed={isOn}
            aria-label={`${segment.label}: ${brushed} brushed of ${all} accounts. Toggles this segment as a filter.`}
            onClick={() =>
              dispatch({type: 'toggle-segment', segment: segment.id})
            }>
            <span style={styles.segLabelCol}>
              <Text type="supporting" maxLines={1}>
                {segment.label}
              </Text>
            </span>
            <span style={styles.segTrack}>
              <span
                style={{
                  ...styles.segGhostBar,
                  width: `${(all / maxAll) * 100}%`,
                }}
                aria-hidden
              />
              <span
                style={{
                  ...styles.segActiveBar,
                  width: `${(brushed / maxAll) * 100}%`,
                  backgroundColor: segment.color,
                  ...(reducedMotion
                    ? undefined
                    : {transition: 'width 140ms ease'}),
                }}
                aria-hidden
              />
            </span>
            <span style={styles.segCountCol}>
              <Text type="supporting" color="secondary" style={styles.numeric}>
                {brushed}/{all}
              </Text>
            </span>
          </button>
        );
      })}
      <Text type="supporting" color="secondary" size="sm">
        Tap a segment to keep only it; tap again to release. Bars re-count
        under the current brushes.
      </Text>
    </VStack>
  );
}

// ============= FILTER CHIPS =============

function FilterChips({
  selection,
  dispatch,
}: {
  selection: Selection;
  dispatch: Dispatch<SelectionAction>;
}) {
  const chips: Array<{id: string; label: string; onRemove: () => void}> = [];
  if (selection.scatter != null) {
    const b = selection.scatter;
    chips.push({
      id: 'scatter',
      label: `Scatter · ${formatMoney(b.spend0)}–${formatMoney(
        b.spend1,
      )} · ${Math.round(b.eng0)}–${Math.round(b.eng1)}% eng`,
      onRemove: () => dispatch({type: 'clear-scatter'}),
    });
  }
  if (selection.spend != null) {
    chips.push({
      id: 'spend',
      label: `Spend ${formatMoney(selection.spend.min)}–${formatMoney(
        selection.spend.max,
      )}`,
      onRemove: () => dispatch({type: 'clear-spend'}),
    });
  }
  for (const segment of selection.segments) {
    chips.push({
      id: `segment-${segment}`,
      label: `Segment · ${SEGMENT_LABEL[segment]}`,
      onRemove: () => dispatch({type: 'toggle-segment', segment}),
    });
  }

  return (
    <HStack gap={2} vAlign="center" wrap="wrap" style={styles.chipRow}>
      {chips.length === 0 ? (
        <Text type="supporting" color="secondary">
          No active brushes — drag on any chart to start filtering.
        </Text>
      ) : (
        <>
          {chips.map(chip => (
            <Token
              key={chip.id}
              label={chip.label}
              size="sm"
              onRemove={chip.onRemove}
            />
          ))}
          <Button
            label="Clear all"
            variant="ghost"
            size="sm"
            onClick={() => dispatch({type: 'clear-all'})}
          />
        </>
      )}
    </HStack>
  );
}

// ============= ACCOUNT TABLE =============

interface AccountRow extends Record<string, unknown> {
  id: string;
  name: string;
  segment: SegmentId;
  region: RegionId;
  spend: number;
  engagement: number;
  seats: number;
}

const SEGMENT_BADGE: Record<
  SegmentId,
  'blue' | 'purple' | 'green' | 'orange'
> = {
  enterprise: 'blue',
  midmarket: 'purple',
  smb: 'green',
  startup: 'orange',
};

const accountColumns: TableColumn<AccountRow>[] = [
  {
    key: 'name',
    header: 'Account',
    width: proportional(2),
    renderCell: (item: AccountRow) => <Text type="body">{item.name}</Text>,
  },
  {
    key: 'segment',
    header: 'Segment',
    width: pixel(110),
    renderCell: (item: AccountRow) => (
      <Badge
        label={SEGMENT_LABEL[item.segment]}
        variant={SEGMENT_BADGE[item.segment]}
      />
    ),
  },
  {
    key: 'region',
    header: 'Region',
    width: pixel(130),
    renderCell: (item: AccountRow) => (
      <Text type="body" color="secondary">
        {REGION_LABEL[item.region]}
      </Text>
    ),
  },
  {
    key: 'spend',
    header: 'Spend / mo',
    width: pixel(100),
    align: 'end',
    renderCell: (item: AccountRow) => (
      <span style={styles.numeric}>
        <Text type="body">{formatMoney(item.spend)}</Text>
      </span>
    ),
  },
  {
    key: 'engagement',
    header: 'Engagement',
    width: pixel(105),
    align: 'end',
    renderCell: (item: AccountRow) => (
      <span style={styles.numeric}>
        <Text type="body">{item.engagement}%</Text>
      </span>
    ),
  },
  {
    key: 'seats',
    header: 'Seats',
    width: pixel(75),
    align: 'end',
    renderCell: (item: AccountRow) => (
      <span style={styles.numeric}>
        <Text type="body">{formatCount(item.seats)}</Text>
      </span>
    ),
  },
];

// ============= PAGE =============

const TABLE_LIMIT = 10;

export default function MetricBrushExplorerTemplate() {
  const [selection, dispatch] = useReducer(selectionReducer, EMPTY_SELECTION);

  // Responsive contract: <=640px swaps the chart grid for a scroll-snap
  // carousel; (hover: none) grows the brush corner hit zones to ~44px.
  const isCompact = useMediaQuery('(max-width: 640px)');
  const isTouch = useMediaQuery('(hover: none)');
  const reducedMotion = useMediaQuery('(prefers-reduced-motion: reduce)');

  // The brushed set: accounts passing every linked facet. Because the drag
  // handlers dispatch on every pointer move, this — and the stats strip,
  // histogram, bars, and table below — recomputes live mid-gesture.
  const brushedIds = useMemo(() => {
    const ids = new Set<string>();
    for (const account of ACCOUNTS) {
      if (accountPasses(account, selection)) {
        ids.add(account.id);
      }
    }
    return ids;
  }, [selection]);

  const brushedAccounts = useMemo(
    () => ACCOUNTS.filter(account => brushedIds.has(account.id)),
    [brushedIds],
  );

  const stats = useMemo(() => {
    const spends = brushedAccounts.map(account => account.spend);
    const seats = brushedAccounts.reduce((sum, a) => sum + a.seats, 0);
    return {
      count: brushedAccounts.length,
      medianSpend: median(spends),
      seats,
      seatShare: Math.round((seats / TOTAL_SEATS) * 100),
    };
  }, [brushedAccounts]);

  const tableRows = useMemo<AccountRow[]>(
    () =>
      [...brushedAccounts]
        .sort((a, b) => b.spend - a.spend)
        .slice(0, TABLE_LIMIT)
        .map(account => ({...account})),
    [brushedAccounts],
  );

  const hasSelection =
    selection.scatter != null ||
    selection.spend != null ||
    selection.segments.length > 0;

  const activePresetId =
    PRESET_BRUSHES.find(preset => {
      const b = selection.scatter;
      return (
        b != null &&
        b.spend0 === preset.rect.spend0 &&
        b.spend1 === preset.rect.spend1 &&
        b.eng0 === preset.rect.eng0 &&
        b.eng1 === preset.rect.eng1
      );
    })?.id ?? null;

  const scatterCard = (
    <Card>
      <VStack gap={3}>
        <HStack gap={2} vAlign="center" wrap="wrap">
          <StackItem size="fill">
            <VStack gap={0}>
              <Heading level={3}>Spend vs engagement</Heading>
              <Text type="supporting" color="secondary">
                Drag a rectangle to brush; drag its body to move it, corners
                to resize. Keyboard: Enter, arrows, Shift+arrows, Escape.
              </Text>
            </VStack>
          </StackItem>
        </HStack>
        <ScatterBrushChart
          selection={selection}
          selectedIds={brushedIds}
          dispatch={dispatch}
          isTouch={isTouch}
          reducedMotion={reducedMotion}
        />
        {/* Preset brushes: the button path into the exact same reducer
            commit the drag gesture uses. */}
        <HStack gap={2} vAlign="center" wrap="wrap">
          <Text type="supporting" color="secondary" size="sm">
            Presets:
          </Text>
          {PRESET_BRUSHES.map(preset => (
            <Button
              key={preset.id}
              label={preset.label}
              size="sm"
              variant={activePresetId === preset.id ? 'secondary' : 'ghost'}
              onClick={() =>
                dispatch({type: 'scatter-brush', rect: preset.rect})
              }
            />
          ))}
        </HStack>
      </VStack>
    </Card>
  );

  const histogramCard = (
    <Card>
      <VStack gap={3}>
        <VStack gap={0}>
          <Heading level={3}>Spend distribution</Heading>
          <Text type="supporting" color="secondary">
            Solid bars = accounts passing the other brushes.
          </Text>
        </VStack>
        <SpendHistogram
          selection={selection}
          dispatch={dispatch}
          reducedMotion={reducedMotion}
        />
      </VStack>
    </Card>
  );

  const segmentCard = (
    <Card>
      <VStack gap={3}>
        <VStack gap={0}>
          <Heading level={3}>Segments</Heading>
          <Text type="supporting" color="secondary">
            Brushed count vs full book per segment.
          </Text>
        </VStack>
        <SegmentBars
          selection={selection}
          dispatch={dispatch}
          reducedMotion={reducedMotion}
        />
      </VStack>
    </Card>
  );

  return (
    <Layout
      height="fill"
      header={
        <LayoutHeader hasDivider>
          <HStack gap={3} vAlign="center" wrap="wrap">
            <StackItem size="fill">
              <HStack gap={2} vAlign="center">
                <Heading level={1}>Metric Brush Lab</Heading>
                <Text type="supporting" color="secondary" style={styles.numeric}>
                  {stats.count} of {ACCOUNTS.length} accounts brushed
                </Text>
              </HStack>
            </StackItem>
            {hasSelection && (
              <Button
                label="Clear all brushes"
                variant="secondary"
                size="sm"
                onClick={() => dispatch({type: 'clear-all'})}
              />
            )}
          </HStack>
        </LayoutHeader>
      }
      content={
        <LayoutContent padding={6} label="Linked metric explorer">
          <div style={styles.page}>
            <VStack gap={5}>
              {/* Active selections as removable chips. */}
              <FilterChips selection={selection} dispatch={dispatch} />

              {/* Lasso-stats strip — recomputed on every pointer move
                  because the gesture dispatches per-move. */}
              <Grid columns={{minWidth: 180, max: 3}} gap={4}>
                <Card>
                  <Stat
                    label="Accounts in brush"
                    value={formatCount(stats.count)}
                    description={`of ${ACCOUNTS.length} total`}
                  />
                </Card>
                <Card>
                  <Stat
                    label="Median spend"
                    value={
                      stats.count > 0 ? formatMoney(stats.medianSpend) : '—'
                    }
                    description="per month, brushed set"
                  />
                </Card>
                <Card>
                  <Stat
                    label="Total seats"
                    value={stats.count > 0 ? formatCount(stats.seats) : '—'}
                    description={
                      stats.count > 0
                        ? `${stats.seatShare}% of all seats`
                        : 'brush to compute'
                    }
                  />
                </Card>
              </Grid>

              {/* Linked charts: desktop 2-col grid (scatter spans left),
                  <=640px a scroll-snap carousel with a swipe hint. */}
              {isCompact ? (
                <VStack gap={2}>
                  <div style={styles.chartSnapRow}>
                    <div style={styles.chartSnapSlide}>{scatterCard}</div>
                    <div style={styles.chartSnapSlide}>{histogramCard}</div>
                    <div style={styles.chartSnapSlide}>{segmentCard}</div>
                  </div>
                  <Text type="supporting" color="secondary" size="sm">
                    Swipe sideways for the histogram and segment charts — all
                    three stay linked to the same brush.
                  </Text>
                </VStack>
              ) : (
                <div style={styles.chartGrid}>
                  <div style={styles.scatterCell}>{scatterCard}</div>
                  <div style={styles.sideCell}>{histogramCard}</div>
                  <div style={styles.sideCell}>{segmentCard}</div>
                </div>
              )}

              {/* Brushed accounts table — same shared selection. */}
              <Card>
                <VStack gap={4}>
                  <HStack gap={2} vAlign="center" wrap="wrap">
                    <StackItem size="fill">
                      <Heading level={3}>Brushed accounts</Heading>
                    </StackItem>
                    <Text
                      type="supporting"
                      color="secondary"
                      style={styles.numeric}>
                      {stats.count === 0
                        ? 'No accounts match'
                        : stats.count <= TABLE_LIMIT
                          ? `${stats.count} accounts`
                          : `Top ${TABLE_LIMIT} of ${stats.count} by spend`}
                    </Text>
                  </HStack>
                  {tableRows.length > 0 ? (
                    <div style={styles.tableScroll}>
                      <Table<AccountRow>
                        data={tableRows}
                        columns={accountColumns}
                        idKey="id"
                        density="compact"
                        dividers="rows"
                        hasHover
                      />
                    </div>
                  ) : (
                    <div style={styles.emptyBody}>
                      <EmptyState
                        isCompact
                        icon={
                          <Icon
                            icon={hasSelection ? BoxSelectIcon : InboxIcon}
                            size="lg"
                          />
                        }
                        title="Nothing in the brush"
                        description="The current brushes exclude every account. Widen the rectangle or remove a chip above."
                        actions={
                          hasSelection ? (
                            <Button
                              label="Clear all brushes"
                              size="sm"
                              onClick={() => dispatch({type: 'clear-all'})}
                            />
                          ) : undefined
                        }
                      />
                    </div>
                  )}
                </VStack>
              </Card>
            </VStack>
          </div>
        </LayoutContent>
      }
    />
  );
}
