// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Cadenza — Week Planner',
  description:
    "MOBILE (390px shell) weekly publish planner for the creator brand Cadenza, week of Mon Jul 6 – Sun Jul 12, 2026 (frozen 'today' Sat Jul 4 sits in the PRIOR week, so the Today chip jumps to Monday and no day carries today styling): a 52px navBar (7-tick brand mark, 'Jul 6–12 · 15 posts', 32px Today chip) over a pinned 64px WeekDensityStrip — 7 merged 64px-tall column buttons, each stacking up to 4 platform-colored 6px dots (Lens/Pulse/Echo/Boards, 3:1-checked pairs) in slot-time order above an independent best-time heat band (heatScore 55/40/80/70/60/35/45 — Wed is tallest at 80 with ZERO dots, proving heat and load are separate channels) — then 7 day sections of 72px SlotCard media rows (48px id-derived gradient thumbs, dividers inset 76) with per-day counts 3+2+0+4+3+1+2 = 15 cross-checking the navBar suffix, the Queue tab badge, and the strip dots. Thu's 9:00/9:20 pair renders the 32px ConflictRibbon ('20 min apart' + 'Space out' → 10:20 AM with Undo) replacing exactly one divider; Wed renders the 44px empty row ('No posts — best time 6–9 PM' + Add). The signature move is long-press (450ms) drag: a dragLayer clone lifts, the origin row stays as a 40% dashed ReslotGhost, the hover day's card grows a 56px badge-carrying landing outline (best-time halo when the slot time falls inside the target's heat window — Thu 6:30 PM → Wed lands in 6–9 PM), and the PINNED strip re-renders projected dots (origin −1, hover +1) mid-gesture; the drop commits ONE store update that re-derives strip dots, both day headers, Queue order, and unmounts the ribbon if a member moved — with full non-gesture parity: every row's 44×44 ellipsis opens an action sheet (Move to…/Duplicate/Delete-with-Undo) whose two-detent MoveSheet (7-chip day radiogroup, inline hour/minute stepper time panel, sticky 48px Move) routes through the identical update call. Queue re-sorts live and rows jump back to their week day; Ideas holds 14 rows with 'Show 8 more' → 'All 14 ideas' (6+8=14); Settings derives per-platform counts (Lens 5 · Pulse 4 · Echo 4 · Boards 2 = 15) from the live rows and its Best-time-hints/Conflict-warnings switches genuinely toggle the heat bands and ribbon. At desktop container widths (≥720px) it renders as a centered 430px phone column, never a stretched relayout. Choose over mobile-parking-session when the surface is a multi-day PLANNING board whose signature is cross-section drag-reslotting under a pinned density strip, not a single live metered session with a countdown dial; choose over mobile-transit-companion when the object is a editable weekly schedule of owned content with move/duplicate/delete verbs, not a read-mostly departures feed with a trip runner; choose over any desktop calendar template when the brief calls for a phone-first 390px shell with sticky navBar/strip/tabBar, bottom sheets, long-press drag with button-path parity, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
