// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Alderbank — Banking Home with Spend Insights',
  description:
    "MOBILE (390px shell) consumer banking home for Alderbank where insights are a working filter, not decoration: a 52px navBar (alder-leaf mark with a rising-sparkline midrib, Eye/EyeOff privacy toggle, explicit Refresh) over a ~132px balance hero (44px account-switcher overline 'EVERYDAY CHECKING ••1428', 40px/700 maskableAmount $4,286.31), a 200×200 five-arc spendRing (r=80, strokeWidth 18, butt caps; Bills $541.90 / Groceries $486.20 / Dining $312.40 / Shopping $273.15 / Transport $164.85 = $1,778.50 spent, center 'Safe to spend $821.50' = $2,600.00 budget − spend), five 44px aria-pressed category chips, a 6-card 280×148 insightPeekRail (82px peek at 390, 24px at 320; every stat arithmetically true — Halewood $272.16 is 50.2% of bills, dining +$47.65 = +18.0% vs June's $264.75) with 6 real dot buttons, and a 45-row inset-grouped July ledger paginated 12→24→36→45 ('Show 12/12/12/9 more' → 'All 45 transactions'). The signature move is the category scrub: ONE setActiveCategory dispatch dims the other arcs to 0.25, fills the chip, filters the ledger to 14 dining rows behind a 'Showing Dining · 14 — Clear' pill, scrolls the rail to the matching insight card, swaps the ring center to '$312.40 · Dining · 14 transactions', and announces through the single sticky toastDock; the +$12.00 refund credit is category 'adjustments' and deliberately excluded from ring math. The navBar eye masks all 20+ currency figures through one width-stable maskableAmount ('$12,940.87' → '$••,•••.••', digits swap to bullets in 1ch cells under tabular-nums — zero layout shift), cross-wired to the More tab's Privacy-mode switch row. The 55%/large-detent account sheet swaps hero + ledger per account: Shared Household renders 4 deterministic 60px skeletonRows resolving to 3 rows on Refresh, Travel Vault shows the true-empty PlaneIcon state, and the footer totals $21,506.00 across 4 accounts. Cards tab lock-switch dims card art 40% and grows a '1 card locked' hero pill; Move tab validates on blur ('Enter an amount up to $4,286.31'), schedules with an Undo toast; More tab's Sign out routes through the centered alertdialog. Desktop container widths (>560px) render a centered 430px phone column, never a stretched relayout. Choose over mobile-p2p-payment-flow when the surface is a full banking HOME (balance hero, spend analytics ring, insight rail, multi-account ledger) rather than a single send-money flow; choose over mobile-parking-session when the object is a money dashboard with a category-scrub filter system, not a live metered session with a countdown gauge; choose over budget-tracker or any desktop template when the brief calls for a phone-first 390px shell with sticky navBar/tabBar, a bottom account sheet, and 44×44 touch targets; choose over mobile-transit-companion when the tabs carry financial verbs (Cards/Move/More) and the hero is a maskable balance, not a journey planner.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
