// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Fieldstone Market — Aisle Finder',
  description:
    "MOBILE (390px shell) in-store shopping companion for Fieldstone Market's 'Weeknight Run' list — a grocery list as a tight pathfinding game. A 52px navBar (28px F-monogram storefront mark · a 36px routeChip holding a 24px 12-segment ProgressRingChip + 'Next: Aisle 4' · 44×44 RefreshCw) sits over a STICKY stylized AisleStripMap (viewBox 358×268: five rounded strips for aisles 2/4/7/9/11 at 46px wide with ≥3:1 strokes, one 8px brand pin per todo item at cy = 36 + slot×40, an entrance dot, and a dotted marching-ants polyline that serpentines entrance → remaining aisles, alternating top-corridor/bottom-walkway entry by stop parity) plus a 32px routeFooter — '4 stops · 8 items · est. 6 min left' from the exact ETA law todo×20s + aisles×40s = 8×20+4×40 = 320 → 6 min. Below, the PickPathRail renders the 12-item fixture (3 done + 1 skipped + 8 todo = 12; 3+2+3+2+2 across Produce/Bakery/Pantry/Dairy/Frozen) in walk order: 60px check rows (44×44 role='checkbox' hit, 16px name + 13px 'Bay 3 · Shelf 2 · Qty 2' meta, visible 44×44 ellipsis — NO swipe anywhere), a dashed 'SKIPPED — END OF TRIP' card with 36px Add-back buttons, and fully-picked aisles collapsed to 44px 'Aisle 2 · 3 of 3 picked' rows. The signature move: checking a row plays a 200ms pin tick, re-routes the polyline (parity flip = the path visibly enters later aisles the other way), advances the routeChip to 'Next: Aisle 7', fills one ring segment, decrements the List tab badge, re-derives the footer ETA, FLIPs emptied aisles into PICKED, and announces via the ONE sticky Undo toast — all derived from a single items array. The ellipsis opens a two-card SkipActionSheet (View shelf location / Skip for now / destructive Remove — undoOverConfirm, no alert; Cancel card, first focus); 'View shelf location' opens a 55%↔large item sheet with a ShelfLocatorDiagram bay elevation (4 shelf slabs, brand product block, 'Aisle 7 · Bay 3 · Shelf 2 (second from bottom)') and a 48px 'Mark as picked' footer. RefreshCw shows a deterministic 4-row skeleton (fixed 60/45/70/60 widths) that resolves on the next tap with 'Updated just now'. Four tabs (List badge 8 · Stores · Deals · Account) persist scroll per tab; checking everything reaches a 'Trip complete' empty state with a reset. Choose over mobile-transit-companion when the journey is INSIDE one building with a synthetic aisle map the user's own check-offs rewire, not a transit trip on external schedule data; choose over mobile-podcast-queue when progress is spatial route pruning (pins, polyline, ETA-by-aisle) rather than a time-budget ledger over reorderable rows; choose over mobile-parking-session when the surface is a multi-tab list-driven companion whose map/list/ring/badge all derive from one checklist, not a single-screen dial with a sheet-driven money preview; choose over any desktop template when the brief needs the 390px shell, sticky map dock, bottom sheets, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
