// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Sayso — Speaking Drill Coach',
  description:
    "MOBILE (390px shell) pronunciation drill surface for Sayso where every attempt is a visual diff against the native speaker: a 52px navBar (quotation-mark-into-waveform brand mark + live lesson percent 58%, 'Lesson 4 · Ordering food' title, an 'Attempt 4' counter pill button opening the breakdown sheet) over a sticky phraseCard ('Me gustaría un café' 22px/700, 'Attempt 4 · Best 76' meta, 44px MasteryRing at 76), then the SyllableStressStrip — a 56px dual-contour SVG band (24-point native pitch line in text-secondary, learner line in brand orange revealed by stroke-dashoffset) over 8 stress-width syllable pill buttons (flex weights 30/38/30/48/30/30/30/48 summing with 6px gaps to the exact 326px card inner width) and a per-syllable lag row (+0…+140ms) — a 4-row attempt-history listCard (72px rows, 48px waveform thumbs from syllable scores, 'Weakest: rí · 54' blame lines) whose rows expand to 8 green/amber score chips + 'View phoneme detail', and a micDock (44×44 Play native, 72px hold-to-speak ShadowMeter with 8 native cadence rim ticks at onset/2400×360° and green/amber learner ticks 4px inside, 36px Run attempt). The signature move is ONE scripted attempt (hold the meter or press Run attempt — identical code path): a 2520ms rAF playhead sweeps the learner contour, flips pills green (lags 0/20/40ms) or amber (+80…+140ms) at each onset, then scores 83 — history inserts attempt #5 ([92,88,74,61,90,85,79,95] → 664/8), the MasteryRing sweeps 76→83, lesson percent ticks 58%→67% (mastered 7→8 of 12), the Review tab badge increments 2→3, profile attempts 217→218, and the single polite toast announces; re-running replaces attempt #5 so every aggregate is idempotent. A two-detent BreakdownSheet (55% syllable table with IPA/duration/latest-score chips; LARGE per-phoneme blame — /r/ 48 vs /i/ 74 — with coach tips) opens from the nav pill, phrase card, any syllable pill, or a history row. Review tab: segmented Ready/Done filter, swipe-to-Done 60px rows with mandatory 44×44 ellipsis fallback and Undo toast (undoOverConfirm), RefreshCw skeleton rows (60px exact geometry) resolving on the next user action. Phrasebook: 12 × 72px MasteryRing media rows (masteries summing 892 → 74% avg). At desktop container widths (≥720px) it renders as a centered 430px phone column. Choose over mobile-meditation-breath-player when the audio surface must DIFF a user performance against a reference (dual contours, cadence ticks, per-phoneme blame), not guide a breathing/playback session; choose over mobile-run-route-recap when the recap is per-attempt improvement history with expandable blame rows, not a single completed activity; choose over mobile-parking-session when the bottom dock is a hold-to-record instrument feeding a scoring pipeline, not an extend/end transaction footer; choose over any desktop template when the brief needs a phone-first 390px shell with sticky chrome, a two-detent sheet, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
