// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Tetherline — Luggage Scan Trail',
  description:
    "MOBILE (390px shell) anti-anxiety luggage tracker for Tetherline, frozen at 13:05 on Fri, Jul 4: a 2-tab surface (Bags / Alerts, 64px tabBar with a derived '2' badge) whose Bags tab opens on a 28px large-title list ('3 bags tracked · 1 divergence · 16 scans logged' derives live from 7+5+4 fixture scans) of three 72px gradient-thumb bag rows — TL-7F2K 'Checked duffel — SEA→LIS' wearing a 'Diverged at AMS' chip, TL-3M81, and the long-nickname truncation stress TL-9Q44 — plus an editToolbar edit mode (selection circles, Remove bag + Undo, per-row and toolbar Move up/down). Pushing a bag shows the 112px id-derived-gradient tagIdentityCard (TAMPER/BATTERY/LAST SCAN micro-stats), the 76px stalenessMeter whose confidence DECAYS between scans (max(0, 100 − round(min/3)) → 70/92/98%), a 7-link scanChainTimeline whose link glyphs age by fill (brand ≤60 min, mid 61–180, outline older) and end in a dashed staleness tail (6px per 15 min → 36px) with a pulsing 'now' dot, and — for the diverged bag only — divergenceLanes: YOU vs BAG lanes over one 05:00–12:00 axis, a merged 4px line forking at the 05:47 split diamond, and an 8-detent role='slider' playhead whose position rewrites the caption ('Bag departed AMS — 3h 20m behind you') and, once scrubbed past the split, arms a 'Reroute delivery' button beside the mandatory Step back/forward path. The reroute sheet's 3 radio rows (Hotel Alvor Baixa 18:00–20:00 free / LIS office 14:30 / courier €12) confirm-execute immediately per undo-over-confirm — sheet closes, chip flips to 'Reroute set · 18:00–20:00', persistent Undo toast restores exactly. Acknowledging the Alerts rows (row tap or ellipsis actionSheet) re-derives the badge 2→1→0, flips the chip to 'Acknowledged', and empties into a BellOff zero-action state; RefreshCw swaps either tab to deterministic skeletons that resolve on the next user action with 'Updated just now'. Sticky-in-flow toast dock, per-tab scroll/screen persistence, active-tab re-tap pops to root, desktop stage renders a centered 430px phone column. Choose over mobile-parking-session when the object is a FLEET of tracked items whose timelines split and go stale, not one live metered session with a pricing sheet; choose over mobile-run-route-recap when the scrubber threads two parallel actor lanes (you vs bag) and arms a recovery verb, not a single route ribbon's stats; choose over mobile-transit-companion when the journey is observed asynchronously through scans-with-decay rather than ridden live; choose over any desktop template when the brief calls for a phone-first 390px shell with tab bar, push stack, bottom sheets, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
