// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Nightcap — Tonight Picker',
  description:
    "MOBILE (390px shell) household movie-night decider for Nightcap, frozen at Fri, Jul 4: a 52px navBar (28px crescent-reel mark, 'Tonight', History push) over a 44px sticky dialSummary ('≤ 120 min · Energy ≤ 3' pill + '9 of 14 fit', SlidersHorizontal scroll-to-dial), then a 236px MoodDial — a 200px dual-thumb SVG ring (budget thumb sweeps 45–180 min over the left 144° arc with 45/90/135/180 ticks; energy thumb snaps 5 detents E1–E5 on the right; 28px thumbs in 44×44 slider hits) whose hub count and the two role=spinbutton stepper pairs (±15 min / ±1 energy, the input CONTRACT) all derive from ONE fitsDial filter over a 14-title fixture (9 fit at the default; 105 ⇒ 6, 135 ⇒ 10, cap 4 ⇒ 11, 75 ⇒ the Popcorn filtered-empty with a 'Reset dial to 120 min / E3' action). Below, a Crown frontrunner banner and the Round-of-8 bracket: each FaceoffPair is two flex cards (90px gradient art, 2-line clamp — the 63-char Wexford Sisters title is the stress — tally chips, Pick this + Details) joined by a fixed 42px Zap divider (158+42+158 = 358 at 390; 123px cards at 320). One bracketStore reducer drives every consequence: PICK benches the loser ('Benched until Jul 18' = Jul 4 + the Profile's 14-day stepper), collapses the round into decidedList rows, slides in the queued pair, re-derives the frontrunner and the Watchlist badge (6→5, count(status==='alive')), and posts a one-deep-snapshot Undo toast in the sticky dock at bottom:76; VETO (3 coins per member in the VetoTokenTray, spent Sam 1 + Riley 0 + Jo 2 = the 3-row veto log; remaining 2+3+1=6) routes through an attribution actionSheet (Cancel-first focus, rows disabled at 0 tokens) and auto-advances the opponent; dial edits mid-flight surface an explicit 'Reseed bracket (6 fit)' button, never an automatic reseed. Watchlist groups cross-check 6+2+1+5 = 'All 14 titles' with swipe-reveal Details/Veto blocks duplicated by 44×44 ellipsis menus, RefreshCw skeletons (60/45/70 + 40/55/30 widths) resolving on the next tap, and a sentinel-faded large title. A two-detent titleSheet (grabber button, 'Why it fits' fixture math, Veto LEFT of a 16px gap from Pick this) opens from Details or 450ms long-press. At desktop container widths (≥720px) it renders the standard centered 430px phone column. Choose over mobile-parking-session when the object is a multi-entity elimination DECISION (bracket, votes, veto economy) rather than one live metered session with a countdown gauge; choose over mobile-group-gift-pool when members spend a capped token budget against each other instead of pledging money toward one goal; choose over mobile-someday-maybe-sorter when the triage is head-to-head pairs feeding a single tonight verdict, not drag-to-dock deferral of a backlog; choose over any desktop template when the brief calls for a phone-first 390px shell with tab-bar navigation, bottom sheets, swipe rows, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
