// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Gatewise — Connection Dash',
  description:
    "MOBILE (390px shell) tight-connection war room for Gatewise, covering the 38 minutes between gates at MUC for AY 1442 → HEL (doors close 14:37, deplaned A26 at 13:59): a 52px navBar (44×44 gate-sign brand mark, 'MUC → HEL' 17/600, and a tricolor countdownPill — 'Buffer +14' green at slack ≥ 10, warning at 1–9, 'Buffer −3' red at ≤ 0 — in a 44×44 hit that scrolls the buffer card into view), a flightCard 60px row that grows a 44px error-tint gateChangeBanner ('Gate changed B44 → K21 · +8 min walk') plus a 20px gate chip when the scripted delay lands, a bufferCard whose 20px BufferBar decomposes the budget into flex-grow minute segments (spent actuals in muted brand tint, walk/tram/passport estimates in category colors, slack in success tint, and a 45° hatched OVERDRAFT segment once spent 7+14 = 21 plus remaining 8+12 pushes the bar to 41 of 38 units) with an 11px legend that always cross-foots (Walk 5 · Tram 7 · Passport 8 · Walk 4 · Slack 14 = 38), a five-row 72px CheckpointChain (24px nodes: done = brand fill + check, current = pulsing ring — static under reduced motion, upcoming = ≥3:1 rest ring; connector line; ETA chips recolored by the live slack band; a 36px 'Mark reached' affordance on the current row only, the whole row being one button), and a sticky-footer 'Backup plans · 3' 48px brand button. The signature move is the frozen sim clock: NOTHING advances except on checkpoint taps, so every state is deterministic — tap 1 (walk actual 7 vs est 5) drops the pill to +12 and re-derives every ETA; tap 2 (tram actual 14 vs est 7 PLUS the gate change flipping c5's walk to 12 min) sends slack to −3, flips the pill red, hatches the bar, injects the banner, AND auto-presents the two-detent RebookTray at medium with a sortNoteRow explaining its re-rank ('Sorted by seats left — buffer is negative': BA 951's 23 seats outrank LH 2237's 16:10 departure), rank badges FLIPing via transform only. Rebook rows hold seats immediately with a persistent Undo toast (undoOverConfirm — no confirm dialogs, no timers); the toastDock is sticky-in-flow above the footer and goes shell-absolute only while the sheet scroll-locks the shell. At desktop container widths (≥720px) it renders as a centered 430px phone column with hairline borders. Choose over mobile-parking-session when the domain is a time-race transfer whose budget bar, checkpoint chain, nav pill, and rebook tray must all flip together off one negative-slack event, not a payment meter whose sheet previews a priced extension; choose over mobile-transit-companion when the object is ONE fragile connection with a countdown ledger and fallback flights, not general line-by-line transit browsing; choose over mobile-run-route-recap when the moving cursor is a live 'you are here' progress state that mutates the plan, not a post-hoc scrubber over finished data; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky navBar/footer, a bottom sheet, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
