// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Lightline — Date Safety Check-in',
  description:
    "MOBILE (390px shell) pre-date safety net for Lightline that behaves like a flight checklist, not a panic button. A 52px navBar (lighthouse beam-arc mark · 'Tonight' · a 28px 'Armed · next 9:30' brand-tinted status pill, 11px/600 tabular) sits over four tabs (Tonight / Guardians / History / Me, 64px tabBar). Tonight stacks a 178px plan card (44px header '1 of 4 check-ins done' + 3×44 Where/With/Home-by rows), a 5×60px session-timeline card (armed 7:45 ✓ · arrived 8:02 ✓ · check-in 8:30 ✓ · check-in 9:30 DUE amber · home safe 11:30 — armed/arrived are events, not checkpoints, so 3 green nodes reconcile with 1-of-4), and two 64px GuardianChips (id-derived gradient avatars, state lines 'updated 8:30 ✓'), with a sticky 128px ringDock (bottom 64, above the tabBar) holding the 96×96 hold-to-confirm CheckinRing — 1200ms rAF fill on a 2π×44=276.46 circumference arc, 3× drain on early release, Space/Enter hold parity, '9:30' etched on a rim textPath, and a static 3-step fill + glow ring under reduced motion. The signature move: ONE completed hold fires completeCheckin() — a single sessionStore write that flips checkpoint c2, rewrites the pill to 'Armed · next 10:30', re-etches the rim, appends the green timeline node, flips BOTH guardian chips to 'updated 9:30 ✓', and announces through the one aria-live toast (five surfaces, screenshot-provable). The Me tab's labeled DEMO CONTROLS drive the deterministic escalation fixture: 'Simulate missed 9:30 check-in' arms a 64px amber banner, an amber 'Escalating · T-4:32' pill (5:00−0:28=4:32 ✓), and an auto-opened two-detent (55% / calc(100%−56px)) escalation sheet whose EscalationLadder shows T+5/T+10/T+15 rungs; each 'Advance +5 min' press adds 300s and fires the crossed rung (press 1 → Priya 'Notified 9:35', History gains the alert row). Cancelling is the ONE place confirm beats undo: a two-step in-sheet button that morphs to 'Confirm — send code word Marigold', with stray taps resetting step 1. History aggregates derive live (4+3+2+3=12 check-ins, 190+165+110+195=660min=11h 0m); 'Extend 30 min' proves the midnight rollover (11:30 PM→12:30 AM). Desktop container widths (≥720px) render a centered 430px phone column, never a stretched relayout. Choose over mobile-date-night-builder when the evening needs a LIVE armed safety session (checkpoints, guardians, escalation ladder) rather than itinerary planning with budget math; choose over mobile-parking-session when the countdown object is a person's check-in cadence with cross-surface guardian consequences, not a metered clock with tiered pricing; choose over mobile-transit-companion when the tabs orbit one armed session and its escalation state machine rather than live vehicle progress; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky docks, bottom sheets, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
