// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Kinloop — Family Day Lanes',
  description:
    "MOBILE (390px shell) family-day coordinator for Kinloop, frozen Friday Jun 12 at 1:15 PM: a sticky 96px header block — 52px navBar (24px four-loop knot mark, 'Friday, Jun 12', 44×44 RefreshCw) over a 44px 7-day DateScrubber (Jun 9–15 radio pills, 44×44 hits, active pill in the quarantined coral #E8604C with dark-on-coral 4.6:1 labels, 6px derived status dots: red while Jun 12 holds 1 conflict, amber once it holds 1 coverage gap) with a −8px-overlap 4-avatar family stack jumping to People. The Today body is a MemberLaneSpine: 44px hour rail (7 AM–9 PM, 14 h × 64px = 896px canvas, 15 min = 16px) beside four flex:1 member lanes ((390−32−44−18)/4 = 74px, measured never hardcoded) carrying 12 fixture events (23.0 distinct hrs, 19 attendance instances, 28.75 person-hrs — every aggregate derives from the events array), lane-spanning HandoffChip custody capsules (piano 4:00 Priya→Zoe, soccer 4:30 Marcus→Theo), a ConflictBraid where Priya's 'Design sync — Q3 homepage review w/ Ada' fully covers the 3:00 school pickup (two half-width chips, alternating-dash seam, 20px red resolver dot in a 44×44 hit), an 'everyone' dinner band fusing all four lanes at 6:30, and a fixed now-line at top 400px. The signature move is reassign-with-consequences: choosing 'Marcus (free)' in the reassign action sheet fires ONE update('H1', {driverId}) and the same render unbraids the conflict (1→0), swaps the scrubber dot red→amber (gaps 0→1: Sprint review 5:00–5:45), draws a 48px amber 45°-hatch coverage band UNDER the chips with a 44×44 AlertTriangle explainer, badges the People tab '2' (Marcus 1→2 drives) and his row pill, re-renders the still-open sheet's Driver row, and lands a persistent Undo toast (undo-over-confirm; exact inverse patch, 'Restored'). Week (7 × 60px rows summing live to 'All 46 events this week'), People (28/700 'Family' large title, 4 × 72px avatar rows with live 'N events · X hrs' and drive pills), Settings (three 51×31 switch rows with ≥3:1 rest tracks + a 15–60 min spinbutton stepper), navBar-refresh skeletons at exact fixture geometry, and a Sun Jun 14 true-empty state round out the tabs; desktop container widths (≥720px) render a centered 430px phone column. Choose over mobile-exam-countdown-planner when the day is COORDINATION across four people's parallel time lanes (custody handoffs, conflicts, coverage) rather than one student's plan-replanning; choose over mobile-transit-companion when the canvas is a multi-member vertical hour spine with lane-spanning tokens, not a single journey timeline; choose over mobile-therapy-session-prep when the signature mutation is a driver reassignment cascading through braid/dots/badges/hatches, not drag-assembly of talking points; choose over any desktop calendar template when the brief needs a phone-first 390px shell with sticky scrubber chrome, two-detent sheets, action-sheet verb pickers, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
