// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Snagline — Site Photo Checklist',
  description:
    "MOBILE (390px shell) gig/field-work photo-inspection surface for Snagline at Harbor Point Unit 12: a 52px navBar (corner-bracket brand mark, 'Harbor Pt · Unit 12', 28px CompletionRing button labeled '14 of 22 shots done, 64 percent complete' that opens the Report tab) over a 52px summary strip ('12 passed · 2 snags · 8 missing' + a Jump-to-zone pill opening a five-row anchored menu), then five sticky 40px ZoneRails (zone-code chip, uppercase name, aria-hidden 6px pips — brand fill done, error ring snag, ≥3:1 REST_GREY missing — plus the visible 'n/m' count) over a 2-column grid of 22 CaptureSlot tiles (172px = 100px media + 72px footer): missing tiles show a stroked framing silhouette (panel/junction/scaffold cycling by index) with four brand corner brackets and a brand-filled Capture button; shot tiles show an id-derived 135° gradient with a 24px StampBar (fixed 08:02–09:24 stamps, zone code, pass/snag glyph on a 55% scrim) and Retake→anchored-menu or error-tinted View-snag buttons. The signature move is the single-commit capture: the LARGE-detent Viewfinder sheet's Capture on GF-EL-05 fills the pip, bumps the rail 5/6→6/6, redraws the navBar ring 64→68% (15/22 = 68.18, round-half-up), drops the Report missing chip 8→7, recounts the summary strip and the 'Blocked: 8 missing shots · 2 open snags' reason row, and posts 'GF-EL-05 captured · Undo' through the ONE sticky toast dock (no auto-dismiss; Undo restores the exact prior slot and reads 'Restored'). 'Flag as snag instead' swaps (never stacks) to the MEDIUM-detent AnnotationSheet — 32px StampBar preview over a 96px gradient swatch, Low/Medium/High radiogroup with arrow keys, blur-validated note ('Describe the snag') — and Save snag pushes the tab badge 2→3 in the same commit. Snags tab resolves via ellipsis menu (execute + Undo, badge decrements); Report's chips jump-and-focus the slot's Capture button; Submit stays enabled and pulses/toasts the blockers until 0/0 flips the submitted banner; Sites lists one LIVE derived row and three static fixtures (18/18 · 100%, 5/16 · 31%, 0/12 · 0%). Tabs persist scroll position and state; re-tapping the active tab scrolls to top. At desktop container widths (≥720px) it renders as the standard centered 430px phone column, never a stretched relayout. Choose over mobile-camera-roll-organizer when the surface is a REQUIRED-shot checklist with per-zone completion math and a submit gate, not a free-form photo library to triage; choose over mobile-parking-session when the object is a multi-zone field inspection driven by one slots record (pips, rails, ring, chips, badge all selectors), not a live metered session with a countdown dial; choose over mobile-transit-companion or any desktop template when the brief calls for a phone-first 390px shell with sticky zone rails, a 2-up capture grid, bottom-sheet viewfinder/annotation flows, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
