// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Kindling — Event RSVP Chat',
  description:
    "MOBILE (390px shell) group-chat-native event planner for Kindling where the thread IS the event page: a 52px navBar (decorative flame mark — the only home of the raw #E8850C — 'Bonfire Night' 17/600 title with a 24px 'Sat Jul 11' muted date pill, 44×44 RefreshCw) over a sticky 64px QuorumMeter header ('QUORUM' overline + '3/6 in' 17/600 tabular count, an 8px track with explicit ≥3:1 light-dark rest fill, brand fill scaling inCount/6 transform-only, one 20px initialed avatar tick per 'in' attendee snapped at ordinal·(100/6)% — 58px slots at 390, 6×58 = 348 ✓ — and a 2×16 'Book' threshold notch at 100%, plus the 36px Plan pill that opens the sheet), then a full-bleed 12-message chat stream (1 system, 9 text, Maya's 'Lock it in ↓' rsvpBubble embedding a live In/Maybe/Out RsvpChipRow radiogroup — 80px chips, 36px visual in 44px hits — and her 'When works?' pollBubble embedding a 2×2 TimeGridPoll whose 124×64 cells heat by count/maxCount·32% brand color-mix: Fri7=2 · Sat5=2 · Sat8=4 · Sun2=2, cell sum 10 = per-person picks 10 ✓), a sticky 48px-toast dock at bottom:76, and a sticky 64px composer (controlled input + 44×44 round brand send). ONE attendee store owns everything: tapping 'In' on the bubble chips lands your tick at slot 4, flips the header to '4/6 in', keeps the two-detent (55% / calc(100%−56px)) Plan sheet's DUPLICATE RsvpChipRow in lockstep, and opens a persistent 'You're in — Undo' toast (undo-over-confirm, no timers); RefreshCw deterministically appends 'Leo is in'/'Noah is in' system messages to reach 6/6, announces 'Quorum reached — booking unlocked' exactly once, and enables the sheet's 48px Book button (disabled at 40% opacity with a derived 'N more needed' caption otherwise — drop to Maybe after quorum and it re-disables at '1 more needed' while the history message stays); booking appends the system message and offers 'Booked — Undo'. Sheet large detent adds the 8×60px attendee list (status-dot pills, error-colored OUT for Tess, the 33-char Priyadarshini ellipsis stress) and the poll grid at card width. At desktop container widths (≥720px) it renders as a centered 430px phone column. Choose over mobile-parking-session when the surface is a conversation whose messages embed live widgets (RSVP chips, availability heat poll) driving a pinned group-progress meter, not a dial-and-ledger utility around one metered object; choose over mobile-p2p-payment-flow when the job is many-person social coordination toward a threshold rather than a two-party transaction; choose over bottom-sheet-snap-explorer when the bottom sheet is a secondary planning surface duplicating in-thread controls, not the primary map-exploration mechanic; choose over any desktop messaging template when the brief demands the 390px shell, sticky chat chrome, 44×44 touch targets, and a thumb-reachable composer.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
