// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Milemark — Hours & Mileage Log',
  description:
    "MOBILE (390px shell) hours-plus-mileage logger for delivery/trade contractors, frozen at Thu Jul 2 2026, 3:45 PM: a 52px navBar (odometer-digit brand mark with a tire-tread tick row, 'Milemark', live 'Wk $492.00' pill) over four tabs (Week / Trips / Rates / Export, Export badged '2'). The Week tab leads with a TODAY hero card: a DayShiftBar (44px track + 12px mileage-tick lane) drawing worked fills (9:00–12:00 closed + an OPEN 1:00 PM segment ending exactly at the dashed 'now' rule) against 45°-striped drive segments, a 3-col stat row (Worked 5h 45m / Miles 24.5 / Earned $157.70), a 96×32 ±15m stepper (spinbutton, clamps 15–420 min), a 32px RateDisc donut whose hourly/mileage/bonus slice angles derive from cents, and 'Log odometer' opening a MEDIUM sheet with a 7-cell OdometerStepper (six integers + brand-ruled tenths cell, chevron spinbuttons, live delta line '048255.0 − 048244.7 = 10.3 mi' with a Matches-Trip-B check, Save-press validation on mismatch). Seven 88/60px day rows (40px RateDiscs or dashed empty circles, compact bars, Wed renders a bare 'Off' track) open a LARGE day-edit sheet with a 120px RateDisc + legend rows and editable worked segments (anchored Edit-times/Delete menus, exact-position Undo restores). The SIGNATURE move: setOpenDur() is the single choke point — dragging the bar's 44×44 edge handle or stepping ±15m re-derives, in the same frame, the navBar pill ($492.00→$498.00 at +15m = 15×40¢), hero stats, RateDisc angles, the week list's compact bar + '$163.70' trailing earnings, the 'Week of Jun 29 · 17h 15m · 105.0 mi' caption, and the Export tab's unsubmitted total ($312.50→$318.50). Trips rows swipe to a 72px Delete block (mandatory 44×44 ellipsis fallback + 450ms long-press garnish; deleting Thu Trip B shows week $485.82 until Undo); the fixture's odometer chain is continuous by construction 048150.0→048255.0 = 105.0 mi. Export marks Tue+Thu submitted ('Exported 2 days · $312.50' + Undo), zeroing the badge live. All money derives from integers (40¢/min, 6¢/tenth) — nothing stored. At desktop container widths (≥720px) it renders as a centered 430px phone column, never a stretched relayout. Choose over mobile-parking-session when the object is a WEEK-long timesheet ledger (per-day timeline bars, odometer arithmetic, submit/export flow), not a single live metered session with a countdown gauge; choose over mobile-roundup-goals when money is EARNED from logged minutes and miles that must reconcile against an odometer chain, not allocated from transaction round-ups; choose over mobile-exam-countdown-planner when the timeline bars record hours worked for pay rather than study load to replan; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky navBar/tabBar, bottom sheets, swipe-reveal rows, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
