// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Larkspur Rx — Prescription Pickup',
  description:
    "MOBILE (390px shell) pharmacy-pickup surface for Larkspur Rx, frozen at 1:45 PM: a 52px navBar (28px larkspur flower mark — stem splitting a capsule petal — a compact 'Pickup' title that fades in via an IntersectionObserver sentinel, and a 44×44 Refresh that announces 'Updated just now'), a 28px ready-window day band (9 AM→7 PM in %, NOW tick at 47.5%, highlighted 2:30 PM window from 55%→100% with a 2px brand leading edge, 'Ready in 45 min' derived from READY_MIN−NOW_MIN), six 72px rxSelectRow checkbox-buttons — each a 48×28 capsule refillGauge (2/5, 4/6, 1/3, dashed-NEW 0/0, 3/4, 1/2), a two-line med stack, a right-aligned dual-price pair (insurance 16px/600 over struck-through cash 13px), and a 22×22 check — a CONDITIONAL error-tinted interaction card that mounts only while Azithromycin (rx-7714) AND Warfarin (rx-8003) are both selected (with a 36px 'Review pair' scroll-to button and +3 min consult added to the wait), a 4-row pharmacy card, a sticky-in-flow statusPill, and a 108px sticky cost footer. The signature move is derived-state discipline in a domain usually rendered as dead paper: count, $24.50 insurance total, $48.85 savings, the ~4 min counter-wait, the warning card, and the pickup pass are ALL pure functions of the selection — toggling Sertraline off rewrites the footer to '2 items · $12.50', the meter caption, and (on reconfirm) the large-detent pass sheet's code LK6248→LK9958 with provably different pseudo-barcode bar widths (each bar ((charCode >> 2i) & 3) + 2 px). The pass card's 'Boost brightness' switch swaps to a #FDFDF8/#191632 max-contrast scan surface in BOTH schemes (deliberate light-dark exemption, ≈15.9:1). Stress fixtures live in the six rows: the 'Hydroxychloroquine Sulfate 200 mg — dispense as written' single-line ellipsis at 320px, its $0.00 COVERED insurance price over struck $148.72 cash, the 0-of-0 NEW-fill gauge, the interaction pair, empty selection (disabled confirm, 'Select items for an estimate'), and the all-six maximum ($49.50 / $230.07 saved / LK1131 / 10 min). At desktop container widths (>560px) it renders as a centered 430px phone column with hairline borders, never a stretched relayout. Choose over mobile-parking-session when the object is a composable multi-select ORDER whose pass/code/totals derive from selection state, not a live metered session with a countdown gauge and extend/end verbs; choose over mobile-p2p-payment-flow when the money math is dual-pricing comparison (insurance vs. cash savings) across selectable rows, not a keypad-driven amount with splits and fees; choose over mobile-transit-companion when the meter is a single availability window on a day band, not departure countdowns across a 4-tab shell; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky navBar/footer, a bottom sheet, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
