// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Vettra — Pet Vet Timeline',
  description:
    "MOBILE (390px shell) pet-health surface for Vettra, frozen at Sat Jul 4 2026: a 52px navBar (24px paw-with-ECG mark · a petSwitcher button with 28px id-derived gradient avatar — Biscuit amber 135° #F59E0B→#B45309, Mochi violet #8B5CF6→#4C1D95 — opening an anchored two-pet menu · 44×44 RefreshCw) over a sticky 64px due-soon rail of scroll-snap chip buttons ('Apoquel · today', 'Refill · 6 days', 'Rabies · 21d', 'Bordetella · 108d overdue' in the error pair) that jump-and-flash their targets, then a full-bleed reverse-chron timeline: year h2 dividers (2026/2025/2024), 72px media rows whose 40px type nodes wear static VaccineHalo urgency rings (>180 d = 52px hairline, 31–180 = 48px 3:1 amber, ≤30 = 44px 3px brand, overdue = 42px 3px error — words always restate the tier), WeightSpark stitch cards (320×56 polyline, 24.1→30.2 lb across 7 checks with a dashed 30.0 vet-flag rule; Mochi's declining 9.8→9.1 lb series exercises the below-baseline flag clamp), and 'All 14 entries' terminal captions. Meds tab: inset-grouped DoseTracklets — whole-row 'Log today's Apoquel dose' button, 14-pip Jun 21–Jul 4 strip (12 given + 1 missed Jun 27 + 1 open = 14 ✓, missed pips wear a 1.5px error boundary), a 36×6 ringed drain track, '12 of 13 given · 1 missed' caption, and a 44×44 ellipsis menu (Log/Skip/Request refill/View history — history holds the 'Amoxicillin-Clavulanate 62.5 mg' truncation stress; 450ms long-press is garnish). The signature move: logging the dose is ONE meds patch with FOUR consequences — pip settles open→given, supply 6→5 rewrites the rail chip, 5 ≤ threshold 5 fires the derived 'Apoquel refill due Thu, Jul 9' node ('All 15 entries'), and the Meds badge unmounts 1→0; Undo restores the exact prior object and all four revert, while Mochi's per-pet state (badge 1, 13+1 Methimazole pips, 2 chips) survives round-trip switches untouched. Records tab: 60px document rows ('2.1 MB · PDF · May 8 2026'), RefreshCw-driven 4-row skeleton at exact 60px geometry (60/45/70 + 40/55/30 widths, shimmer dies under reduced motion) resolving to 'Updated just now'; a two-detent (55% / calc(100%−56px)) record sheet whose 90-word May 8 vet note forces the medium-detent inner scroller. Choose over mobile-parking-session when the object is a longitudinal per-entity health LEDGER (timeline spine + med adherence + derived refill forecasting), not a live metered session with countdown gauge; choose over mobile-creator-pulse when mutations ripple across TABS (badge, rail, timeline caption) rather than along a time scrubber; choose over medication or habit desktop trackers and any desktop template when the brief demands a phone-first 390px shell with sticky navBar/dueRail/tabBar, bottom-sheet detents, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
