// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Chalkline — Session Notes',
  description:
    "MOBILE (390px shell) tutor session-note editor for Chalkline, frozen on Dana Reyes's Jul 4 Algebra II session with Maya Okafor, where every input rewrites the parent recap live. Four tabs over a 64px tabBar (Students/Sessions/Recaps/More); the Sessions flagship stacks a Minutemap (56px track of 12 tap-cycle segments, 5 min each — initial 2/5/3/2 segments = 10/25/15/10 = 60 min, legend chips recompute counts × 5 on every tap and 0m chips dim to 40%, never hide), five 96px ConceptMasteryLadder rows (4×44×44 rung radios with arrow-key movement; 3-dot ghost strips paint three prior sessions' rungs — quadratic factoring [1,2,2] puts one dot over rung 1, two over rung 2; unselected rungs carry an explicit ≥3:1 boundary border, per-column history sums 9/11/14 → 1.8/2.2/2.8 averages), a 4-chip homework grid (36px chips in 44px hits), a live RecapComposer (rating→phrase map 1 'needs foundational review' … 4 'has mastered this'; opening sentence derives from the minutemap — 'We spent 25 minutes on new material, 15 on practice, and 10 each on warmup and review.'; changed sentences flash a 240ms tint, removed under reduced motion; unrated concepts are omitted behind an 'n concepts unrated' pill), a 3×72px past-session timeline (avg chips 2.8/2.2/1.8 — identical to the sparkline math), and a sticky 48px Send footer riding above the tabBar. The signature beat: tap rung 3 on Quadratic factoring and the composer sentence rewrites in place, the group chip flips Focus→Progressing (groups 2/2/1 → 1/3/1), and the Students tab's 64×24 TrendSparkline last point lifts 2.8→3.0 (sum 14→15) with 'Rated just now'. A two-detent (55% / calc(100%−56px)) sheet previews the recap exactly as Amara Okafor will read it — TimeSplitDonut degrees = minutes × 6 with the Minutemap legend strings verbatim — with an in-sheet Send at the LARGE detent; Send is undo-over-confirm through the single sticky-in-flow toast dock (no timers), and a session-picker actionSheet (context header, four 56px rows, separate Cancel card) swaps the editor to read-only sent notes (rungs at 35% opacity, 'draft unchanged' banner). Per-tab screens and scrollTop persist; active-tab re-tap pops to root. At desktop container widths (≥720px) it renders as a centered 430px phone column. Choose over mobile-parking-session when the sheet is a document PREVIEW built live from many small editor inputs (ratings, segment tags, chips), not a transaction configurator writing one pending value back onto a gauge; choose over mobile-story-planner when the one store fans out into derived PROSE and grouped aggregates rather than an ordering array across strips and steppers; choose over mobile-event-rsvp-chat when the surface is a single-author professional log with a send/undo lifecycle, not a multi-attendee chat quorum; choose over any desktop grading/notes template when the brief demands the 390px shell, 44×44 rungs, tap-cycle tagging tracks, and bottom-sheet preview.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
