// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Denari — Currency Pockets',
  description:
    "MOBILE (390px shell) traveler's split-wallet for Denari on the 'Kyoto & Lisbon' trip (Day 7 of 12, 6 days left): a 52px navBar (28px interlocking half-moon Denari mark, a stacked 'USD TOTAL' / $1,293.60 tabular ticker that always re-derives as Σ round(balance×rate) over the four pockets — 453.60 + 418.50 + 190.50 + 231.00 — and a 44×44 ArrowLeftRight exchange button) over a two-tab surface. The Wallet tab holds four 76px pocket-meter rows (40px currency chip circle, name+tag line, trailing balance over USD): each row's 4px pacing bar and '€46.50 of €70 today · 6.0 days runway' caption derive spentToday LIVE from today's ledger entries so row and ledger can never disagree — JPY sits at 124% wearing the error recolor + 'over plan' caption, THB at 95% proves the ≥100% boundary, GBP at 0% shows the bare ≥3:1 rest track — with swipe-to-reveal 72px Spend blocks, mandatory 44×44 ellipsis actionSheets (Spend / Exchange / View activity / destructive Close pocket → centered alert whose committing verb is 'Exchange', never a disabled button), and a sticky 'New spend' footer at bottom:64. The Activity tab is an 11-entry TODAY (−$157.17 = 50.22 + 75.60 + 31.35) / YESTERDAY ledger with 16px EXCHANGE badge pills, an 'All 11 entries' terminal caption derived from ledger length, and a navBar RefreshCw → 4 deterministic skeletonRows → 'Updated just now' status flow. The signature move is the two-detent exchange sheet: a dual-readout slider (0–300 step 5, full slider a11y) counter-rolls '−€120.00' up and '+¥18,960' down (120 × 158.00 locked = 160.00 mid × 0.9875), shades the 1.25% spread as a hatch band at the fill tip, and drains a 28px rate-lock ring from 0:30 — at expiry the confirm dims to 40% and a 'Refresh rate' secondary re-quotes the same 158.00; committing moves both pockets, pulses and digit-rolls both rows, re-derives the ticker to $1,291.98, prepends an EXCHANGE entry carrying the −$1.62 spread (= exactly the ticker delta), and badges the Activity tab. A full-screen spend-ticket cover (real-button keypad, never OS keyboard art) previews 'After this: ¥60,500 left · today ¥12,700 of ¥9,000 (141%)' with a live-recoloring bar before an immediate commit + Undo toast that restores balance, entry position, and header to the cent. At desktop container widths (≥720px) it renders as a centered 430px phone column. Choose over mobile-banking-home-insights when the domain is multi-currency travel envelopes with per-day pacing and an FX exchange flow, not a single-account home with category insights; choose over mobile-p2p-payment-flow when money moves BETWEEN the user's own pockets under a countdown rate lock rather than to a contact; choose over mobile-parking-session when the sheet's job is a dual-denomination slider trade with cross-pocket consequences, not extending one timed session; choose over any desktop template when the brief calls for a phone-first 390px shell with tab persistence, bottom sheets, swipe-reveal rows, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
