// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Lists & Inputs — Specimen Gallery',
  description:
    "MOBILE (390px shell) SPECIMEN GALLERY — the mobile kit's visual contract for list rows and input controls, rendered as 13 annotated specimens under sticky h2 sectionHeaders (top:52 under the 52px navBar, whose 44×44 Sun/Moon toggle flips colorScheme on the shell so both themes exist by construction). Every specimen sits in a hairline SpecimenFrame with 11px/500 tabular-nums annotations citing exact px anatomy: S1 the three canonical rows (44px utility with 13px meta + 16px chevron, 60px standard with 40px avatar and the 'Katarzyna Wojciechowska-Brzęczyszczykiewicz' single-line-ellipsis stress, 72px rich with 48px r12 thumb and three lines over a 68px-inset divider); S2 a FROZEN swipe-reveal at translateX(-152px) exposing 76px Mute + 76px Delete blocks (destructive LAST) above the mandatory 44×44 ellipsis-fallback row; S3 live single-open disclosure rows (aria-expanded, chevron rotates 90°); S4 a 320px nested scroller of 26 contacts in 10 lettered sections with the letter-•-letter indexScrubber rail — pointer scrub shows the 56px HUD circle, and the rail is ONE focusable role='slider' with Arrow/Home/End; S5 live load-more ('Show 4 more' twice → 'All 12 items' caption), which focuses the first appended row and announces '4 more loaded' through the single polite toastDock (sticky bottom:16 per the foundations amendment); S6 true-empty (InboxIcon, 'No messages', one 36px action) and filtered-empty ('No results for “xq”', 'Clear search') per exact emptyAndSkeleton anatomy; S7 three 60px-geometry skeletonRows (widths cycling 60/45/70 and 40/55/30) plus 2-up tiles under ONE shared 1.6s shimmer removed under reduced motion; S8 a whole-row role='switch' with the exact 51×31 track / 27px white thumb / 20px travel; S9 a 96×32 stepper with named Increase/Decrease buttons and a role='spinbutton' value (min 0 / max 10, exhausted half at 35% opacity); S10 a validate-on-blur email formField (48px input, 16px text zoom floor, error clears mid-keystroke once valid); S11 six toggleable 32px filter chips with 44px hits (one 'Longest-chip stress label'); S12 the FROZEN searchFlow focused-empty composition (36px field in a 52px bar, brand Cancel, Recent header + Clear, three 44px recents incl. a 55-char ellipsizing query); S13 a full-bleed CSS scroll-snap carousel of 280px cards with next-card peek. At desktop container widths (≥720px) it renders as a centered 390px column — a specimen gallery that reflows stops being a contract. Choose over composer-state-gallery when the reference sheet is the MOBILE kit's list/input primitives rather than a desktop composer's state matrix; choose over mobile-parking-session or any mobile product surface when the deliverable is the annotated px-anatomy contract reviewers diff against, not a branded app scenario; choose over dashboard-executive-summary or any desktop template when the brief calls for the 390px phone stage with sticky navBar, inset-grouped cards, and 44×44 touch law.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
