// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Airlume — Stream Preflight',
  description:
    "MOBILE (390px shell) go-live ritual for Airlume creator Ayla Reyes (@aylalive): a 52px navBar (44×44 Close, 22px ReadinessRing whose arc is metGates/7 × 360° — initial 4/7 ≈ 206°, dash 35.0/61.26 — beside the 'Go Live' title, 44×44 Bell with a notify dot) over a 194px streamCard (120px id-derived SVG gradient cover with an equalizer skyline, one-line 'Late Night Synth Build Vol. 12', Music + Live Production chips), a 274px SignalMeterCluster ('2 of 3 green' live caption over three 76px meter rows, each an 18px label line plus a 28px sparkline of exactly 24 fixed-fixture bars: Bitrate 4,212 kbps green with '+1,712 headroom', Audio −14 dB green in [−20,−6], Battery 18% RED with a 36px 'Plug in' fix → 64%), a 243px REQUIRED card of four 60px ChecklistGateRows (title/destination met with brand-check glyphs; copyright scan and moderator UNMET with error-ring lock glyphs, 2px aria-hidden lock-tether lines running down the card toward the arm bar, and 'Run scan'/'Assign' one-assignment fix verbs), a 182px OPTIONAL card of three whole-row 51×31 switches, and a 124px stickyFooter (36px 'Review blockers (3)' ↔ 'Go Live' aux over the 56px CountdownArmBar). The signature move is the jointly-gated slide-to-arm: 7 gates = 4 blocking checks + 3 meters, and every toggle re-derives ONE useReducer store — ring arc, arm readiness/fill, aux label, cluster caption, and the notify sheet's recipient math (941 push + optional 343 email = 1,284) move together with zero duplicated flags. Completing the slide (release ≥85% of pointerdown-measured travel; Enter/Space arms directly) runs a T-minus 5 countdown whose fill sweeps 20%/s — any tap aborts with an Undo toast that re-arms at a fresh T-5 — and at 0 the navBar flips to a 12%-error-tinted 'ON AIR · 00:00' pulse-dot treatment with a 1s elapsed clock; 'End stream' routes through Undo. A rejected slide rubber-bands and pins a BlockerCallout pill to the first unmet gate (deterministically the copyright scan), scrolled into view, with a 55%-detent blockers sheet as the button path. At desktop container widths (≥720px) it renders as a centered 430px phone column, never a stretched relayout. Choose over mobile-parking-session when the surface is a gated GO/NO-GO ritual whose slide-to-commit is fenced by live meters and a checklist, not a running meter session with tiered pricing math; choose over mobile-caption-ab-lab when the drag gesture is an arming threshold with a countdown consequence, not a comparative crossfade between variants; choose over mobile-transit-companion when the screen's whole purpose is one irreversible-feeling launch verb made safe by derived readiness plus Undo, not multi-leg monitoring; choose over any desktop template when the brief needs a phone-first 390px shell with sticky navBar/footer, bottom sheets, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
