// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Earmark — Up Next Queue',
  description:
    "MOBILE (390px shell) podcast-queue surface for Earmark that treats listening time as a budget, frozen at the 4:10 PM BASE_MIN: a 52px navBar (28px folded-corner Earmark mark whose fold doubles as a play triangle, 'Up Next' h1, Edit⇄Done text button + 44×44 RefreshCw) over a 48px queueLedger ('UP NEXT · 6' / '2 hr 32 min · Ends 6:42 PM' — remainders 32+31+21+24+18+12 = 138 min + 14 now-playing = 152, all tabular), one listCard of six 72px queueRows whose NOVELTY is the divider-as-meter: the 2px bottom hairline inset 104px renders each episode's played fraction in brand indigo over the border track, so a 0% row (Ledger Lines, with its ~90-char stress title) reads as a plain divider directly above Night Static's 66.1% meter. Rows carry a 44×44 grip (pointer drag reorders, swapping on 36px midpoints), deterministic show-derived gradient artwork tiles (no images), '#n' position overlines, downloaded glyphs (rows 1/3/6 = the Downloads tab's 46.2+59.5+11.5 = 117.2 MB, echoed by Profile's storage row), swipe-to-reveal −72px Archive (white on #4338CA ≈ 8.6:1) with the mandatory ellipsis-menu fallback, and Edit-mode ChevronUp/Down pairs. Below: a sticky-in-flow toastDock (bottom 142, persistent Undo, no timers), a 66px miniPlayer dock (2px 65.9% progress hairline, 'Up next:' line derived from queue[0], Moon sleep chip, skip-30, play/pause) stacked flush above the 64px 4-tab tabBar with a live Listen badge. The signature ripple: every reorder, archive (undo-over-confirm: 152−24 → '2 hr 8 min · Ends 6:18 PM', Undo restores the exact index and 6:42 PM), Discover add (+38 → 7:20 PM), and skip-30 (9090 s floors to '2 hr 31 min · Ends 6:41 PM') re-derives ledger, terminal caption, positions, badge, and miniPlayer from ONE `queue` array in the same render. Also ships: a 55%-detent Now Playing sheet with a six-option sleep-timer radiogroup ('End of episode (14:00 left)'), a Discover snap carousel (min(140px,42%) cards, 44px page-dot buttons, follow toggles) + Trending Add pills, a 4-row 72px skeleton refresh cycle with shared shimmer (removed under reduced motion), archive-to-empty ('14 min · Ends 4:24 PM' at zero), and per-tab scroll persistence with active-tab re-tap-to-top. At desktop container widths (≥720px) it renders as a centered 430px phone column with hairline borders — never a stretched relayout. Choose over mobile-transit-companion when the object is a user-ORDERED media queue whose sum is a time budget (reorder/archive/add all move one deterministic end-time), not a live departures board; choose over mobile-meditation-breath-player when the surface is queue logistics around many episodes rather than one continuous playback session; choose over mobile-parking-session when the ledger derives from a mutable list instead of a single metered countdown; choose over mobile-camera-roll-organizer when rows are sequenced (positions matter) rather than triaged into albums.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
