// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Pinbay — Parking Spot Memory',
  description:
    "MOBILE (390px shell) 'where is my car' memory surface for Pinbay — no map tiles, no payments — with four tabs (Find / Drop / History / Places) under a 52px navBar and a 64px tabBar whose Find badge reads the live '62m' meter. Drop is the builder: a Garage/Street/Lot segmented row (36px track, radiogroup + arrow keys) swaps a 358px card between a stylized SVG garage cross-section (GarageLevelStack, viewBox 326×320: five isometric skewX slabs at collapsed top-Ys 100/122/144/166/188, a 14px LIFT shaft at x=196, a 36×20 car chip and 24px teardrop on the pinned level), a six-zone curb strip (6×54 = 324+2 = 326, Blue/Red/Loading ≥3:1 pairs), and a 24-stall lot grid (6×49+5×6 = 324+2 = 326, C-11 seat-able) — the signature 450ms 'Hold to drop pin' in the 80px sticky footer fans the slabs to top-Ys 8/66/124/182/240 while a 50%-opacity ghost car tracks pointer Y and slab bands illuminate, release seating the pin; an HTML-absolute P1–P5 rail (5×44 + 4×8 = 252) is the mandatory always-visible button path with aria-pressed. One activePinStore write cascades everywhere: Find flips empty-state → walk-back card with a 96×96 SpotDecayTimer coin (outer meter ring 2π·44 ≈ 276.46, dashoffset 276.46·(28/90) ≈ 86.01; inner amber freshness ring 2π·34 ≈ 213.63, dash 213.63·(28/240) ≈ 24.92; invariant 62+28 = 90), History grows a derived pending row, the tab badge appears, and the toastDock announces. The CueChipTrail renders ONE cue array both directions — park order 1→5 with GripVertical drag (30px-crossing swaps) plus Edit-mode chevron buttons, navBar Cancel/'2 Selected'/Done and a 64px editToolbar with leading destructive Remove; walk-back order reversed with renumbered discs, per-cue step counts summing 40+55+35+30+20 = 180, and checkable circles feeding '2 of 5 cues passed' in the two-detent (55% / calc(100%−56px)) walk-back sheet whose 'I found it' completes the session. Clear pin is undo-over-confirm: the actionSheet's destructive last row executes immediately and the persistent Undo toast restores badge, pending row, and checks in one assignment. History refresh shows 4 deterministic 60px skeletons (60/45/70/60% / 40/55/30/40%) resolved by the next user action; aggregates derive live (45+75+120+60 = 300 min = 5h 0m, 'All 5 sessions', 12+7+3 = 22 visits saved). At desktop container widths (≥720px) it renders as a centered 430px phone column, never a stretched relayout. Choose over mobile-parking-session when the object is REMEMBERING a location in 3D space (garage levels, cues, walk-back) rather than a live metered session with tiered pricing and extend/end verbs; choose over mobile-store-aisle-finder when the memory is user-authored (drop a pin, record cues) rather than navigating a known store layout; choose over mobile-open-house-router when there is ONE spot to return to, not a multi-stop route plan; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky chrome, bottom sheets, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
