// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Bellwether — Credit Factors',
  description:
    "MOBILE (390px shell) credit-score decomposition surface for Bellwether (model v3, Maya Okafor, score 713 of 850): a 52px navBar (32px compass mark · 'Bellwether' wordmark that crossfades to a 28px scoreChip once an IntersectionObserver sentinel scrolls the hero under · 44×44 RefreshCw) over a decomposed gauge dial — five weight-proportioned arc segments (84/72/36/24/24° = weights ×2.4°, sum 240°), each a muted capacity track plus a health-length hue fill (96/55/83/75/51% → green/amber/green/amber/red), 2px body-color boundary separators, and a needle at 180.2° sweep — then a 44px score row (40px/800 '713' + 12-month sparkline 694→713), five 128px factor cards whose contributions cross-check exactly (185+91+68+41+28 = 413 → 300+413 = 713; maxPts sum 550), a Factors braid of five aligned 12-month sparklines sharing ONE scrubber (the whole card is a single role='slider', ArrowLeft/Right steps months, drag snaps a 1.5px brand rule and re-derives all five trailing values + the month-readout card), a full-bleed Alerts feed (12 rows, 2 unread matching the tab badge, swipe-to-mark-read at −72px with the mandatory 44×44 ellipsis fallback, Undo toast restoring the badge, 'Show 6 more' → 'All 12 alerts'), and a 64px tabBar where Simulate is an aria-haspopup launcher, not a screen. The signature move is the two-detent what-if simulator sheet (medium 55% leaves the dial visible): three levers — utilization slider 68→8 in tens ((68−target)×0.3 → +18), on-time-months stepper (months/3 → +4), close-oldest-card switch (−12 as age −9 + mix −3, flipping the age segment green→amber at 72%) — write deterministic deltas that move the needle (713→735 with a 24% brand ghost band and dashed actual-needle), lengthen the utilization fill 55→66%, grow '+18 pts' deltaBadges with struck actuals on the cards, re-sum the DeltaChipStack (+18 +4 −12 = +10 → 723), and flip the navBar chip to '735 ▲+22' — closing the sheet reverts every surface instantly because projection overlays render only while it is open (lever values persist for reopen). At desktop container widths (≥720px) it renders as a centered 390px phone column, never a stretched relayout. Choose over mobile-banking-home-insights when the object is ONE decomposable score with a rehearsal sandbox — weight-proportioned arcs, cross-checked point math, and a projection sheet — not an accounts-and-transactions home feed; choose over mobile-parking-session when the sheet's levers project a hypothetical (ghost band + revert-on-close) rather than commit a purchase that rewrites receipts and totals; choose over bottom-sheet-snap-explorer when the two-detent sheet is a means to cross-surface consequences (needle, arcs, badges, chip) rather than the sheet mechanics being the subject.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
