// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Selvage — Living Fit Profile',
  description:
    "MOBILE (390px shell) thumb-first fit-profile builder for Selvage: a 52px navBar (tape-loop 's' mark, compact 'Fit' title, FitScoreChip — 20px completeness ring at 288°/80% beside 'Fit 78' where 78 = round(467/6)) over a scrubbable MeasureTapeDial (80–120 cm SVG strip at 16px/cm panning inside a fluid window, 0.5 cm detents, 88×44 magnifier lens '98.0 cm / 38.6 in', flanking 44×44 ∓/± steppers, cm|in segmented toggle, role='slider' with Arrow/Home/End keys), a SilhouetteFitMap (240px stylized figure with four ≥44px tappable ease zones tinted tight/true/loose vs the Arno Trucker garment spec — chest 4 true · waist 12 loose · hip 6 true · inseam muted '—'), a 6×60px BrandFitLedger (confidence bars with printed %, conf-desc → justUpdated → alpha sort, 200ms FLIP re-sort, 'Updated' badges, out-of-range verdicts like 'Below Arno S (88–93)' at the 80 cm bound), a sticky toastDock, a 72px BagTray whose two size chips pulse when they re-derive, and a 64px Shop/Fit/Bag/You tabBar with per-tab scroll persistence. The signature move is scrub-with-consequences: every half-cm detent re-verdicts all six brands, re-tints the silhouette, and re-sizes both bag items in one render — scrubbing 98→101 flips exactly 3 rows M→L (Kessler and Rhode crossing 98, Arno crossing 99; Duval already L, Motoyama M through 102), re-sorts Rhode above Field & Loom, pulses both bag chips, clears manual overrides, and announces once ('Sizes updated · 3 brands, 2 bag items'). Ledger rows and silhouette zones open a two-detent (55% / calc(100%−56px)) brand sheet — PDP size chips that override a bag item's size until the next tape change, 44px size-chart rows, an Arno garment-measurement block the zone tap scrolls to, and a confidence bar ('67% · 2 of 3 measurements on file', 'Add shoulder → 100% confidence'); committing shoulder 46 via the inline validated formField (30–60 cm, blur validation) closes the ring to 100%, lifts every confidence to 100 (600/6 ✓), and toasts 'Shoulder added · Fit 100'. All verdicts, confidences, ease bands, and the nav score are pure functions of the five measurement fields in ONE fitProfile owner — no verdict state is ever stored. At desktop container widths (≥720px) it renders as a centered 430px phone column with hairline borders. Choose over mobile-banking-home-insights when the one scrubbed value must re-derive many verdict surfaces (ledger, silhouette, bag) rather than filter a ledger; choose over mobile-parking-session when the primary input is a continuous measurement slider with size-chart math, not a timed session with tiered pricing; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky chrome, a bottom sheet, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
