// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Dovetail Rx — Med Schedule & Interaction Untangler',
  description:
    "MOBILE (390px shell) 4-tab medication-schedule surface for Dovetail Rx, frozen at 12:40 PM Fri Jul 4, where drug interactions are SPATIAL. Today renders four slot sections (Morning 3 taken · Noon 3 · Evening 2 · Night 1 = 9 doses, ring 3/9) as inset-grouped cards of 44px dose rows; the Noon card draws its Ibuprofen×Lisinopril MAJOR conflict as an amber cubic-bezier tether ('M 10 22 C -2 45, -2 89, 10 112', 3px stroke, 45·i+22 row-index math) along the card's leading edge, with a 36px conflict footer row as the aria-visible twin. Interactions holds an 8×8 InteractionMatrix in a 422px horizontal snap rail (sticky two-letter code column LS/LV/MT/SR/CA/IB/FE/ML, 44×44 role=grid cells with arrow-key roving focus, 8 voided diagonal self-cells, 28 mirrored pairs = 3 monitored + 25 neutral) plus a 3-row monitored-pair list; Cabinet lists 8 meds summing to exactly 286 pills ('286 pills on hand · 1 low' — only Melatonin 7 ≤ 10); History shows the 7-day 60-of-63 = 95% weekly ring and a live today ledger. SpacingTimerChips count gap rules off the frozen clock: Ferrous sulfate waits ≥2h after Calcium (untaken → 'Wait · 2h after Calcium'; taken at 12:40 → 'Clear · gap 5h 20m' = 1080−760; skipped → 'Blocked · Calcium skipped'), and Calcium sits 'Clear · gap 5h 28m' after the 7:02 Levothyroxine (750−422 = 328 ≥ 240). The signature move: long-press-dragging (450ms, ghost chip, brand drop ring — or the mandatory 44×44 ellipsis → Move-to-slot actionSheet with live '± conflict' deltas) Ibuprofen out of Noon dissolves the tether via a 240ms dash-out, decrements the Interactions tab badge 2→1 (unmounts at 0, never '0'), cools the IB×LS matrix cells amber→green symmetrically, recomputes the iron chip, and fills the navBar AdherenceRing (r=12, C=75.40, glyph-only with aria-label) — every mutation toasts through the ONE sticky-in-flow toastDock with a real Undo that pops an exact snapshot (chain replays backward one toast at a time). Two-detent pair sheets (55% / calc(100%−56px)) carry severity banner, 64px DovetailMark warning glyph, plain-language rule, mini tether rail, and a 48px 'Move Ibuprofen to Evening' CTA. Per-tab scrollTop persists; re-tapping the active tab scrolls to top; desktop container widths (≥720px) center a 430px phone column. Choose over mobile-prescription-pickup when the surface is the daily SCHEDULE with interaction physics (tethers, spacing math, move/skip/undo verbs), not a pharmacy pickup errand; choose over mobile-parking-session when the object is a multi-tab health routine whose one store re-derives five surfaces per mutation, not a single live metered session; choose over mobile-plant-care-roster when the care-loop needs conflict GEOMETRY between items (same-slot tethers, an 8×8 pair matrix) rather than independent per-item schedules; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky navBar/tabBar, bottom sheets, actionSheets, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
