// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Foyer — Arrival & Room Key',
  description:
    "MOBILE (390px shell) day-of hotel arrival surface for Foyer at The Ardmore Hotel (Maya Okafor, Thu Jul 2 – Sun Jul 5 · 3 nights): a transparent navBar (arch-keyhole Foyer mark whose keyhole circle IS the unlock ring at 24px, RefreshCw) sits over a 208px stylized-SVG facade hero and flips to blur+hairline via an IntersectionObserver sentinel, its center stack fading in with a stage-driven subtitle ('Arriving today' → 'Room 1408' → 'Key active'); below, one dense scroll body runs a 4×64px arrival-readiness rail (28px discs, 2px connectors, live '2 OF 4 READY' → 3 → 4 counter that always equals count(done)), a 60px-row stay timeline (4 visible + 'Show 6 more' = 10, user actions prepend 'Just now' events to 11/12 and the terminal 'All N events' caption recomputes), a room card that grows from two 72px offers into assigned anatomy with a checkable folio ($240 × 3 = $720; taxes $108; resort fee $35 × 3 = $105; 828 + 105 = TOTAL $933 on Visa ··4417), undo-over-confirm request chips (badge 0→1→2→3, persistent Undo toast, no timers), and — at stage 4 only — the inline 160px KeyCoin. Two two-detent sheets (55% / calc(100% − 56px), single overlay enum so stacking is impossible): a room-select sheet whose fluid SVG floor-strip (viewBox 0 0 358 96 — 12 rooms in two facing rows, elevator core, ICE nook) is a real radiogroup with 44×44 offer hits plus matching 72px offer-row radios, and a key sheet holding the signature hold-to-unlock coin — pointerdown arms a 1200ms ring fill (C = 2·π·68 = 427.26) with haptic-style tick dots at 400/800/1200ms, early release rewinds with zero store writes, completion (or the mandatory 'Unlock door' button / Enter/Space) prepends 'Entered room 1408', flips readiness to 4 OF 4 exactly once, and starts the 8s auto-relock sweep with an aria-hidden numeral and 'Relock now' escape hatch. Check-in stages physically gate the page: the key section renders as an inert 64px 'Unlocks after room is assigned' placeholder, then a key-issued teaser, then the coin. One stayStore owns stage/doorState/overlay/timeline/requests/toast; the toast dock is sticky-in-flow above the sticky footer at rest and shell-absolute only while scroll-locked. At desktop container widths (≥720px) it renders as a centered 430px phone column with hairline borders. Choose over mobile-parking-session when the flow is a staged arrival that progressively unlocks page sections and a physical-access verb (hold-to-unlock with auto-relock), not a live metered countdown with tiered pricing; choose over mobile-banking-home-insights when the surface is a hospitality check-in with a floor-map picker rather than a filtering money dashboard; choose over bottom-sheet gallery templates when sheets must drive cross-surface consequences (readiness counter, navBar subtitle, timeline ledger) instead of demonstrating sheet mechanics; choose over any desktop template when the brief needs a phone-first 390px shell with sticky navBar/footer, gating stages, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
