// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Splitshift — Tip Pool Split',
  description:
    "MOBILE (390px shell) role-weighted tip-pool splitter for restaurant closers, Splitshift tonight pool #12 ($567.03 = POOL_CENTS 56703): a 52px navBar (coin-bisected-by-shift-slash brand mark, 'Tonight's Pool' h1, 44×44 RefreshCw whose press shows six 64px skeleton WeightRows with deterministic 60/45/70% bars plus an 'Updated just now' status toast) over a 36px balanceStrip ($567.03 pool · #12 + a 24px Balanced ✓ / 'Over by $32.97' pill), then a STICKY PoolFlow mini-sankey (top 52 z15, 148px = 12 pad + 116px SVG viewBox 358×116 preserveAspectRatio none + 20px '6 teammates · 34.0 hrs · 31.5 weight-hrs' caption; ribbon stroke = max(2, round(share·48)) → 10/9/12/5/4/7px, 240ms stroke-width tween, locked ribbons at full opacity), a 56px PennyStrip ('3¢ remainder' + one 44px-hit cent-chip per absorbed cent, '1¢ → MO', tap advances that cent to the next unlocked teammate), and six 64px WeightRows in a listCard (name button → teammate actionSheet, roleChip, hours, 17/700 rAF count-up payout with LockIcon when pinned; minus · detent-ticked slider (0.50–1.50, snap ±0.02 to role defaults 0.60/0.70/0.85/1.00/1.25) · plus · 44×44 aria-pressed lock toggle). ONE pool store + pure derive(): floors floor(56703·wh/31.5) = 11700+10800+14625+6300+4860+8415 = 56700¢, remainder 3¢ rotates from ROUND_INDEX 12 % 6 = 0 to Maya/Diego/Priya, finals sum to $567.03 to the cent; dragging any slider live-redistributes every unlocked payout, re-thickens the ribbons, re-derives the absorber set, and flips the pill — locks over-committing the pool ($200+$250+$150 = $600 → 'Over by $32.97') clamp unlocked payouts to $0.00 and swap the PennyStrip for an 'Unlock a payout to rebalance' error row. The medium/large-detent pennySheet shows floored-base/+1¢-badge/final rows with the exact math footer ('Floored $567.00 + remainder $0.03 = $567.03'), Rotate-all, and demo fixture buttons (clean 56700¢ pool, over-commit seed); History ($432.18+$511.40+$598.75 = '$1,542.33 · 3 pools', 'Show 8 more' → 'All 11 closed pools'), Roles (five 60px rows whose 96×32 steppers move every slider's detent ticks), and Team (72px avatar rows) persist per-tab scroll; every remove/unlock/reassign is exact-restore Undo through the single sticky toastDock. Choose over mobile-group-gift-pool when the money flows OUT to weighted earners with locks and penny reconciliation, not IN from contributors toward a target; choose over mobile-p2p-payment-flow when the object is a multi-party derived ledger with a sankey, not a single send; choose over mobile-roundup-goals when one continuous weight write must redistribute a fixed pot to the cent rather than routing coins between goal jars; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky chrome, bottom sheets, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
