// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Emberline — Thermostat Schedule',
  description:
    "MOBILE (390px shell) weekly thermostat editor for Emberline, frozen at Tuesday 3:12 PM: a four-tab push-stack shell (Home / Schedule / Energy / Settings, 52px navBar with IntersectionObserver title fade + 64px tabBar) whose Home tab is a hero dial card — 200×200 SVG 270° arc in the temperature-interpolated ember↔teal mix, 44px '66°' numeral, 'Holding · Away until 5:30 PM', a 28px 'Next change 5:30 PM → 71°' chip, the DualSetpointStepper hold row (two linked 96×32 spinbutton tracks enforcing the 2° deadband: heat to 74 pushes cool to 76 with a one-render 600-weight flash and a toast), and an 'Est. runtime 5h 30m' badge derived from the duty table (72+60+54+108+36 = 330 min) — over an Auto/Heat/Cool/Off segmented radiogroup (Off collapses the card to a one-action PowerIcon empty state). The Schedule tab is the signature surface: a 7-chip WeekHeatStrip radiogroup (3-band night/day/evening mini heatmaps per day) above a 768px SetpointTimeline (32px/hour, 30-min = 16px snap, 44px hour gutter) of five draggable temperature-tinted blocks summing to exactly 1440 min (Night 360 · Morning 150 · Away 540 · Evening 270 · Wind-down 120; weekends re-shape to 360+240+360+360+120 = 1440). Dragging the Away block's 44px resizeHandle (role='slider', ArrowUp/Down = 30-min) writes through the ONE WeekScheduleStore mid-drag so four surfaces move in the same frame: the Away/Evening minute swap, the ComfortCurvePreview's stepped 45-min ramps ('+8° by 6:45 AM'), the hero 'Next change' chip, and the runtime badge (5h 30m → 5h 21m at +30); pointerup commits with an Undo toast (no timers, exact-array restore), and the editor sheet (55%/large detents, preventScroll focus trap) offers the same boundaries as spinbutton steppers plus block delete that merges minutes into a neighbor (Night absorbs Morning → 510m, day still 1440). Energy is a 7-bar week chart reconciling to 'This week 67.0 kWh · −8% vs last week (72.8)' with 60px breakdown rows (41.8+12.6+8.2+4.4 = 67.0) and a RefreshCw-driven deterministic skeleton; Settings pushes a Sensors screen (avg 64.25 → 'Avg 64.3°') and ≥3:1 opaque-track switch rows. Desktop (≥720px container) renders a centered 430px phone column. Choose over mobile-parking-session when the object is a WEEKLY multi-block schedule with drag-resize block editing and cross-tab derivations, not a single live metered session with one extend verb; choose over mobile-cycle-phase-wheel when the hero is a schedule track users restructure (resize/delete/duplicate blocks), not a read-mostly phase wheel with daily logging; choose over mobile-banking-home-insights when mutations move minutes between timeline neighbors under a 1440-min invariant rather than filtering a transaction ledger; choose over grid-feeder-console or any desktop template when the brief needs a phone-first 390px shell with bottom sheets, long-press menus, 44×44 targets, and a sticky toast dock.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
