// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Dogear — Book Club Reading Progress',
  description:
    "MOBILE (390px shell) spoiler-gated book-club surface for Dogear, frozen 7 days before the Jul 11 meeting: a 52px navBar (folded-corner Dogear mark, 'The Glass Meridian' h1, pace-tinted 'Jul 11 · 7 days' countdown chip that opens the Club tab) over an 84px sticky ChapterSpineTrack — 20 chapter segments sized pages/340 as percentages (lengths cycle 14/18/16/20 ×5 = 340), four member avatar dots above (Jonah 24.12% · Ravi 44.12% · Maya 64.12% · Priya 84.12%), YOUR draggable 28px bookmark teardrop below at 54.12% (role='slider', Arrow ±1 page, PageUp/Down ±1 chapter, drag snaps to the nearest chapter end), and a hatched SPOILER FOG from p.184 to 100% with a 20px feathered edge. Four tabs: Reading (112px PaceCoachCard — 156 pages left → 'Read 23 pages/day', projected Jul 10, 1 day early — 12→20 60px chapter rows with per-row 'Mark read to here' buttons and a 'Show 8 more' loadMoreRow, plus a 96×32 page stepper), Discuss (8 full-bleed 72px SpoilerGateThread rows summing to 30 replies — locked rows blur title/preview behind an unblurred '4 replies · unlocks at Ch. 12' caption whose press opens an anchored 'Mark read to Ch. 12' explainer, the non-gesture unlock path; RefreshCw drives a 4-row deterministic skeleton), Club (meeting card + 5 member rows with relative tags — Priya's stress-length name ellipsizes — and a live 'Club average · p. 184 of 340 (54%)' caption), Shelf (28px large title with IntersectionObserver navBar fade + 3 book rows with id-derived gradient covers). The signature move is one reading position unlocking everything: any commit (drag, slider keys, row button, stepper boundary-cross, explainer) moves the fog, refills read segments (≥3:1 rest-fill pair), unblurs gated threads with a 400ms reply count-up, re-sums the Discuss badge (11→14 crosses ch12 +4 → 7 then ch14 +3 → 10; p340 = 17), re-derives the pace coach (p116 flips chip + card to error, '2 days late'; p340 is the 'Finished · 7 days early' terminal), and flips member tags — all under ONE undo-over-confirm toast whose full snapshot restores fog, gates, badge 17→3, pace, and tags exactly. Chapter rows open a two-detent chapter-notes sheet (Ch. 2 is the true-empty stress with one 'Add note' action). At desktop container widths (≥720px) it renders as a centered 430px phone column. Choose over mobile-plant-care-roster when the domain is reading progress with content GATING (spoiler fog, thread locks) rather than recurring-care scheduling; choose over mobile-someday-maybe-sorter when the one state value is a continuous position on a spine that many surfaces derive from, not a triage verdict; choose over mobile-hotel-key-checkin when progress is user-dragged rather than stage-gated by a service; choose over any desktop template when the brief needs a phone-first 390px shell with sticky spine chrome, bottom tabs, sheets, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
