// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Switchback — Trail Conditions Scout',
  description:
    "MOBILE (390px shell) trail go/no-go instrument for Switchback, loading on the pushed Cascade Pass detail (back pops to a Trails root with search + three saved-trail 72px rows): a 52px navBar (44×44 back + 'Trails', center title fading in via an IntersectionObserver sentinel, 44×44 RefreshCw) over a 52px 'Cascade Pass' 28/700 large title and a live verdict row — a 32px pill button reading 'CAUTION · icy above 3.4 mi' (amber pair, white ≈4.6:1) or 'GO · clear to turnaround' (brand fir green #3F7A4E ≈5.0:1) beside an 'Est 5h 48m' 16/600 tabular chip. Below sits the ElevationConditionRibbon (SVG viewBox 0 0 358 140): a 7-point elevation polyline (2,400→5,600 ft, y-scale 116px/3,200ft = 0.03625 px/ft) over six under-curve condition bands (clear/mud/snow/ice pairs each ≥3:1 vs the card), ten 10px report pins with 44×44 hit rects, a pointer scrub lens ('mi 2.6 · 14.2% · SNOW', slider-role keyboard path at 0.2mi), and a draggable TurnaroundFlag whose track IS the curve (snap 0.2, clamp 1.0–4.8; 44px −/+0.2 stepper + spinbutton and the sheet CTA as button paths). The signature chain: ONE {turnaroundMile} write re-dims bands past the flag to 30%, recomputes minutes = 20×(2×mi) + 3×(gain/100) + condition penalties (4.8→348='5h 48m', 3.4→226='3h 46m', 1.0→52='52m'), flips CAUTION↔GO exactly at 3.4, re-derives the Pack tab (5 base + Microspikes/Gaiters/Trekking-poles; badge 8→7→5, emptyState 'Nothing extra needed' at 1.0), and rewrites the Trails-root card meta 'Est 5h 48m · 9.6 mi RT' — five pure reads per render. Reports render as a ReportFreshnessStack of 72px rows sorted by conf = max(20, 100−3×ageHours) (94/85/67/43/22/20…), each led by a 40px decay-ring avatar (3px arc sweep = conf% of 360°, opacity floored at 0.35) with PAST-FLAG rows at 55%; 'Show 4 more' appends the conf-20 batch then 'All 10 reports'; the Reports tab adds an All/Mud/Snow/Ice segmented radiogroup. Pack rows are whole-row switches that remove immediately with exact-index Undo through the ONE sticky-in-flow toast dock (bottom:76 above the 64px tabBar; absolute only during sheet scroll-lock). A two-detent segment sheet (55% / calc(100%−56px), clickable grabber, preventScroll focus-in) shows grade/gain/in-segment reports and 'Set turnaround here'. Desktop (≥720px container) renders a centered 430px phone column. Choose over mobile-route-manifest when the object is a GO/NO-GO planning readout driven by one continuous turnaround value on an elevation profile, not a stop-by-stop delivery ledger with swipe verbs; choose over mobile-run-route-recap when the surface plans a future hike with live derived consequences rather than replaying a finished workout; choose over mobile-transit-companion when the domain is backcountry conditions with confidence-decayed crowd reports, not scheduled departures; choose over mobile-parking-session when the signature write is a draggable spatial flag recomputing five surfaces, not a sheet-staged payment extension.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
