// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: "Forkful — Today's Meal Quick-Add Log",
  description:
    "MOBILE (390px shell) meal-logging surface for Forkful, built around repetition speed: a 52px navBar (28px ForkMark tine-bar glyph, IO-sentinel-wired compact 'Today' title + hairline that appear only after the 28px/700 large title scrolls under, 44×44 RefreshCw → fixed 'Updated just now' status toast) over a concentric three-arc macro dial (viewBox 224, three 270° arcs opening at the bottom: protein r=100 arclen 471.2 in brand ember, carbs r=84/395.8, fat r=68/320.4 as color-mix strokes; shared 32px tabular center numeral '1,106 of 2,110 kcal'; overshoot clamps the fill at 100% and renders a 3×16 error end tick), a three-chip 44px legend ('Protein 77/140g'), a meal rail of four calorie-sized dot anchors (diameter 12 + round(16·min(kcal/700,1)) → seeded 21/24/16px + Dinner's 12px empty ring at a ≥3:1 boundary pair), then four meal sections — 13px/600 sectionHeaders with LIVE kcal ('LUNCH · 536 KCAL'), 2-column 116px quick-add tile grids (16 stroke-glyph foods, whole-tile add buttons, ×N brand count badges with 4.6:1 near-black badge text, 44×44 ellipsis + 450ms long-press both opening the portion sheet), and 60px swipe-to-delete logged rows (−72px error block + mandatory ellipsis menu, delete executes immediately with Undo restoring the exact list index). A sticky-in-flow toast dock (bottom 76, one polite region, no timers) rides above a sticky 64px summary footer — '1,004 kcal left' + '77P · 105C · 42F logged' caption + a 'Dinner ↓' first-empty-meal jump — replacing the tab bar. Every kcal is arithmetically derived (4P+4C+9F; TARGETS 2110 = 4·140+4·230+9·70) and every surface is a pure derivation of the ONE loggedItems owner: a single tile tap moves badge, dial arcs, rail dot, section kcal, row list, footer remaining, and toast in the same frame. The MEDIUM-detent (55%) PortionSheet holds a 96×32 0.5-step serving spinbutton (0.5–3.0, exhausted half at 35%), a live macro readout ('2.5 g' halves at Almond ×0.5 = 85 kcal), a 4-segment meal radiogroup, and an 'Add 2 servings · 342 kcal'-style confirm; demo paths: Protein Shake ×3 → protein 167/140g clamped arc + '27g over' error chip + '491 kcal left'; Salmon and Rice ×3 → footer flips to '247 kcal over'. At desktop container widths (≥720px) it renders as a centered 430px phone column with hairline borders. Choose over mobile-parking-session when the surface is a high-frequency LOGGING loop (many taps per session accumulating into dial/rail/footer aggregates), not a single live session with one extend/end decision; choose over mobile-cycle-phase-wheel when the hero must be a multi-ring quantitative macro gauge fed by list mutations rather than a single cyclical phase indicator; choose over mobile-camera-roll-organizer when items are CREATED by tapping a catalog rather than triaged from an existing grid; choose over mobile-list-input-gallery when you need a working product surface with one wired state owner, not annotated specimen contracts.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
