// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Duesday — Invoice Chaser',
  description:
    "MOBILE (390px shell) aging-sorted invoice-triage surface for Duesday, a small-business owner's chase list: a 52px navBar (torn-invoice/coin brand mark · 'Duesday' · 44×44 RefreshCw) over a 72px TOTAL OUTSTANDING header whose $17,000.00 derives live by .reduce (overdue $7,685.00 + due soon $6,850.00 + promised $2,465.00, 4+3+2 = 9 invoices), a 36px Overdue/Due soon/Promised radiogroup with derived counts, and 88px invoice rows in an inset-grouped listCard: 40px agingBadge (id-derived gradient monogram under a 113.1-circumference aging arc — sweep min(daysPast/45,1), escalating amber/orange/red pairs with commented ≥3:1 math; due-soon rows sweep a ≥3:1 neutral), two-line name/meta stack (inv-04's 40-char 'Orchard Lane Events & Catering Collective' is the 320px ellipsis stress), trailing tabular amount over a 44×16 three-notch ladderStepper, and a 44×44 ellipsis. Promised rows grow to 116px with a 28px scroll-snap promise-chip rail (inv-08 holds 3 chips forcing peek-scroll; $1,679.75/$785.25 cents prove tabular alignment). The signature move is the three-rung nudge ladder: ellipsis (or row tap) → action sheet ('Send nudge (firm → final)' / 'Log promise to pay' / 'Mark paid' + separate Cancel card) → two-detent (55% / calc(100% − 56px)) chase-composer sheet prefilled from the rung-keyed deterministic template with a live rung-preview strip; Send advances the ladder, stamps 'nudged today', FLIP-re-sorts the cooled row downward (nudgedToday asc → daysPastTerms desc → id asc; instant under reduced motion), appends a 'Today' activity entry that badges the Activity tab, and offers snapshot-exact Undo from the single sticky-in-flow toast dock (bottom 76, no auto-dismiss). Swipe left −72px reveals a brand Promise block (same Log-promise mutation as the mandatory ellipsis path); Mark paid drops the derived header live ($17,000.00 → $12,750.00 for inv-01; paying both promised rows leaves $14,535.00 and a true-empty 'No promises yet' state whose one action opens the first overdue row's action sheet). Activity is the sanctioned full-bleed 60px log; Settings ships two listCards of whole-row 51×31 switches with ≥3:1 rest boundaries; tabs persist scrollTop with active-tab re-tap scrolling to top. At desktop container widths (≥720px) it renders as a centered 430px phone column, never a stretched relayout. Choose over mobile-receipt-inbox when the object is money OWED TO the user with an escalating outreach ladder (rung state, composer templates, promise chips), not documents to file; choose over mobile-subscription-audit when rows demand a per-row chase verb with cross-surface consequences rather than keep/cancel judgment; choose over mobile-p2p-payment-flow when the flow is accounts-receivable triage across nine debtors, not a single send-money transaction; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky navBar/tabBar, bottom sheets, swipe-reveal rows, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
