// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Activity Rings Close',
  description:
    "MOBILE (390px shell) motion-first fitness day-summary for Cadence, frozen at Sat, Jul 11 (week Sun Jul 5 – Sat Jul 11, 2026): a 52px navBar (activity mark · 'Rings' · 44px Replay) over a large-title row, then the centerpiece — three concentric SVG rings (Move r118 in THE quarantined coral literal / Exercise r94 in the success token / Stand r70 in the accent token; 20px round-cap strokes over color-mixed rest tracks) that sweep closed via stroke-dashoffset transitions (900ms decelerate bezier, sequential 220ms delays 0/220/440). Every percent DERIVES from raw value/goal fixtures (486/620 CAL → 78%, 42/30 MIN → capped 100%, 7/12 HRS → 58%); the Exercise ring closing at 100% fires a staged settle beat (1.5s timer, cleaned up) that mounts a one-shot overshoot glow pulse + a 12-o'clock ring-cap dot spark, springs a 'Goal hit · Exercise' chip into a reserved 36px row (cubic-bezier(0.34,1.56,0.64,1), zero layout shift), and posts the announcement through the single polite toast dock (sticky bottom:16, 44×44 dismiss, new toast replaces old). The center hub counts Move calories 0→486 over 800ms via a fixed-step setInterval (tabular-nums). A week strip of 7 flex:1 mini-ring day buttons (S–S letters, today marked in text-accent, Wed is the rest day rendered as dashed empty rings + explicit 'Rest day' text, never color alone) RE-RUNS the choreography on tap — all three rings retarget with the same staged transitions and the count-up restarts; Replay resets the rings fully open first. Below: a rings detail listCard (value/goal rows with % subs), a Week-recap card whose aggregates derive in code (exercise-goal days 4 of 7, perfect days 1, rest days 1), and three Milestones metric cards (Steps 9,214 · Distance 4.8 mi · Flights 12) whose numbers tick up only on first scroll-into-view (IntersectionObserver, once; Replay re-ticks). Reduced motion (matchMedia + change listener): rings render at final values with transition:none, all count-ups render final, glow/spark are removed, the Goal-hit chip appears statically. At container widths >560px (useElementWidth ResizeObserver, never viewport) it renders the standard centered 430px phone column on a muted backdrop. Choose over mobile-meditation-breath-player when the surface is a data-recap of ring GOALS closing with celebratory choreography rather than a live guided breathing loop; choose over mobile-run-route-recap when the story is three concentric goal gauges + a tappable week strip, not a single workout's route map and splits; choose over mobile-p2p-payment-flow when the count-up celebrates fitness metrics instead of committing a money transfer; choose over any desktop template when the brief calls for a phone-first 390px shell with 44×44 touch targets and transform/stroke-dashoffset-only motion.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
