// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Spool — Long-read Queue',
  description:
    "MOBILE (390px shell) read-it-later queue for Spool that treats the backlog as thread on a spool: a 52px navBar (24px SpoolMark — 270° wound-thread arc over a rest-track ring — plus RefreshCw and Moon) whose center title is the LIVE total '3h 12m across 9 pieces' derived from nine articles at the fixture law remainingMin = (totalParas − readParas)/2 (200 wpm · 100 words/para: 14+6+9+18+22+28+31+26+38 = 192), over a 28/700 'Your queue' large-title row and ProgressSpineCards (88px; 116px 22/700 NOW READING variant) with a 6px book-style spine filling bottom-up (readParas/totalParas), '14 min left · The Meridian' meta, and ceil(remainingMin/12) session pips ('2 sessions'), grouped into ALMOST DONE ≤10 / TONIGHT 11–25 / LONGER SITS >25 sections (2/3/4 at rest) that re-sort live; swipe-to-reveal Archive at −72px with the mandatory 44×44 ellipsis menu (Move to top / Read next / Archive). The signature move is the 88px ResumeScrubberBar (sticky bottom:64 above the 64px tabBar): dragging the 28px thumb streams a1's actual paragraph first-clauses ('¶17 — The shop on Delancey kept a drawer of orphaned screws') from a 44-entry EXCERPTS fixture into a 13px italic ticker, and releasing commits ONE readParas write (16→32 of 44) that recomputes the navBar total 192→184 = '3h 04m', drops a1's pips 2→1, and re-sorts it from TONIGHT into ALMOST DONE (3/2/4) — prev/next 44×44 buttons and ArrowLeft/Right step the same role='slider' store path. A two-detent (55% / calc(100%−56px)) TonightPlannerSheet greedy-packs whole pieces ascending plus ONE hatched partial into a 15/25/40-min window (15 = 6+9 exact; 25 = 6+9+partial 10 of 14 → 24%/36%/40% PackedWindowBar blocks; 40 = 6+9+14+partial 11 of 18) and 'Start session' promotes the first block to NOW READING with a 'Planned 25 min · 3 pieces' toast; archive is execute-then-Undo ('3h 03m across 8 pieces' after a3, exact restore) through a sticky-in-flow toast dock at bottom:156 that flips shell-absolute only during sheet scroll-lock. Stats tab derives '1h 26m' from week bars [12,18,9,22,14,11,0]; Settings rows are whole-row 51×31 switches; spine/scrubber rest tracks carry amendment-checked ≥3:1 light-dark pairs. At desktop container widths (≥720px) it renders as a centered 430px phone column. Choose over mobile-podcast-queue when the queue is READING progress measured in paragraphs with a scrub-to-reposition excerpt ticker and a bin-packing session planner, not audio episodes with a player bar and downloads ledger; choose over mobile-book-club-progress when the object is a personal multi-article backlog with derived time-buckets, not one shared book's social pace; choose over mobile-tonight-picker when 'tonight' means deterministically packing minutes of reading into a chosen window, not swiping to pick one title; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky navBar/tabBar chrome, bottom sheets, swipe-reveal rows, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
