// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Keyline — Saturday Open-House Router',
  description:
    "MOBILE (390px shell) Saturday open-house day router for Keyline, planned in integer minutes (DEPART_HOME 600 = 10:00 AM, 20-min dwell): a 52px navBar (28px key-into-pin mark · 'Sat, Jul 11' that swaps to the collapsed EtaStrip 'Done 1:34 PM · 5/6 fit' once the 28px 'Saturday plan' large title scrolls under, wired via IntersectionObserver · 44×44 Refresh driving a user-resolved skeleton), a 3-tab 64px tabBar whose Day badge re-derives '5/6', and a Day flow of daySummaryCard ('Leave 10:00 AM — Done 1:34 PM' over the exact cross-check '106 min driving · 108 min viewing · 0 min waiting' = 214 min, plus Reorder stops / Add delay +15m buttons) above a route rail: six stops on a '64px 1fr' grid — 48px hue-stepped gradient house glyphs (152+18°/stop), ≥108px stopCards with a 120×20 FeasibilityChip whose 2×14 arrival tick sits at (arrive−open)/(close−open)×120 (s5 baseline 104px, reds clamp to 118), and drive connectors 4px wide × driveMin×2 tall (24–72px) recolored by the DOWNSTREAM stop's status. The signature move is plan-recompute-everywhere: ONE pure computePlan(order, skipped, added, delayMin) feeds every surface, so long-press-dragging '77 Cormorant Dr' to slot 5 slides ticks live mid-drag and lands the max-red case (+42 min after close, done 1:45 PM, '3/6 fit'), the sticky rippleBanner (top 52, in-flow — never shell-absolute) names exactly that stop with a one-tap 'Skip it' that executes + Undo (restoring exact order/skipped/delay through the sticky toastDock), the two-detent ReorderSheet (grip drag AND always-visible 44px chevrons, live mini chips) commits 'Route updated — 3/6 fit', the StopActionSheet offers iconed Move earlier/later/Skip today, 'Add delay +15m' shifts departure proving buttons-only recompute, Homes re-sorts green-by-slack → amber → red/skipped into a detail push ('‹ Homes'), and Saved's 'Plan visit' appends s7 green at 1:50 PM or s9 as the +115-min extreme red while s8 stays honestly disabled ('No Sat window'); skipping all six reveals the true-empty 'No stops planned' with Restore all. At desktop container widths (≥720px) it renders as a centered 430px phone column, never a stretched relayout. Choose over mobile-transit-companion when the object is a self-authored multi-stop DAY PLAN with hard viewing windows and feasibility math the user reorders, not live transit legs to ride; choose over mobile-route-manifest when the router is consumer-side what-fits-when triage (windows, skips, appends) rather than a worker's fixed delivery manifest; choose over mobile-date-night-builder when stops are independent timed windows on a drive matrix instead of a single evening's duration-proportional rail; choose over mobile-subscription-audit when the verdict surface is arrival-time feasibility across a route, not per-item keep/cancel triage.",
  category: 'Real Estate & Moving',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
