// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Murmur — Voice Note Thread',
  description:
    "MOBILE (390px shell) voice-message conversation for Murmur (#5B4BC4 quarantined accent): a 52px navBar (44×44 back 'Chats', center 'Priya' fading in via an IntersectionObserver sentinel, 44×44 Info naming the full 'Priya Nandakumar') over a 52px large-title row (28/700 'Priya' + live meta '6 voice notes · 9:47 total · 2 new', where 587s = 84+125+47+118+36+177 and '2 new' re-derives from the heard map), then a full-bleed stream: TUESDAY divider and six fixed-266px WaveScrubBubbles (12 pad + 36 play + 8 gap + 198 wave + 12 pad; 40 id-hashed bars 6–28px at 3px/2px pitch = 198), two-tone heard/unheard tint (m2 shows floor(42/125×40) = 13 heard bars; outgoing white 92%/56% on the accent with 7.0:1/3.1:1 math, incoming unheard #8A8797 ≥3:1 vs card, fully-unheard incoming notes render bright + dot + '2 new' text). Every waveform is a role=slider (ArrowLeft/Right ±5s, Home/End) whose pointer drag rides an 11/500 timestamp chip and whose pointerup arms a reply anchor — the composer grows a 44px ReplyAnchorChip ('Reply at 0:42' + 12-bar mini-wave sliced bars 7..18 of m2's hash + '…the venue holds forty…'), the mic relabels to 'Record reply at 0:42', and the sticky-in-flow toast offers Clear undo. The active bubble expands a 52px footer (44×44 −5s/+5s/Aa — the visible button path that matters on m6, where 177s/198px ≈ 0.89 s/px) plus a 2-line karaoke preview. Sticky footer stack: 56px miniPlayer (36px play/pause, 'Priya · 0:42 / 2:05' tabular readout, 1.5x speed pill, 58px micro-waveform, Aa, X-collapse that shrinks the stack 120→64 with no jump) + 64px composer (48px pill input, 48px mic) = 120px, 164px with the reply chip. The 'Aa' path opens a two-detent transcript sheet (55% / calc(100% − 56px), clickable grabber, 1x/1.5x/2x radiogroup) whose 41-word TranscriptKaraoke buttons ('holds, 0:42'; the t=41/t=42 tiebreak; 14-char 'unconventional' wrap stress) seek the ONE playback value — waveform playhead, mini-player readout, heard tint, and active word all move in the same render (single-playhead law: playing any other note swaps expandedId, rebinds the mini-player, and receipts keep deriving 'Played' 47≥47 / 'Delivered' from PEER_HEARD_SEC). At desktop container widths (≥720px) it renders as a centered 430px phone column with hairline borders, never a stretched relayout. Choose over mobile-podcast-queue when the surface is a two-person voice CONVERSATION with scrubbable bubbles, reply anchors, and read receipts, not an episode queue with a time ledger; choose over mobile-parking-session when the bottom sheet carries karaoke content synced to a playhead rather than a pricing form; choose over desktop messaging/feed templates when the brief demands the 390px shell, sticky navBar/footer stack, 44×44 touch targets, and gesture-with-button-path scrubbing.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
