// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Biometric Checkout',
  description:
    "MOBILE (390px shell) Apple-Pay-STYLE payment-sheet experience for the product-neutral 'FacePay' wallet at Alpenglow Supply, anchored on Fri, Jul 4: a store screen (52px sticky navBar, inset-grouped order-summary card whose $65.50 / $6.00 / $5.90 / $77.40 figures are reduce()-derived from 3 cart-item cents fields, a delivery card, and a 'Fail first scan' demo chip) under a 48px token-pure inverted 'Buy with FacePay · $77.40' button that raises the payment sheet (translateY slide + scrim fade, absolute inside shell, scroll-locked, Escape/scrim/X close with focus restore). The sheet is the centerpiece choreography: a 2-card wallet stack that shuffles on tap (outgoing card runs a tilt keyframe on an inner wrapper while both slots spring to new transforms — the Account row re-derives from the front card), merchant/account/total rows, and a 72px face-glyph SVG whose confirm sequence chains on animationend — a glowing scan bar sweeps twice (translateY ×2 alternate), the four stroke groups tint to the brand accent with 110ms stagger, the glyph crossfades into a var(--color-success) ring + check that DRAW ON via stroke-dashoffset (dasharray 164/35) with a haptic-style double-pulse, the header stamps a rotate-in DONE, and 600ms later the sheet drops away to a confirmation banner, a confirmed row folding into the order card, a Paid pill, and a 'Payment complete · $77.40' toast in the single sticky bottom:16 dock. 'Use passcode instead' (44px) swaps the panel for a 4-dot pad (fills pop, wrong entries shake the dot row and clear on animationend, fixed code 1-1-2-2 commits through the SAME succeed() path); the demo chip makes attempt one shake into 'Try again' with attempt two succeeding. All motion is transform/opacity + stroke-dashoffset with spring cubic-bezier(0.34,1.56,0.64,1) / decelerate cubic-bezier(0.22,1,0.36,1); prefers-reduced-motion removes the sweep/shake/pulse/pop entirely and renders the ring+check complete via base stroke-dashoffset:0, with staged timers replacing animationend chaining. One quarantined brand literal light-dark(#3B5BDB, #91A7FF) with contrast math; >560px container widths render a centered 430px phone column on the muted backdrop via a useElementWidth ResizeObserver. Choose over mobile-slide-to-confirm when the payment commit is a biometric scan-and-morph inside a raised wallet sheet rather than a slide-to-pay track or hold-to-confirm ring; choose over mobile-p2p-payment-flow when the surface is a merchant checkout with a card stack and authentication choreography, not keypad amount entry with split math; choose over mobile-success-celebration when the star is the pre-payment scan/passcode ritual rather than the post-commit confetti receipt.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
