// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Afterglow — Date Debrief Log',
  description:
    "MOBILE (390px shell) post-date journal for Afterglow (crescent-dissolving-to-three-dots mark, #DB2777): a 4-tab surface (Log · People · Patterns · Me) where ONE dense debrief form feeds a live scatter of past dates. The Log tab stacks paired Spark/Ease slider blocks (76px each: 16px/500 label + 22px/700 tabular value over a 4px track with 28px thumb and a 96×32 stepper whose halves pad to 44×44 hits), a 260px SparkEaseScatter card — 12 committed 12px dots on per-person radial gradients (x = ease, y = spark, quadrant hairlines at 5.5; the e04/e10 collision at spark 9 · ease 8 proves the deterministic +8px-per-collision offset) plus an 18px dashed-BRAND-ring draft dot whose gradient lerps cool→warm by (spark+ease−2)/18 and glides 200ms as sliders move; the WHOLE card is one button opening a two-detent (55% / calc(100%−56px)) pattern-map sheet with person/verdict filter chips, an honest 'Showing N of 12' count, and a SearchXIcon filtered-empty (Jordan · Excited → 0) — a weighted FlagTray (12 chips, taps cycle 0→1→2→0, weight encoded by 1px vs 3px border + 700 label, running '+1 green · −0 red' tally), a 240×130 semicircle VerdictDial (5 radio stops at −90/−45/0/+45/+90°, dashed ghost tick tracking the suggestion formula score = spark + ease + 2·(Σgreen − Σred), bands ≤8/9–13/14–16/17–19/≥20; ghost-vs-choice divergence reads 'Suggested: Again · You chose: Never'), a note field, and a swipeable RECENT DEBRIEFS list (60px rows, −72px Delete reveal + mandatory 44×44 ellipsis fallback, delete-then-Undo restoring the exact array index, 'Show 9 more' → 'All 12 debriefs'). Committing validates the dial (error ring + scroll + focus on miss), appends e13, and every surface recomputes: the 13th dot settles with a 320ms pulse, People's Alex DateCountRing grows 1→2 segments with the chosen-verdict tint, Patterns' '9 of 12 dates rated ease ≥7' flips to '10 of 13' (while 'Ease ≥7 first dates led to a second 4 of 5 times' deliberately holds still — Alex's first-date ease was 6), and the VerdictDistBar (1/1/2/5/3 of 12) grows a bar. Per-tab scroll and the draft survive tab switches; overlays close; active-tab re-tap scrolls to top. Choose over mobile-mutual-window-finder when the dating surface is reflective scoring of past dates (sliders → scatter → verdict) rather than forward scheduling of shared free windows; choose over mobile-date-night-builder when the object is a JOURNAL of many past evenings with derived patterns, not a run-sheet composing one upcoming evening; choose over mobile-symptom-day-journal when the log's payload is paired 1–10 axes + weighted qualitative flags feeding a scatter/verdict engine rather than clinical symptom tracking; choose over mobile-parking-session when the dial is a discrete 5-stop verdict radiogroup driven by a scoring formula, not a continuous time gauge with tiered pricing.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
