// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Skyshed — Stargazing Tonight',
  description:
    "MOBILE (390px shell) tonight-only observatory card for Skyshed, one fictional dark-sky night (Fri, Aug 14) on a minutes-after-19:30 axis (domain 0–660): a 52px navBar (28px roof-hatch-and-star mark, tab title, countdown pill re-anchoring 'Dark in 2h 14m' → 'Dark for Xh Ym' → 'Dawn at 4:18 AM' as you scrub) over Tonight/Targets/Sites tabs on a 64px tabBar. The signature move is ONE scrubbable viewTime driving every surface: a 96px NightArcTimeline (nine explicit-pair twilight bands 42/74/114/156…528/570/610/642, a 12px 62% moon band 250→565, an SVG cloud ridge from the literal 11-point array summing 255 → the 23% stat tile, a brand-outlined best window 335–425, and a role=slider playhead with ±5/±30/Home/End keys plus −30m/+30m stepper buttons and a pulsing 'Best window' snap-to-380 button) feeds a half-dome SkyDomeChart (viewBox 326×200, x = 24+(az−70)/220·278, y = 176−alt/90·150, ridge polygon at the site's obstruction°, planets as discs, clusters as four-point stars, an ISS dash arc that exists ONLY at 104–110, marks clipping under the horizon with no ghost, sibling sr-only summary), six 88px TargetVisibilityRows whose MoonWashout/AboveRidge 4px meters fill and drain live (washoutMax 50/42/20/32/27 = round(62·(1−sep/180)); every transit = (rise+set)/2 exactly), a resorting Targets tab ('All 6 targets' terminal caption), and an 'UP AT <time>' top-3 section with a 44px 'See all 6 targets' row that switches tabs and moves focus. Reminder bells are role=switch and execute immediately (undo-over-confirm): toggling plants a ReminderAlertChip ('9:14 PM · ISS pass' seeded) on the bestWindowCard and announces through the single sticky toast dock with exact-snapshot Undo. The site picker is a two-detent (55% / calc(100%−56px)) sheet with per-site horizonMiniBars; committing 'Use this site' (or tapping a Sites-tab radio row) swaps obstruction° straight into the dome ridge and every ABOVE RIDGE meter (Backyard's 22° shows Saturn never clearing early — baked stress). At desktop container widths (≥720px) it renders as a centered 430px phone column, never a stretched relayout. Choose over mobile-allergy-season-radar when the scrubbed axis is a single NIGHT with astronomy-grade fused encodings (twilight/moon/cloud) re-projecting a sky chart, not a multi-day forecast; choose over mobile-transit-companion when the object is a passive observation plan driven by one time slider rather than a live trip with arrival mechanics; choose over mobile-thermostat-schedule when scrubbing must re-derive continuous meters and a projected chart, not edit schedule blocks; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky navBar/tabBar, a bottom sheet, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
