// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Kestrel — Mobile Chrome Gallery',
  description:
    "MOBILE (390px shell) specimen gallery that renders the mobile kit's chrome contract as 17 labeled frames — a living MANIFEST in the composer-state-gallery tradition, correct in both themes by construction. The gallery's own real chrome is a 52px sticky navBar ('Chrome Gallery' 17px/600, 28px Kestrel ember mark, and a LIVE 44×44 Sun/Moon role='switch' that flips colorScheme on the shell so every light-dark() token flips at once) plus sticky blurred sectionHeaders at top 52; below, eight sections of SpecimenFrames (inset 358px cards: 13px/600 caption + LIVE/FROZEN StatePill, muted MiniStage, then an AnnotationBlock of 11px/500 tabular-nums '↳ key: value px' lines citing exact anatomy). §1 four navBar variants (plain push bar with 44×44 back + 200px-ellipsis title, large-title expanded/collapsed at 28px/700, active search flow with 36px field + 'quarterly review' query + clear + Cancel, edit-mode flip at '3 Selected'); §2 the 64px tabBar three ways (a LIVE 5-tab bar whose taps really move the brand tint, an 18px error-badge variant capped at '99+', and the editToolbar that replaces it with Delete at the LEADING end); §3 a LIVE 3-segment radiogroup (36px track, 200ms thumb, arrow keys) plus a frozen disabled-segment still; §4 FAB variants (56px circle, 48px extended pill, 0.92 pressed still); §5 sticky footer CTA default + busy (the one legal 16px inline spinner); §6 frozen sheet compositions at the 55% medium and calc(100%−56px) large detents with 36×5 grabbers over the exact foundations scrim; §7 a z50 full-screen cover; §8 a closing zIndex ladder (sticky 20 → toast 30 → scrim 40 → sheet 41 → cover 50 → alert 61) and motion/corner legend. Nine clipping stress rows are baked into the frames ('Reconciliation & Adjustments — Q3', the Lisbon search query, '248 Selected', 'New voice memo', 'Continue to checkout — $1,284.00', 'Filter, sort & display options'). FROZEN specimens are aria-hidden div stills so no fake buttons enter tab order; the caption + annotations carry the contract for screen readers. Desktop container widths (≥720px) render the same 390px column centered on a muted backdrop — the px anatomy must measure identically at every viewport. Choose over composer-state-gallery when the specimens are MOBILE shell chrome (nav/tab bars, sheets, FABs) rather than a desktop composer's states; choose over bottom-sheet-snap-explorer when you need the whole chrome vocabulary as frozen labeled stills, not an interactive sheet-mechanics playground; choose over mobile-parking-session (or any Mobile app template) when the deliverable is the kit's reference document itself — annotated anatomy with px callouts — not a working product surface.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
