// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Selo — Symptom Day Journal',
  description:
    "MOBILE (390px shell) single-day pain/symptom diary for Selo rendered as an instrument, defaulting to Tue, Jun 16 (8 entries): a 52px navBar with 44×44 prev/next-day chevrons (disabled at the fixture edges) around the date title plus a 24px DayLoadRing whose arc is min(severity-sum, 50)/50 — 34/50 = 68% at rest — then a 5-cell RegionIntensityStrip (64px flex:1 filter buttons: head/chest/gut/joints/skin glyphs, 18% SEV-ramp tint by region max — head 6 · chest 4 · gut 7 · joints 2 · skin 2 — and a 13px tabular max numeral, '–' at zero), a 768px 24-hour DaySpine listCard (32px/hour, 44px hour-label column, 2px rail at x=52) of severity beads sized 12+sev×2 px on a teal→amber→red 10-step light-dark ramp with 4px duration tails (durationMin×32/60) and a lane-2 +28px collision shift (e5 2:05 PM vs e6 2:35 PM, 16px apart), a FactorChipMatrix (coffee 3 · stress 3 · poor-sleep 2 · screen-time 1, live 4px co-occurrence bars scaled to maxCount), and a terminal '8 entries · worst hour 2 PM' caption. The signature move is press-and-slide severity: pointerdown on a bead plus 8px slop then 12px per detent live-resizes and recolors the bead, refills the navBar ring, retints the region cell, and recomputes the worst-hour caption on every detent crossing, committing on pointerup through the one update(entryId, patch) mutator that the edit sheet's 96×32 SeverityStepper (role=spinbutton, ArrowUp/Down) mirrors exactly. Region cells toggle a per-day-keyed filter (non-matching beads fade to 20% + tabIndex −1; chips that never co-occur drop to 40% + aria-disabled — filter 'chest' leaves only Stress lit), the FAB/empty-state CTA opens a medium-detent create sheet (region radiogroup, inline hour/minute/duration steppers, factor toggles, 48px note field with e3's 58-char ellipsis stress, live worst-hour readout), and Delete is undoOverConfirm: immediate removal with an untimed Undo toast that splices the entry back into its exact array position while ring/cells/chips/caption re-derive (delete e5: 68%→54%, gut 7→5, coffee 3→2, worst hour 2 PM→9 AM). Day d2 is the true-empty state (ring 0%, '–' cells, muted chip tracks, one promoted 'Log symptom' CTA); every aggregate is computed in render from the entry array, never stored. At desktop container widths (≥720px) it renders as a centered 430px phone column with hairline borders. Choose over mobile-cycle-phase-wheel when the object is ONE day's entries on a linear 24h spine with per-entry severity gestures, not a 28-day cycle dial; choose over mobile-meal-quickadd-log when logging carries severity/duration/region physics and cross-surface aggregate consequences rather than quick-add counts; choose over mobile-sleep-morning-report when the surface is an editable diary instrument, not a read-mostly morning summary; choose over any desktop template when the brief calls for a phone-first 390px shell with bottom sheet, sticky FAB, press-and-slide gestures, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
