// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Feastly — Party Headcount Grid',
  description:
    "MOBILE (390px shell) party-planning surface for Feastly, \"Dinner at Priya's\" (Sat, Jul 18): a 52px navBar (28px PlateMark — four plate wedges at 100/66/33/0 brand opacity, fullest wedge nudged 2px outward — 'Headcount' title fading in via IntersectionObserver sentinel, 44×44 RefreshCw → static 'Updated just now' caption) over a 52px largeTitle and a 56px countStrip (7 CONFIRMED · 3 MAYBE · 2 OUT NumberRollers + a 'Nudge 2' decay-ring chip opening the nudge-queue sheet), then the DietaryMatrix: a dual-sticky guest-by-dietary pivot grid on columns 'minmax(72px,1fr) repeat(4, minmax(52px,56px))' — 44px sort-button header row sticky top:52, 32px live tally row sticky top:96 ('2 · 1 +1 · 2 +1 · 2 +1', '+n' = maybe overlays), twelve 56px guest rows whose every cell is a real 52–56×56 <button aria-pressed> around a 28×28 toggle (off = 2px ≥3:1 boundary outline, on = brand fill + white check at the 3.5:1 icon floor), out rows at 45% opacity. Below: a 48px ServingsRecalcBar sticky bottom:64 (STD 4 · VEG 2 · VGN 1 · GF 2 · DF 2 rollers; std = 7−2−1 = 4, 4+2+1 = 7 = confirmed ✓) and a 3-tab bar. The signature ripple is one reducer write with cross-tab consequences: tapping Marcus's GF cell rolls the tally 2→3, rolls the recalc GF counter, flips Rosemary Focaccia to '5 std + 2 GF planned · needs 4 + 3' with a 'Short 1' pill and a Menu tab badge '1', and regenerates exactly two Shopping lines (GF flour 240 g→360 g = 3×120 ✓, Soy sauce→GF tamari) with 'updated' dots — Menu and Shopping are pure projections, and the persistent no-timer Undo toast (sticky-in-flow dock, bottom 124 over the recalc bar / 76 elsewhere) restores the snapshot in one assignment, never a confirm dialog. Guest-name taps open a two-detent (55% / calc(100%−56px)) guest sheet: Confirmed/Maybe/Out radiogroup with arrow keys, four whole-row 51×31 switches (the visible non-gesture toggle path), invite decay ring (2d ≈ 29%, 5d ≈ 71%, 6d ≈ 86% arcs) and a 48px 'Send nudge' footer for maybes. Menu pushes a dish-detail screen (ChevronLeft back, per-variant 96×32 steppers, role=spinbutton 0–16) where raising planned clears the badge; per-tab screenByTab + scrollTop persist, re-tapping the active tab pops to root. At desktop container widths (≥720px) it renders as a centered 430px phone column, never a stretched relayout. Choose over mobile-event-rsvp-chat when the job is aggregate headcount-and-provisioning math across a dietary pivot grid, not per-guest conversation threads; choose over mobile-group-gift-pool when quantities derive from WHO is coming (servings, loaves, ml of cream), not from money contributions toward a target; choose over mobile-tip-pool-split when the split axis is dietary flags feeding menu/shopping projections rather than hours-weighted payouts; choose over mobile-transit-companion when the dual-sticky matrix IS the hero surface and every other tab is a derived consequence of toggling its cells.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
