// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Vouchly — Reference Request Manager',
  description:
    "MOBILE (390px shell) reference-gathering state machine for Vouchly, frozen at 'today = Jul 4': a 52px navBar (twin speech-bubble mark, fading compact title driven by the 52px large-title row scrolling under, 44×44 RefreshCw scripted-reply trigger) over a References root with a 116px coverage card — a three-segment typed meter rendering the Senior PM · Meridian Labs requirement profile (Manager 2 / Peer 2 / Direct report 1 = 5) slot by slot as solid brand (confirmed), 45° hatch + explicit ≥3:1 border (pending), or dashed hollow (unasked), captioned '2 of 5 confirmed · 3 pending' — then three relationship sections of 72px swipeable roster rows (40px initials avatar, statusChip in explicit amber/green light-dark pairs, a 28px cooldown drain ring whose 75.4 circumference shows Marcus Bell's 1/3-remaining 25.13 arc, 44×44 ellipsis fallback for the −72px swipe-Nudge block), a Requests tab of 60px sent records grouped ACTIVE · 3 / COMPLETED · 2, and a Packet tab of 88px voucher cards with a sticky 'Share packet (2)' footer. The signature move is chip-assembled outreach: the 56px FAB opens a two-detent (55% / calc(100%−56px)) compose sheet targeting Elena Torres-Konstantopoulou where locked Role/Company chips, Deadline and Tone radio pairs, and two toggles re-flow a live preview through one pure buildMessage() (all-on ≈ 5 sentences scrolls inside the sheet; minimal assembly proves it downward); Send flips her to Awaiting through the single useReducer owner's one update(id, patch) verb, re-hatches the MGR segment, bumps the Requests badge 3→4, and shows an in-sheet receipt with Done. The navBar RefreshCw applies the one scripted reply — Lena Fischer confirms — moving the DR header to '1 OF 1', Packet badge 2→3, and 'Share packet (3)'. Nudges are cooldown-gated (armed rows swipe or act via the ellipsis action sheet; gated rows explain 'Nudged 2d ago · re-arms Fri'), Remove executes immediately with a persistent Undo toast in the one sticky toast dock (bottom 76 above the 64px tabBar), and screens plus scroll positions persist per tab (re-tapping the active tab pops to root). At desktop container widths (≥720px) it renders as a centered 430px phone column, never a stretched relayout. Choose over mobile-newsletter-triage when the object is a typed COVERAGE gauge filled by third-party confirmations with cooldown-gated outreach, not a rollup digest of senders; choose over mobile-date-safety-checkin when progress advances by other people replying (scripted via Refresh) rather than by timed self check-ins; choose over mobile-parking-session when the surface is a multi-tab roster/requests/packet manager with a compose sheet, not a single live metered session with a dial hero; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky navBar/tabBar, bottom sheets, an action sheet, swipe-reveal rows, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
