// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Live Route Tracking',
  description:
    "MOBILE (390px shell) motion-first courier-tracking screen for Dart, order #D-4127: a 52px navBar (Orders back · order title · Replay) over a 46dvh schematic SVG city map (20 token-tinted blocks, Fountain Sq / Alder Park washes, labeled Ninth Ave + Alder St) whose route polyline draws in on mount via pathLength=100 stroke-dashoffset, with a pulsing pickup pin, a drop-off pin, and a courier dot carrying a heading-rotated chevron that EASES leg-by-leg along four precomputed keyframe tracks — 40 sampled points per leg generated at module scope with a decelerate ease baked into the sample spacing (animation runs linear; no rAF, no physics libs) — advanced by a staged setTimeout phase machine (drawing → 4 legs with waypoint dwells → nearby). Passing each waypoint pops a checkpoint row into the Route updates card with an overshoot spring; the scripted leg-3 event recalculates ONCE: the remaining polyline turns dashed-abandoned, a detour segment draws in along Alder St, the ETA jumps +2:00 under an amber opacity-flash overlay, and the polite toast dock announces 'Rerouted +2 min'. Below the map: a ticking m:ss ETA (1s interval from a 500s fixture seed, never wall-clock), a 4-step progress timeline (Picked up → In transit → Nearby → Delivered) whose active segment loops a background-position sheen, a driver card (monogram avatar, ★4.9 · 1,208 deliveries, 44×44 Call/Message buttons), inset-grouped delivery details, and a 44px 'Simulate arrival' demo chip that fast-forwards to Delivered — map dims, LIVE pill flips, and a delivered sheet (absolute inside shell, scroll-locked, Escape/scrim dismiss) slides up with an SVG ring+check stroke-dashoffset draw-on. Replay restarts the whole choreography via a runId key. Reduced motion (matchMedia with change listener): the polyline renders complete, the dot JUMPS between waypoints, pulse/blink/sheen/flash loops are removed, chips and the delivered check appear instantly. Token-pure chrome with ONE quarantined brand literal light-dark(#1D4ED8, #93C5FD) (contrast math at the const). At container widths >560px it renders as a centered 430px phone column on a muted backdrop. Choose over mobile-route-manifest when the surface is the RECIPIENT'S live map choreography (easing dot, reroute event, delivered celebration) rather than a driver's stop-list workflow; choose over mobile-parking-session when the live session is a vehicle moving through a scripted route, not a stationary meter countdown; choose over mobile-luggage-scan-trail when progress is animated on a map in real time instead of a static scan-history timeline; choose over any desktop template when the brief calls for a phone-first 390px shell with staged transform/opacity motion and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
