// Copyright (c) Meta Platforms, Inc. and affiliates.

import type {AstryxPageTemplate} from '@astryxdesign/cli/template';

const template = {
  type: 'page',
  name: 'Tourmark — Apartment Tour Scorecard',
  description:
    "MOBILE (390px shell) one-thumb apartment-tour scorecard for Tourmark: a 52px navBar (28px clipboard-ajar brand mark, 'Unit 4B' title ellipsized at 200px beside a 28px compositePill '80' with a light-dark(#B44E29,#E8916B) border, SlidersHorizontal + RefreshCw 44×44 buttons) over three tabs (Tour / Compare / Notes, sticky 64px tabBar). Tour stacks a 60px LeaderBanner ('Current leader · Unit 12 — 82', 200ms crossfade on rank flips, all-veto variant 'No eligible leader — 4 units vetoed' with a Review-dealbreakers action), four 36px unit chips in 44px hits (u7a ships the live truncation stress 'Unit PH-2 · The Wexford at Barrow Crossing'), six 96px WeightedCriterionRows — 16/500 label, live '5×2 = 10 pts' contribution, five 44×44 rating radios (arrow keys, selected-and-below = brand fill), and a WeightTickStrip readout button (four 8×16 bars + '2x') that opens the weight sheet scrolled to that criterion — then three VetoChip switches ('Mold smell' / 'Pests' / 'Broken deadbolt', ON = error fill + OctagonX) and a live '6 criteria · 44 / 55 pts' caption. A sticky bottom-64 CompareStrip re-ranks four gradient-capped chips (label, 17/700 composite, 4px score bar) with 200ms translateX swaps. The signature move is weight-tuning-with-consequences: the two-detent (55% / calc(100%−56px)) sheet's six 64px rows pair a 128px four-zone snap-drag track with a 96×32 stepper and a role=spinbutton value (the mandated non-gesture path) — dragging Natural light 2x→3x recomputes ΣW 11→12 and flips u4b (49/60 → 82) past u12 (48/60 → 80) live in the 56px SheetLeaderboardMirror, and at 4x the compositePill recounts 80→83 while the single toastDock announces 'Unit 4B is now 83'. Vetoes execute immediately (composite → semantic 0: struck pill '71 0', struck strip chip with 0-width bar, struck leaderboard row) with exact-prior-state Undo through the sticky-in-flow toast dock (no timers); RefreshCw swaps six 96px deterministic skeletons (60/45/70 + 40/55/30 width cycles, shared 1.6s shimmer removed under reduced motion) that resolve on the NEXT user interaction with 'Updated just now'. Per-tab scroll persists via scrollByTab; re-tapping the active tab scrolls to top. At desktop container widths (≥720px) it renders as a centered 430px phone column with hairline borders, never a stretched relayout. Choose over mobile-parking-session when the object is a multi-candidate weighted comparison (ratings × weights → live re-ranking) rather than a single live session with a countdown gauge; choose over mobile-subscription-audit when scoring criteria and tuning weights drive the ranking, not verdict-triage of rows into keep/pause/cancel buckets; choose over mobile-collab-pitch-inbox when the numbers are user-authored ratings/weights re-scored client-side, not inbound offers scored against a rate baseline; choose over any desktop template when the brief calls for a phone-first 390px shell with sticky chrome, a bottom sheet, and 44×44 touch targets.",
  category: 'Mobile',
  componentsUsed: ['Icon'],
} satisfies AstryxPageTemplate;

export default template;
