// Copyright (c) Meta Platforms, Inc. and affiliates.

'use client';

/**
 * @file Status & Feedback Gallery — a four-panel UI-kit page that catalogs
 * the page-state patterns of "Ledgerline", a billing/ops product: alert
 * banners, empty states, progress indicators, and pagination. Every variant
 * is a live specimen, not a screenshot: alerts dismiss into a restore tray,
 * the error empty state retries through a simulated 1 s reload, one demo
 * slider animates the determinate bar / segment strip / percent ring, and
 * the numbered pager actually windows a fixture invoice list beside it.
 *
 * @input Deterministic fixtures only: four seed alert banners plus a
 *   full-width outage bar, a 96-row invoice corpus generated by a pure
 *   helper over small word arrays (no Date.now, no Math.random, no network
 *   assets), fixed empty-state copy, and a 4-step checkout stepper model.
 *   All interactivity lives in useState; the only timer is the 1 s retry
 *   simulation, which is cleaned up on unmount.
 * @output A Layout height="fill" gallery: LayoutHeader with the page title
 *   and a section switcher (SegmentedControl wide / Selector narrow), then
 *   LayoutContent stacking four labeled panels — Alerts (info/success/
 *   warning/error banners with dismiss, an update alert with working
 *   actions, a slim inline field alert that validates an email input, a
 *   full-width system outage bar, and the restore tray that collects
 *   dismissals), Empty states (first-run with a CSS-shape illustration and
 *   a CTA that resolves it, empty-search with clear-filters, error-with-
 *   retry, and a dashed create-new drop target), Progress (slider-driven
 *   determinate bar, 6-segment steps strip, conic-gradient percent ring,
 *   and a clickable 4-step checkout stepper), and Pagination (numbered with
 *   ellipsis over 24 fixture pages windowing a result list, simple
 *   prev/next, load-more with a running count, and a compact table-footer
 *   Pagination).
 * @position Page template; emitted by `astryx template
 *   status-feedback-gallery`.
 *
 * Frame: Layout height="fill". LayoutHeader (divider) holds the title row
 * and the section switcher. LayoutContent scrolls the panel stack; there is
 * no side panel or footer — each pattern panel is a Card with its own
 * heading, and specimens sit in Grids inside it.
 *
 * Responsive contract:
 * - >768px: header keeps title + switcher on one row (SegmentedControl);
 *   specimen Grids run 2-across (minWidth 300 tracks); the numbered pager
 *   and its fixture result list sit side by side.
 * - <=768px: the switcher becomes a full-width Selector under the title;
 *   Grids collapse to one column; the numbered pager stacks above its
 *   result list.
 * - <=640px / 375px: everything is single-pane; the numbered page buttons
 *   keep ~40px tap targets and the button row wraps rather than
 *   overflowing; the stepper wraps its four steps onto two rows. No
 *   hover-only affordances — every action is a real button or link.
 *
 * Container policy: pattern panels are Cards (this is a kit gallery, not a
 * tool surface); specimens inside use plain VStacks with a small
 * VariantLabel header so each archetype is named on the page.
 */

import {
  useEffect,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from 'react';

import {
  HStack,
  Layout,
  LayoutContent,
  LayoutHeader,
  StackItem,
  VStack,
} from '@astryxdesign/core/Layout';
import {Text, Heading} from '@astryxdesign/core/Text';
import {Badge} from '@astryxdesign/core/Badge';
import {Banner} from '@astryxdesign/core/Banner';
import {Button} from '@astryxdesign/core/Button';
import {Card} from '@astryxdesign/core/Card';
import {Divider} from '@astryxdesign/core/Divider';
import {EmptyState} from '@astryxdesign/core/EmptyState';
import {FieldStatus} from '@astryxdesign/core/FieldStatus';
import {Grid} from '@astryxdesign/core/Grid';
import {Icon} from '@astryxdesign/core/Icon';
import {IconButton} from '@astryxdesign/core/IconButton';
import {Link} from '@astryxdesign/core/Link';
import {List, ListItem} from '@astryxdesign/core/List';
import {Pagination} from '@astryxdesign/core/Pagination';
import {ProgressBar} from '@astryxdesign/core/ProgressBar';
import {
  SegmentedControl,
  SegmentedControlItem,
} from '@astryxdesign/core/SegmentedControl';
import {Selector} from '@astryxdesign/core/Selector';
import {Slider} from '@astryxdesign/core/Slider';
import {Spinner} from '@astryxdesign/core/Spinner';
import {TextInput} from '@astryxdesign/core/TextInput';
import {Token} from '@astryxdesign/core/Token';
import {useMediaQuery} from '@astryxdesign/core/hooks';
import {
  ArchiveRestoreIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  FilterXIcon,
  FolderPlusIcon,
  MailIcon,
  MegaphoneIcon,
  PlusIcon,
  RefreshCwIcon,
  SearchIcon,
  ServerCrashIcon,
  SparklesIcon,
  XIcon,
} from 'lucide-react';

// ============= STYLES =============
// Plain inline styles on Astryx design-token CSS variables (declared at
// :root by `@astryxdesign/core/astryx.css`). No StyleX compiler required.

const styles: Record<string, CSSProperties> = {
  page: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--spacing-5)',
    minHeight: '100%',
    boxSizing: 'border-box',
  },
  // Full-width system outage bar: slimmer than a Banner, error-toned.
  outageBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--spacing-2)',
    padding: 'var(--spacing-2) var(--spacing-3)',
    borderRadius: 'var(--radius-md)',
    backgroundColor: 'var(--color-error-muted)',
    border: '1px solid var(--color-error)',
    boxSizing: 'border-box',
    width: '100%',
  },
  // First-run illustration built from CSS shapes only (no image assets):
  // a gradient "window" card with two skeleton bars and a floating dot.
  illustration: {
    position: 'relative',
    width: 128,
    height: 88,
    borderRadius: 'var(--radius-lg)',
    background:
      'linear-gradient(135deg, var(--color-accent-muted), var(--color-background-secondary))',
    border: '1px solid var(--color-border)',
    overflow: 'hidden',
  },
  illustrationTopBar: {
    position: 'absolute',
    top: 12,
    left: 12,
    width: 64,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'var(--color-accent)',
    opacity: 0.6,
  },
  illustrationMidBar: {
    position: 'absolute',
    top: 30,
    left: 12,
    width: 96,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'var(--color-border-emphasized)',
  },
  illustrationLowBar: {
    position: 'absolute',
    top: 48,
    left: 12,
    width: 80,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'var(--color-border-emphasized)',
  },
  illustrationDot: {
    position: 'absolute',
    right: 14,
    bottom: 12,
    width: 24,
    height: 24,
    borderRadius: '50%',
    background:
      'radial-gradient(circle at 30% 30%, var(--color-accent), var(--color-accent-muted))',
  },
  // Dashed "create new" drop target. A real <button> so it is keyboard
  // reachable; ~40px+ tap target by construction.
  dropTarget: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 'var(--spacing-2)',
    width: '100%',
    minHeight: 120,
    padding: 'var(--spacing-4)',
    borderRadius: 'var(--radius-lg)',
    border: '2px dashed var(--color-border)',
    backgroundColor: 'var(--color-background-secondary)',
    color: 'var(--color-text-secondary)',
    cursor: 'pointer',
    font: 'inherit',
    boxSizing: 'border-box',
  },
  // Segmented steps bar: six flex segments; filled ones take accent.
  segmentTrack: {
    display: 'flex',
    gap: 4,
    width: '100%',
  },
  segment: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'var(--color-border)',
  },
  segmentFilled: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'var(--color-accent)',
  },
  // Circular percent ring: conic-gradient donut. The center is truly
  // punched out with a radial-gradient mask so the card surface shows
  // through, and the label sits on top via grid centering.
  ringOuter: {
    position: 'relative',
    width: 96,
    height: 96,
    flexShrink: 0,
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
  },
  ringFill: {
    position: 'absolute',
    inset: 0,
    borderRadius: '50%',
    WebkitMask:
      'radial-gradient(closest-side, transparent calc(100% - 12px), #000 calc(100% - 11.5px))',
    mask: 'radial-gradient(closest-side, transparent calc(100% - 12px), #000 calc(100% - 11.5px))',
  },
  // Checkout stepper: wraps to two rows on narrow screens.
  stepperRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 'var(--spacing-2)',
    alignItems: 'center',
  },
  stepButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--spacing-2)',
    padding: 'var(--spacing-2) var(--spacing-3)',
    minHeight: 40,
    borderRadius: 'var(--radius-md)',
    border: '1px solid var(--color-border)',
    backgroundColor: 'var(--color-background-body)',
    font: 'inherit',
    cursor: 'pointer',
  },
  stepButtonActive: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--spacing-2)',
    padding: 'var(--spacing-2) var(--spacing-3)',
    minHeight: 40,
    borderRadius: 'var(--radius-md)',
    border: '1px solid var(--color-accent)',
    backgroundColor: 'var(--color-accent-muted)',
    font: 'inherit',
    cursor: 'pointer',
  },
  stepButtonUpcoming: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--spacing-2)',
    padding: 'var(--spacing-2) var(--spacing-3)',
    minHeight: 40,
    borderRadius: 'var(--radius-md)',
    border: '1px dashed var(--color-border)',
    backgroundColor: 'var(--color-background-secondary)',
    font: 'inherit',
    color: 'var(--color-text-secondary)',
    cursor: 'default',
  },
  stepIndex: {
    width: 22,
    height: 22,
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    backgroundColor: 'var(--color-border)',
    fontSize: 12,
    flexShrink: 0,
  },
  stepIndexDone: {
    width: 22,
    height: 22,
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    backgroundColor: 'var(--color-success)',
    color: 'var(--color-on-success)',
    flexShrink: 0,
  },
  // Numbered pager: wraps at narrow widths; buttons keep 40px targets.
  pagerRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 'var(--spacing-1)',
    alignItems: 'center',
  },
  ellipsisCell: {
    minWidth: 24,
    textAlign: 'center',
  },
  specimenBody: {
    minHeight: 168,
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--spacing-3)',
  },
};

// ============= DATA =============
// Deterministic fixtures only. The invoice corpus is generated by a pure
// helper over fixed word lists; no clocks, no randomness, no image assets.

type SectionId = 'all' | 'alerts' | 'empty' | 'progress' | 'pagination';

const SECTIONS: Array<{value: SectionId; label: string}> = [
  {value: 'all', label: 'All'},
  {value: 'alerts', label: 'Alerts'},
  {value: 'empty', label: 'Empty states'},
  {value: 'progress', label: 'Progress'},
  {value: 'pagination', label: 'Pagination'},
];

type AlertStatus = 'info' | 'success' | 'warning' | 'error';

interface GalleryAlert {
  id: string;
  status: AlertStatus;
  title: string;
  description: string;
}

// The four core banner specimens (info/success/warning/error).
const SEED_ALERTS: GalleryAlert[] = [
  {
    id: 'alert-info',
    status: 'info',
    title: 'Sandbox mode is on',
    description:
      'Charges in this workspace hit the test processor only. Switch to live keys from Settings when you are ready.',
  },
  {
    id: 'alert-success',
    status: 'success',
    title: 'Export complete',
    description:
      'invoices-june.csv (2,411 rows) is ready in your downloads panel.',
  },
  {
    id: 'alert-warning',
    status: 'warning',
    title: 'Card expiring soon',
    description:
      'The Visa ending 4421 on the Acme Robotics account expires this month. Ask the owner to update billing.',
  },
  {
    id: 'alert-error',
    status: 'error',
    title: 'Webhook endpoint failing',
    description:
      'https://hooks.acme.dev/billing has returned 500 for the last 12 deliveries. Retries pause after 72 hours.',
  },
];

// Full-width system outage bar (slim, above the banner stack).
const OUTAGE_ALERT: GalleryAlert = {
  id: 'alert-outage',
  status: 'error',
  title: 'Partial outage: payout reporting is delayed',
  description:
    'Payout reporting is delayed — data older than 10:00 UTC is accurate; newer rows are still catching up.',
};

// Empty-search specimen: the applied filter chips and the rows they hide.
const SEARCH_FILTERS = ['status:archived', 'owner:me', 'currency:CHF'];

const HIDDEN_SEARCH_ROWS = [
  {id: 'sr-1', title: 'INV-2093 — Acme Robotics', meta: 'USD 1,240.00 · Paid'},
  {id: 'sr-2', title: 'INV-2094 — Northwind Labs', meta: 'USD 86.00 · Open'},
  {id: 'sr-3', title: 'INV-2101 — Globex GmbH', meta: 'EUR 410.50 · Paid'},
];

// Rows that "load" when the error specimen's retry resolves.
const RECOVERED_ROWS = [
  {id: 'rr-1', title: 'Payout PO-5581', meta: 'USD 12,904.11 · In transit'},
  {id: 'rr-2', title: 'Payout PO-5580', meta: 'USD 9,377.20 · Paid'},
  {id: 'rr-3', title: 'Payout PO-5579', meta: 'USD 11,032.75 · Paid'},
];

// Checkout stepper model.
const CHECKOUT_STEPS = ['Cart', 'Shipping', 'Payment', 'Review'] as const;

// Pagination corpus: 24 pages × 4 rows = 96 deterministic invoices.
const PAGE_SIZE = 4;
const TOTAL_PAGES = 24;
const TOTAL_ROWS = PAGE_SIZE * TOTAL_PAGES;

const CUSTOMERS = [
  'Acme Robotics',
  'Northwind Labs',
  'Globex GmbH',
  'Initech',
  'Umbrella Supply',
  'Stark Industrial',
  'Wayne Tooling',
  'Hooli Cloud',
];

const INVOICE_STATUSES = ['Paid', 'Open', 'Past due', 'Draft'] as const;

interface InvoiceRow {
  id: string;
  title: string;
  customer: string;
  amount: string;
  status: (typeof INVOICE_STATUSES)[number];
}

/** Pure, index-driven fixture generator — same output on every render. */
function makeInvoice(index: number): InvoiceRow {
  const number = 2000 + index;
  const customer = CUSTOMERS[index % CUSTOMERS.length];
  const status = INVOICE_STATUSES[index % INVOICE_STATUSES.length];
  // Deterministic pseudo-amount: cycles through a fixed range.
  const dollars = 120 + ((index * 37) % 900);
  const cents = (index * 13) % 100;
  return {
    id: `inv-${number}`,
    title: `INV-${number}`,
    customer,
    amount: `USD ${dollars}.${String(cents).padStart(2, '0')}`,
    status,
  };
}

const INVOICES: InvoiceRow[] = Array.from({length: TOTAL_ROWS}, (_, index) =>
  makeInvoice(index),
);

const STATUS_TOKEN_COLOR: Record<
  (typeof INVOICE_STATUSES)[number],
  'green' | 'blue' | 'orange' | 'purple'
> = {
  Paid: 'green',
  Open: 'blue',
  'Past due': 'orange',
  Draft: 'purple',
};

const LOAD_MORE_CHUNK = 8;

// ============= HELPERS =============

/**
 * Windows page numbers around the current page with `-1` sentinels for
 * ellipses, e.g. 1 … 7 8 9 … 24. Pure and deterministic.
 */
function buildPageWindow(current: number, total: number): number[] {
  if (total <= 7) {
    return Array.from({length: total}, (_, index) => index + 1);
  }
  const pages: number[] = [1];
  const start = Math.max(2, current - 1);
  const end = Math.min(total - 1, current + 1);
  if (start > 2) {
    pages.push(-1);
  }
  for (let page = start; page <= end; page++) {
    pages.push(page);
  }
  if (end < total - 1) {
    pages.push(-1);
  }
  pages.push(total);
  return pages;
}

function isValidEmail(value: string): boolean {
  // Fixture-grade validation: something@something.tld
  return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(value);
}

// ============= SHARED BITS =============

/** Small label header above each specimen so every variant is named. */
function VariantLabel({label, hint}: {label: string; hint?: string}) {
  return (
    <VStack gap={0.5}>
      <Text type="label" color="secondary">
        {label}
      </Text>
      {hint != null && (
        <Text type="supporting" color="secondary">
          {hint}
        </Text>
      )}
    </VStack>
  );
}

/** Panel wrapper: Card with a heading row and a Badge naming the archetype. */
function PatternPanel({
  id,
  title,
  archetype,
  description,
  children,
}: {
  id: string;
  title: string;
  archetype: string;
  description: string;
  children: ReactNode;
}) {
  return (
    <Card padding={4} aria-labelledby={`${id}-heading`}>
      <VStack gap={4}>
        <VStack gap={1}>
          <HStack gap={2} vAlign="center" wrap="wrap">
            <Heading level={2} id={`${id}-heading`}>
              {title}
            </Heading>
            <Badge label={archetype} />
          </HStack>
          <Text type="supporting" color="secondary">
            {description}
          </Text>
        </VStack>
        <Divider />
        {children}
      </VStack>
    </Card>
  );
}

function InvoiceList({rows}: {rows: InvoiceRow[]}) {
  return (
    <List density="compact" hasDividers>
      {rows.map(row => (
        <ListItem
          key={row.id}
          label={
            <Text size="sm" weight="medium" maxLines={1}>
              {row.title} — {row.customer}
            </Text>
          }
          description={
            <Text type="supporting" color="secondary" maxLines={1}>
              {row.amount}
            </Text>
          }
          endContent={
            <Token
              label={row.status}
              color={STATUS_TOKEN_COLOR[row.status]}
              size="sm"
            />
          }
        />
      ))}
    </List>
  );
}

// ============= PANEL 1: ALERTS =============

function AlertsPanel() {
  // Which of the five dismissable alerts (outage + four banners) are
  // currently dismissed. Dismissals collect in the restore tray below so
  // the panel never dead-ends.
  const [dismissedIds, setDismissedIds] = useState<string[]>([]);
  // The "alert with actions" specimen: update pending → updated.
  const [updateApplied, setUpdateApplied] = useState(false);
  const [updateSnoozed, setUpdateSnoozed] = useState(false);
  // Slim inline field alert: email subscribe with validation.
  const [email, setEmail] = useState('ops@acme');
  const [emailTouched, setEmailTouched] = useState(false);
  const [subscribed, setSubscribed] = useState(false);

  const dismiss = (id: string) => {
    setDismissedIds(prev => (prev.includes(id) ? prev : [...prev, id]));
  };
  const restore = (id: string) => {
    setDismissedIds(prev => prev.filter(item => item !== id));
  };
  const restoreAll = () => setDismissedIds([]);

  const allAlerts = [OUTAGE_ALERT, ...SEED_ALERTS];
  const dismissedAlerts = allAlerts.filter(alert =>
    dismissedIds.includes(alert.id),
  );

  const emailInvalid = !isValidEmail(email);
  const showEmailError = emailTouched && emailInvalid && !subscribed;

  const trySubscribe = () => {
    setEmailTouched(true);
    if (!emailInvalid) {
      setSubscribed(true);
    }
  };

  return (
    <PatternPanel
      id="alerts"
      title="Alerts"
      archetype="Application UI / Alerts"
      description="Status banners with icon and dismiss, an alert with working actions, a slim inline field alert, and a full-width system outage bar. Dismissed alerts collect in the restore tray."
      >
      <VStack gap={4}>
        {/* Full-width system outage bar */}
        <VStack gap={2}>
          <VariantLabel
            label="System outage bar"
            hint="Full-width, slim, product-wide scope — sits above all page chrome."
          />
          {dismissedIds.includes(OUTAGE_ALERT.id) ? (
            <Text type="supporting" color="secondary">
              Outage bar dismissed — restore it from the tray below.
            </Text>
          ) : (
            <div style={styles.outageBar} role="status">
              <Icon icon={MegaphoneIcon} size="sm" />
              <StackItem size="fill">
                <Text size="sm" weight="medium">
                  {OUTAGE_ALERT.description}
                </Text>
              </StackItem>
              <Link href="#status" type="supporting">
                Status page
              </Link>
              <IconButton
                label="Dismiss outage bar"
                icon={<Icon icon={XIcon} size="sm" />}
                variant="ghost"
                size="sm"
                onClick={() => dismiss(OUTAGE_ALERT.id)}
              />
            </div>
          )}
        </VStack>

        {/* Info / success / warning / error banners */}
        <VStack gap={2}>
          <VariantLabel
            label="Status banners"
            hint="One per intent: info, success, warning, error. Each has an icon and a dismiss control."
          />
          {SEED_ALERTS.every(alert => dismissedIds.includes(alert.id)) ? (
            <Text type="supporting" color="secondary">
              All four banners dismissed — restore them from the tray below.
            </Text>
          ) : (
            <VStack gap={2}>
              {SEED_ALERTS.filter(
                alert => !dismissedIds.includes(alert.id),
              ).map(alert => (
                <Banner
                  key={alert.id}
                  status={alert.status}
                  title={alert.title}
                  description={alert.description}
                  isDismissable
                  onDismiss={() => dismiss(alert.id)}
                />
              ))}
            </VStack>
          )}
        </VStack>

        {/* Alert with actions */}
        <VStack gap={2}>
          <VariantLabel
            label="Alert with actions"
            hint="Primary and secondary actions inline; both do something."
          />
          {updateSnoozed ? (
            <HStack gap={2} vAlign="center">
              <Text type="supporting" color="secondary">
                Update reminder snoozed for this session.
              </Text>
              <Link onClick={() => setUpdateSnoozed(false)} type="supporting">
                Bring it back
              </Link>
            </HStack>
          ) : updateApplied ? (
            <Banner
              status="success"
              title="Workspace updated to v2.4.1"
              description="Rate-limit dashboards and CSV exports picked up the new columns."
              endContent={
                <Button
                  label="Undo"
                  variant="ghost"
                  size="sm"
                  onClick={() => setUpdateApplied(false)}
                />
              }
            />
          ) : (
            <Banner
              status="info"
              title="Ledgerline v2.4.1 is available"
              description="Adds per-endpoint webhook retry policies and faster CSV exports."
              endContent={
                <HStack gap={2} vAlign="center">
                  <Button
                    label="Update now"
                    variant="primary"
                    size="sm"
                    onClick={() => setUpdateApplied(true)}
                  />
                  <Button
                    label="Later"
                    variant="ghost"
                    size="sm"
                    onClick={() => setUpdateSnoozed(true)}
                  />
                </HStack>
              }
            />
          )}
        </VStack>

        {/* Slim inline field alert */}
        <VStack gap={2}>
          <VariantLabel
            label="Inline field alert"
            hint="Slim, field-scoped feedback — validates as you type and on submit."
          />
          <HStack gap={2} vAlign="start" wrap="wrap">
            <StackItem size="fill">
              <VStack gap={1}>
                <TextInput
                  label="Alert digest email"
                  isLabelHidden
                  value={email}
                  onChange={value => {
                    setEmail(value);
                    setSubscribed(false);
                  }}
                  onBlur={() => setEmailTouched(true)}
                  placeholder="you@company.com"
                  startIcon={<Icon icon={MailIcon} size="sm" />}
                  width="100%"
                />
                {showEmailError && (
                  <FieldStatus
                    variant="detached"
                    type="error"
                    message="Enter a full email address, like ops@acme.dev."
                  />
                )}
                {subscribed && (
                  <FieldStatus
                    variant="detached"
                    type="success"
                    message={`Digest enabled — weekly alert summary goes to ${email}.`}
                  />
                )}
              </VStack>
            </StackItem>
            <Button
              label="Subscribe"
              variant="secondary"
              onClick={trySubscribe}
            />
          </HStack>
        </VStack>

        {/* Restore tray */}
        {dismissedAlerts.length > 0 && (
          <VStack gap={2}>
            <Divider />
            <HStack gap={2} vAlign="center">
              <Icon icon={ArchiveRestoreIcon} size="sm" />
              <StackItem size="fill">
                <Text type="label">
                  Restore tray · {dismissedAlerts.length} dismissed
                </Text>
              </StackItem>
              <Button
                label="Restore all"
                variant="ghost"
                size="sm"
                onClick={restoreAll}
              />
            </HStack>
            <List density="compact" hasDividers>
              {dismissedAlerts.map(alert => (
                <ListItem
                  key={alert.id}
                  label={
                    <Text size="sm" maxLines={1}>
                      {alert.title}
                    </Text>
                  }
                  startContent={
                    <Badge
                      label={alert.status}
                      variant={alert.status === 'error' ? 'error' : undefined}
                    />
                  }
                  endContent={
                    <Button
                      label="Restore"
                      variant="ghost"
                      size="sm"
                      onClick={() => restore(alert.id)}
                    />
                  }
                />
              ))}
            </List>
          </VStack>
        )}
      </VStack>
    </PatternPanel>
  );
}

// ============= PANEL 2: EMPTY STATES =============

function FirstRunSpecimen() {
  const [created, setCreated] = useState(false);
  return (
    <VStack gap={2} style={styles.specimenBody}>
      <VariantLabel
        label="First run"
        hint="Illustrated welcome with a single primary CTA."
      />
      {created ? (
        <VStack gap={2}>
          <List density="compact" hasDividers>
            <ListItem
              label={
                <Text size="sm" weight="medium">
                  Q3 invoicing
                </Text>
              }
              description={
                <Text type="supporting" color="secondary">
                  Empty project · just created
                </Text>
              }
              startContent={<Icon icon={SparklesIcon} size="sm" />}
            />
          </List>
          <FieldStatus
            variant="detached"
            type="success"
            message="Project created — the empty state resolved into the list."
          />
          <Link onClick={() => setCreated(false)} type="supporting">
            Reset demo
          </Link>
        </VStack>
      ) : (
        <VStack gap={3} hAlign="center">
          <div style={styles.illustration} aria-hidden>
            <div style={styles.illustrationTopBar} />
            <div style={styles.illustrationMidBar} />
            <div style={styles.illustrationLowBar} />
            <div style={styles.illustrationDot} />
          </div>
          <EmptyState
            title="No projects yet"
            description="Projects group invoices, payouts, and alerts for one client."
            isCompact
            actions={
              <Button
                label="Create your first project"
                variant="primary"
                onClick={() => setCreated(true)}
              />
            }
          />
        </VStack>
      )}
    </VStack>
  );
}

function EmptySearchSpecimen() {
  const [filtersApplied, setFiltersApplied] = useState(true);
  return (
    <VStack gap={2} style={styles.specimenBody}>
      <VariantLabel
        label="Empty search"
        hint="The query matches rows, but the applied filters hide them all."
      />
      {filtersApplied ? (
        <VStack gap={2}>
          <HStack gap={1} wrap="wrap">
            {SEARCH_FILTERS.map(filter => (
              <Token key={filter} label={filter} color="blue" size="sm" />
            ))}
          </HStack>
          <EmptyState
            icon={<Icon icon={SearchIcon} size="lg" />}
            title="No invoices match"
            description="3 invoices match “acme” but are excluded by the filters above."
            isCompact
            actions={
              <Button
                label="Clear filters"
                variant="secondary"
                onClick={() => setFiltersApplied(false)}
              />
            }
          />
        </VStack>
      ) : (
        <VStack gap={2}>
          <InvoiceListLite rows={HIDDEN_SEARCH_ROWS} />
          <Link onClick={() => setFiltersApplied(true)} type="supporting">
            Re-apply filters
          </Link>
        </VStack>
      )}
    </VStack>
  );
}

function InvoiceListLite({
  rows,
}: {
  rows: Array<{id: string; title: string; meta: string}>;
}) {
  return (
    <List density="compact" hasDividers>
      {rows.map(row => (
        <ListItem
          key={row.id}
          label={
            <Text size="sm" weight="medium" maxLines={1}>
              {row.title}
            </Text>
          }
          description={
            <Text type="supporting" color="secondary" maxLines={1}>
              {row.meta}
            </Text>
          }
        />
      ))}
    </List>
  );
}

type RetryPhase = 'error' | 'retrying' | 'resolved';

function ErrorRetrySpecimen() {
  const [phase, setPhase] = useState<RetryPhase>('error');
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // The retry simulates a 1 s reload, then resolves. Clean the timer up on
  // unmount so switching panels mid-retry never fires a stale setState.
  useEffect(() => {
    return () => {
      if (timerRef.current != null) {
        clearTimeout(timerRef.current);
      }
    };
  }, []);

  const startRetry = () => {
    setPhase('retrying');
    timerRef.current = setTimeout(() => {
      setPhase('resolved');
      timerRef.current = null;
    }, 1000);
  };

  return (
    <VStack gap={2} style={styles.specimenBody}>
      <VariantLabel
        label="Error state with retry"
        hint="Retry simulates a 1 s reload, then resolves into content."
      />
      {phase === 'resolved' ? (
        <VStack gap={2}>
          <FieldStatus
            variant="detached"
            type="success"
            message="Reloaded — payouts are back."
          />
          <InvoiceListLite rows={RECOVERED_ROWS} />
          <Link onClick={() => setPhase('error')} type="supporting">
            Reset demo
          </Link>
        </VStack>
      ) : phase === 'retrying' ? (
        <VStack gap={2} hAlign="center" style={{minHeight: 120}}>
          <Spinner size="sm" aria-label="Retrying payout fetch" />
          <Text type="supporting" color="secondary">
            Retrying payout fetch…
          </Text>
        </VStack>
      ) : (
        <EmptyState
          icon={<Icon icon={ServerCrashIcon} size="lg" />}
          title="Couldn’t load payouts"
          description="The reporting service returned 503. Your data is safe; only this view failed."
          isCompact
          actions={
            <Button
              label="Retry"
              variant="secondary"
              onClick={startRetry}
              icon={<Icon icon={RefreshCwIcon} size="sm" />}
            />
          }
        />
      )}
    </VStack>
  );
}

function DropTargetSpecimen() {
  const [draftCount, setDraftCount] = useState(0);
  return (
    <VStack gap={2} style={styles.specimenBody}>
      <VariantLabel
        label="Create-new drop target"
        hint="Dashed target doubles as the empty state for a drafts rail."
      />
      <button
        type="button"
        style={styles.dropTarget}
        onClick={() => setDraftCount(count => count + 1)}
        aria-label="Create a new draft invoice (or drop a CSV here)">
        <Icon icon={FolderPlusIcon} size="lg" />
        <Text size="sm" weight="medium">
          Drop a CSV or click to create a draft
        </Text>
        <Text type="supporting" color="secondary">
          Drafts stay private until you send them.
        </Text>
      </button>
      {draftCount > 0 && (
        <HStack gap={2} vAlign="center">
          <StackItem size="fill">
            <FieldStatus
              variant="detached"
              type="success"
              message={
                draftCount === 1
                  ? 'Draft created.'
                  : `${draftCount} drafts created.`
              }
            />
          </StackItem>
          <Link onClick={() => setDraftCount(0)} type="supporting">
            Reset
          </Link>
        </HStack>
      )}
    </VStack>
  );
}

function EmptyStatesPanel() {
  return (
    <PatternPanel
      id="empty"
      title="Empty states"
      archetype="Application UI / Empty States"
      description="First-run, empty-search, error-with-retry, and a dashed create-new drop target. Every one resolves into real content — none of them dead-end."
      >
      <Grid columns={{minWidth: 300, max: 2}} gap={4}>
        <FirstRunSpecimen />
        <EmptySearchSpecimen />
        <ErrorRetrySpecimen />
        <DropTargetSpecimen />
      </Grid>
    </PatternPanel>
  );
}

// ============= PANEL 3: PROGRESS =============

const SEGMENT_COUNT = 6;

function ProgressPanel() {
  // One demo slider animates the determinate bar, the segment strip, and
  // the percent ring so the relationship between the three is obvious.
  const [percent, setPercent] = useState(45);
  const [checkoutStep, setCheckoutStep] = useState(1);

  const filledSegments = Math.round((percent / 100) * SEGMENT_COUNT);
  const ringFillStyle: CSSProperties = {
    ...styles.ringFill,
    background: `conic-gradient(var(--color-accent) ${
      percent * 3.6
    }deg, var(--color-border-emphasized) 0deg)`,
  };

  const goToStep = (index: number) => {
    // Completed steps are clickable; upcoming steps are not skippable.
    if (index <= checkoutStep) {
      setCheckoutStep(index);
    }
  };

  return (
    <PatternPanel
      id="progress"
      title="Progress"
      archetype="Application UI / Progress Bars"
      description="A determinate bar, segmented steps strip, and percent ring all driven by one demo slider, plus a 4-step checkout stepper with clickable completed steps."
      >
      <VStack gap={4}>
        <VStack gap={2}>
          <VariantLabel
            label="Demo value"
            hint="Drag the slider — the bar, segments, and ring below all track it."
          />
          <Slider
            label="Demo progress value"
            min={0}
            max={100}
            step={5}
            value={percent}
            onChange={(next: number) => setPercent(next)}
            formatValue={value => `${value}%`}
          />
        </VStack>

        <Grid columns={{minWidth: 240, max: 3}} gap={4}>
          <VStack gap={2}>
            <VariantLabel label="Determinate bar" />
            <ProgressBar
              value={percent}
              max={100}
              label={`Import progress: ${percent}%`}
              isLabelHidden
              variant={percent === 100 ? 'success' : 'accent'}
            />
            <Text type="supporting" color="secondary">
              {percent === 100
                ? 'Import complete.'
                : `Importing ledger rows — ${percent}% done.`}
            </Text>
          </VStack>

          <VStack gap={2}>
            <VariantLabel label="Segmented steps" />
            <div
              style={styles.segmentTrack}
              role="img"
              aria-label={`${filledSegments} of ${SEGMENT_COUNT} segments complete`}>
              {Array.from({length: SEGMENT_COUNT}, (_, index) => (
                <div
                  key={index}
                  style={
                    index < filledSegments
                      ? styles.segmentFilled
                      : styles.segment
                  }
                />
              ))}
            </div>
            <Text type="supporting" color="secondary">
              {filledSegments} of {SEGMENT_COUNT} batches migrated.
            </Text>
          </VStack>

          <VStack gap={2}>
            <VariantLabel label="Percent ring" />
            <HStack gap={3} vAlign="center">
              <div
                style={styles.ringOuter}
                role="img"
                aria-label={`Storage used: ${percent}%`}>
                <div style={ringFillStyle} aria-hidden />
                <Text size="sm" weight="semibold">
                  {percent}%
                </Text>
              </div>
              <Text type="supporting" color="secondary">
                Conic-gradient donut; the label sits in the punched-out
                center.
              </Text>
            </HStack>
          </VStack>
        </Grid>

        <Divider />

        <VStack gap={2}>
          <VariantLabel
            label="Checkout stepper"
            hint="Completed steps are clickable to jump back; upcoming steps stay locked."
          />
          <div style={styles.stepperRow}>
            {CHECKOUT_STEPS.map((step, index) => {
              const isDone = index < checkoutStep;
              const isActive = index === checkoutStep;
              return (
                <button
                  key={step}
                  type="button"
                  style={
                    isActive
                      ? styles.stepButtonActive
                      : isDone
                        ? styles.stepButton
                        : styles.stepButtonUpcoming
                  }
                  onClick={() => goToStep(index)}
                  disabled={index > checkoutStep}
                  aria-current={isActive ? 'step' : undefined}
                  aria-label={
                    isDone
                      ? `${step} (completed — click to return)`
                      : isActive
                        ? `${step} (current step)`
                        : `${step} (upcoming)`
                  }>
                  <span
                    style={isDone ? styles.stepIndexDone : styles.stepIndex}
                    aria-hidden>
                    {isDone ? <Icon icon={CheckIcon} size="xsm" /> : index + 1}
                  </span>
                  <Text size="sm" weight={isActive ? 'semibold' : 'normal'}>
                    {step}
                  </Text>
                </button>
              );
            })}
          </div>
          <HStack gap={2} vAlign="center">
            <Button
              label="Back"
              variant="ghost"
              size="sm"
              isDisabled={checkoutStep === 0}
              onClick={() => setCheckoutStep(step => Math.max(0, step - 1))}
            />
            <Button
              label={
                checkoutStep === CHECKOUT_STEPS.length - 1
                  ? 'Place order'
                  : 'Next'
              }
              variant="primary"
              size="sm"
              isDisabled={checkoutStep === CHECKOUT_STEPS.length - 1}
              onClick={() =>
                setCheckoutStep(step =>
                  Math.min(CHECKOUT_STEPS.length - 1, step + 1),
                )
              }
            />
            <Text type="supporting" color="secondary">
              Step {checkoutStep + 1} of {CHECKOUT_STEPS.length} ·{' '}
              {CHECKOUT_STEPS[checkoutStep]}
            </Text>
          </HStack>
        </VStack>
      </VStack>
    </PatternPanel>
  );
}

// ============= PANEL 4: PAGINATION =============

function NumberedPagerSpecimen({isCompact}: {isCompact: boolean}) {
  const [page, setPage] = useState(8);
  const rows = INVOICES.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  const windowPages = buildPageWindow(page, TOTAL_PAGES);

  const pager = (
    <VStack gap={2}>
      <div
        style={styles.pagerRow}
        role="navigation"
        aria-label="Invoice pages (numbered)">
        <IconButton
          label="Previous page"
          icon={<Icon icon={ChevronLeftIcon} size="sm" />}
          variant="ghost"
          isDisabled={page === 1}
          onClick={() => setPage(current => Math.max(1, current - 1))}
        />
        {windowPages.map((pageNumber, index) =>
          pageNumber === -1 ? (
            <span
              key={`gap-${index}`}
              style={styles.ellipsisCell}
              aria-hidden>
              <Text type="supporting" color="secondary">
                …
              </Text>
            </span>
          ) : (
            <Button
              key={pageNumber}
              label={String(pageNumber)}
              variant={pageNumber === page ? 'primary' : 'ghost'}
              size="sm"
              aria-current={pageNumber === page ? 'page' : undefined}
              onClick={() => setPage(pageNumber)}
            />
          ),
        )}
        <IconButton
          label="Next page"
          icon={<Icon icon={ChevronRightIcon} size="sm" />}
          variant="ghost"
          isDisabled={page === TOTAL_PAGES}
          onClick={() =>
            setPage(current => Math.min(TOTAL_PAGES, current + 1))
          }
        />
      </div>
      <Text type="supporting" color="secondary">
        Page {page} of {TOTAL_PAGES} · the list{' '}
        {isCompact ? 'below' : 'beside this pager'} is the live window.
      </Text>
    </VStack>
  );

  const resultList = (
    <VStack gap={1}>
      <Text type="label" color="secondary">
        Invoices {(page - 1) * PAGE_SIZE + 1}–{page * PAGE_SIZE} of{' '}
        {TOTAL_ROWS}
      </Text>
      <InvoiceList rows={rows} />
    </VStack>
  );

  return (
    <VStack gap={2}>
      <VariantLabel
        label="Numbered with ellipsis"
        hint={`Windows ${TOTAL_PAGES} fixture pages; the result list re-slices on every click.`}
      />
      {isCompact ? (
        <VStack gap={3}>
          {pager}
          {resultList}
        </VStack>
      ) : (
        <HStack gap={4} vAlign="start">
          <StackItem size="fill">{pager}</StackItem>
          <StackItem size="fill">{resultList}</StackItem>
        </HStack>
      )}
    </VStack>
  );
}

function SimplePrevNextSpecimen() {
  const [page, setPage] = useState(1);
  return (
    <VStack gap={2}>
      <VariantLabel
        label="Simple prev / next"
        hint="No numbers — just the two controls and a position readout."
      />
      <HStack gap={2} vAlign="center">
        <Button
          label="Previous"
          variant="secondary"
          size="sm"
          icon={<Icon icon={ChevronLeftIcon} size="sm" />}
          isDisabled={page === 1}
          onClick={() => setPage(current => Math.max(1, current - 1))}
        />
        <Button
          label="Next"
          variant="secondary"
          size="sm"
          icon={<Icon icon={ChevronRightIcon} size="sm" />}
          isDisabled={page === TOTAL_PAGES}
          onClick={() =>
            setPage(current => Math.min(TOTAL_PAGES, current + 1))
          }
        />
        <Text type="supporting" color="secondary">
          Page {page} of {TOTAL_PAGES}
        </Text>
      </HStack>
    </VStack>
  );
}

function LoadMoreSpecimen() {
  const [visibleCount, setVisibleCount] = useState(LOAD_MORE_CHUNK);
  const exhausted = visibleCount >= TOTAL_ROWS;
  const shown = Math.min(visibleCount, TOTAL_ROWS);
  return (
    <VStack gap={2}>
      <VariantLabel
        label="Load more"
        hint="Append-style paging with a running count instead of pages."
      />
      <InvoiceList rows={INVOICES.slice(0, Math.min(shown, PAGE_SIZE))} />
      <Text type="supporting" color="secondary">
        Showing {shown} of {TOTAL_ROWS} invoices (first {PAGE_SIZE} rendered
        here; the count is the live state).
      </Text>
      <HStack gap={2} vAlign="center">
        {exhausted ? (
          <>
            <Text type="supporting" color="secondary">
              All {TOTAL_ROWS} loaded.
            </Text>
            <Link
              onClick={() => setVisibleCount(LOAD_MORE_CHUNK)}
              type="supporting">
              Reset
            </Link>
          </>
        ) : (
          <Button
            label={`Load ${Math.min(
              LOAD_MORE_CHUNK,
              TOTAL_ROWS - shown,
            )} more`}
            variant="secondary"
            size="sm"
            icon={<Icon icon={PlusIcon} size="sm" />}
            onClick={() =>
              setVisibleCount(count =>
                Math.min(TOTAL_ROWS, count + LOAD_MORE_CHUNK),
              )
            }
          />
        )}
      </HStack>
    </VStack>
  );
}

function TableFooterSpecimen() {
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(PAGE_SIZE);
  const totalPages = Math.max(1, Math.ceil(TOTAL_ROWS / pageSize));
  const currentPage = Math.min(page, totalPages);
  const rangeStart = (currentPage - 1) * pageSize + 1;
  const rangeEnd = Math.min(currentPage * pageSize, TOTAL_ROWS);
  return (
    <VStack gap={2}>
      <VariantLabel
        label="Compact table footer"
        hint="The Astryx Pagination component with a page-size selector."
      />
      <Card padding={2}>
        <HStack gap={3} vAlign="center" wrap="wrap">
          <StackItem size="fill">
            <Text type="supporting" color="secondary">
              Showing {rangeStart}–{rangeEnd} of {TOTAL_ROWS}
            </Text>
          </StackItem>
          <Pagination
            label="Invoice table pages"
            page={currentPage}
            onChange={setPage}
            totalItems={TOTAL_ROWS}
            pageSize={pageSize}
            pageSizeOptions={[4, 8, 12]}
            onPageSizeChange={size => {
              setPageSize(size);
              setPage(1);
            }}
            size="sm"
          />
        </HStack>
      </Card>
    </VStack>
  );
}

function PaginationPanel({isCompact}: {isCompact: boolean}) {
  return (
    <PatternPanel
      id="pagination"
      title="Pagination"
      archetype="Application UI / Pagination"
      description="Four paging idioms over the same 96-row invoice corpus: numbered with ellipsis (windowing a live result list), simple prev/next, load-more with a count, and a compact table footer."
      >
      <VStack gap={4}>
        <NumberedPagerSpecimen isCompact={isCompact} />
        <Divider />
        <Grid columns={{minWidth: 300, max: 2}} gap={4}>
          <SimplePrevNextSpecimen />
          <LoadMoreSpecimen />
        </Grid>
        <Divider />
        <TableFooterSpecimen />
      </VStack>
    </PatternPanel>
  );
}

// ============= PAGE =============

export default function StatusFeedbackGalleryTemplate() {
  const [section, setSection] = useState<SectionId>('all');
  const isCompact = useMediaQuery('(max-width: 768px)');

  const show = (id: Exclude<SectionId, 'all'>) =>
    section === 'all' || section === id;

  const switcher = isCompact ? (
    <Selector
      label="Show section"
      isLabelHidden
      options={SECTIONS.map(item => ({
        value: item.value,
        label: item.label,
      }))}
      value={section}
      onChange={value => setSection(value as SectionId)}
      width="100%"
    />
  ) : (
    <SegmentedControl
      label="Show section"
      value={section}
      onChange={value => setSection(value as SectionId)}
      size="sm">
      {SECTIONS.map(item => (
        <SegmentedControlItem
          key={item.value}
          label={item.label}
          value={item.value}
        />
      ))}
    </SegmentedControl>
  );

  return (
    <Layout
      height="fill"
      header={
        <LayoutHeader hasDivider role="banner">
          {isCompact ? (
            <VStack gap={2}>
              <VStack gap={0.5}>
                <Heading level={1}>Status &amp; Feedback Gallery</Heading>
                <Text type="supporting" color="secondary">
                  Live specimens of Ledgerline’s page-state patterns.
                </Text>
              </VStack>
              {switcher}
            </VStack>
          ) : (
            <HStack gap={3} vAlign="center">
              <StackItem size="fill">
                <VStack gap={0.5}>
                  <Heading level={1}>Status &amp; Feedback Gallery</Heading>
                  <Text type="supporting" color="secondary">
                    Live specimens of Ledgerline’s page-state patterns —
                    every variant here is interactive.
                  </Text>
                </VStack>
              </StackItem>
              {switcher}
            </HStack>
          )}
        </LayoutHeader>
      }
      content={
        <LayoutContent role="main" label="Status and feedback gallery">
          <div style={styles.page}>
            {show('alerts') && <AlertsPanel />}
            {show('empty') && <EmptyStatesPanel />}
            {show('progress') && <ProgressPanel />}
            {show('pagination') && <PaginationPanel isCompact={isCompact} />}
          </div>
        </LayoutContent>
      }
    />
  );
}
