/**
 * Pre-compile the Astryx brand theme to a static CSS file, mirroring what
 * `astryx theme build` produces for the packaged themes. The theme object
 * sets `__built: true`, so the Theme component skips runtime <style>
 * injection entirely — dark/light tokens are plain CSS from first paint,
 * with no injection race.
 *
 * Run after editing demo/src/astryxTheme.js:  pnpm build:theme
 */
import {writeFileSync} from 'node:fs';
import {generateThemeCSS} from '@astryxdesign/core/theme';
import {astryxTheme} from '../demo/src/astryxTheme.js';

const {prose, component} = generateThemeCSS(astryxTheme);
const banner = [
  '/*',
  ' * @generated by scripts/build-theme.mjs — do not edit manually.',
  ' * Source: demo/src/astryxTheme.js',
  ' */',
  '',
  '',
].join('\n');

const sections = [];
if (prose) sections.push(`@layer reset {\n${prose}\n}`);
if (component) sections.push(`@layer astryx-theme {\n${component}\n}`);

const outUrl = new URL('../demo/src/astryxTheme.css', import.meta.url);
writeFileSync(outUrl, banner + sections.join('\n\n') + '\n');
console.log(`Wrote ${outUrl.pathname}`);
