import {lazy} from 'react';
import type {ComponentType, LazyExoticComponent} from 'react';

export type TemplateKind = 'page' | 'block';

export interface TemplateEntry {
  id: string;
  name: string;
  kind: TemplateKind;
  category: string;
  description: string;
  component: LazyExoticComponent<ComponentType>;
  loadSource: () => Promise<string>;
  preload: () => Promise<unknown>;
  requires?: string;
}

// Vite statically analyzes these template-literal dynamic import paths
// (dynamic-import-vars): every templates/*.tsx match becomes its own lazy
// chunk, and the ?raw variant becomes a lazily fetched source module.
const entry = (
  id: string,
  name: string,
  kind: TemplateKind,
  category: string,
  description: string,
  requires?: string,
): TemplateEntry => ({
  id,
  name,
  kind,
  category,
  description,
  component: lazy(() => import(`../../templates/${id}.tsx`)),
  loadSource: () =>
    import(`../../templates/${id}.tsx?raw`).then(
      (m: {default: string}) => m.default,
    ),
  preload: () => import(`../../templates/${id}.tsx`),
  requires,
});

export const templates: TemplateEntry[] = [
  entry(
    'dashboard-executive-summary',
    'Executive Summary Dashboard',
    'page',
    'Dashboard',
    'Hero quarterly-revenue Stat, sparkline trend rail, and regional breakdown table.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'dashboard-widget-grid',
    'Widget Grid Dashboard',
    'page',
    'Dashboard',
    'Configurable grid of mixed widget cards with edit mode and per-widget menus.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'dashboard-split',
    'Split Dashboard',
    'page',
    'Dashboard',
    'Primary time-series chart beside stacked Stat cards and a plan breakdown list.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'dashboard-tabbed',
    'Tabbed Dashboard',
    'page',
    'Dashboard',
    'Header TabList switching Overview / Traffic / Revenue / Quality dashboard views.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'dashboard-filterable',
    'Filterable Dashboard',
    'page',
    'Dashboard',
    'Collapsible filter panel that live-filters KPI Stats, chart, and accounts table.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'kpi-dashboard',
    'KPI Dashboard',
    'page',
    'Dashboard',
    'KPI row, chart widgets, and compact table using the upcoming Stat pattern.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'fleet-node-status',
    'Fleet Node Status',
    'page',
    'Dashboard',
    'Node fleet health: status-square density grid, detail table, and per-user rollup with stacked bars.',
  ),
  entry(
    'activation-funnel-analytics',
    'Activation Funnel Analytics',
    'page',
    'Dashboard',
    'Funnel analytics: stat cards, drop-off callouts, comparison funnel bars, cohort heatmap, velocity strip.',
  ),
  entry(
    'table-inline-expansion',
    'Table with Inline Expansion',
    'page',
    'Table',
    'Endpoint registry table with per-row toggles expanding colSpan detail regions.',
  ),
  entry(
    'table-index-detail',
    'Index/Detail Table',
    'page',
    'Table',
    'Master job table whose selected row populates an end-panel detail pane.',
  ),
  entry(
    'table-split-pane',
    'Split Pane List/Detail',
    'page',
    'Table',
    'Email-client split with a resizable ticket list and conversation detail pane.',
  ),
  entry(
    'table-bulk-actions',
    'Table with Bulk Actions',
    'page',
    'Table',
    'Checkbox selection with a sticky action bar for archive, assign, and delete.',
  ),
  entry(
    'table-tree',
    'Tree / Hierarchical Table',
    'page',
    'Table',
    'Expandable hierarchical file table with depth indenting and tree-aware search.',
  ),
  entry(
    'table-comparison',
    'Comparison Table (Frozen Column)',
    'page',
    'Table',
    'Pricing matrix with a frozen label column and scrollable plan columns.',
  ),
  entry(
    'table-chart',
    'Table with Linked Chart',
    'page',
    'Table',
    'Weekly store chart over its product table with metric switch and row overlay.',
    'Uses a local ChartV2 shim until the lab component is released.',
  ),
  entry(
    'form-page',
    'Form Page',
    'page',
    'Form',
    'Centered single-column settings form with grouped sections and sticky footer.',
  ),
  entry(
    'form-wizard',
    'Form Wizard',
    'page',
    'Form',
    'Multi-step setup wizard with step indicator, per-step validation, and review.',
  ),
  entry(
    'form-modal',
    'Modal Overlay Form',
    'page',
    'Form',
    'Create-project Dialog over a dimmed project table, adding rows on submit.',
  ),
  entry(
    'form-side-sheet',
    'Side Sheet Form',
    'page',
    'Form',
    'Discounts table with a slide-in right sheet for creating or editing a record.',
  ),
  entry(
    'form-inline-edit',
    'Inline Edit Form',
    'page',
    'Form',
    'Label/value rows that swap into inline inputs with per-row Save/Cancel.',
  ),
  entry(
    'auth-sign-in-showcase',
    'Sign-in & Registration Showcase',
    'page',
    'Form',
    'Variant-switched auth showcase in a framed viewport: centered and split-brand sign-in, registration with live strength meter, and a passwordless six-box code flow with real validation and demo error paths.',
  ),
  entry(
    'ai-chat-artifact',
    'AI Chat with Artifact',
    'page',
    'AI Chat',
    'Conversation panel beside a generated-code artifact pane with version tools.',
  ),
  entry(
    'ai-chat-tool-stream',
    'AI Chat with Tool Stream',
    'page',
    'AI Chat',
    'Agent chat with collapsed tool-call piles expanding into per-call status rows.',
  ),
  entry(
    'compaction-inspector',
    'Context Compaction Inspector',
    'page',
    'AI Chat',
    'Compaction event inspector with raw/summary comparison, context tree, and stats.',
  ),
  entry(
    'browser-session-replay',
    'Browser Session Replay',
    'page',
    'AI Chat',
    'Agent browser-session dock with play/scrub transport, frame counter, and a 12-step action timeline.',
  ),
  entry(
    'sub-agent-monitor',
    'Sub-Agent Monitor',
    'page',
    'AI Chat',
    'Docked sub-agent status tray with dismiss/restore management and a modal session transcript.',
  ),
  entry(
    'composer-state-gallery',
    'Composer State Gallery',
    'page',
    'AI Chat',
    'Six frozen states of a power chat composer: slash chip, mentions, queued tray, drag-over, force-stop.',
  ),
  entry(
    'artifact-pin-dock',
    'Artifact Pin Dock',
    'page',
    'AI Chat',
    'Pill tab bar with CI status dots over an artifact viewer, GitHub PR card, and a data-sources run panel.',
  ),
  entry(
    'inbox',
    'Inbox',
    'page',
    'Tools',
    'Three-column mail triage with folder rail, message list, and reading pane.',
  ),
  entry(
    'search-results',
    'Search Results Page',
    'page',
    'Tools',
    'Docs search with facet rail, ranked snippet results, sort, and pagination.',
  ),
  entry(
    'diff-viewer',
    'Diff Compare Viewer',
    'page',
    'Tools',
    'Split/unified code diff with gutters, change stats, and an inline comment thread.',
  ),
  entry(
    'notebook-report',
    'Notebook / Report Page',
    'page',
    'Tools',
    'Analytics notebook of prose, SQL, chart, and table blocks with block toolbars.',
    'Uses a local ChartV2 shim until the lab component is released.',
  ),
  entry(
    'incident-console',
    'Incident Console',
    'page',
    'Tools',
    'On-call response console with dense grouped rows and a resizable inspector.',
  ),
  entry(
    'kanban-board',
    'Kanban Board',
    'page',
    'Tools',
    'Product delivery board with fixed-width columns and accessible move controls.',
  ),
  entry(
    'deployment-detail',
    'Deployment Detail',
    'page',
    'Tools',
    'Deployment status header, metadata grid, and terminal-style build logs.',
    'Uses a local LogStream shim until the lab component is released.',
  ),
  entry(
    'command-palette-launcher',
    'Command Palette Launcher',
    'page',
    'Tools',
    'Command palette over a dimmed workspace with fuzzy matching and grouped results.',
  ),
  entry(
    'file-browser-preview',
    'File Browser with Preview',
    'page',
    'Tools',
    'TreeList file navigator beside a code/rendered preview with version history.',
  ),
  entry(
    'memory-relation-explorer',
    'Memory Relation Explorer',
    'page',
    'Tools',
    'Faceted memory-graph browser: filter rail, relation table with weight bars, and a typed detail panel.',
  ),
  entry(
    'feature-gate-console',
    'Feature Gate Console',
    'page',
    'Tools',
    'Feature-flag ops console: KPI cards, batch rollout controls, CSS bar-chart telemetry, gate table with health dots and switches.',
  ),
  entry(
    'transcript-annotator',
    'Transcript Annotator',
    'page',
    'Tools',
    'Session replay transcript with seven block renderers beside a sticky golden/failure/neutral labeling panel.',
  ),
  entry(
    'mail-compose',
    'Email Compose Window',
    'page',
    'Mail',
    'Docked compose window with recipient chips, formatting toolbar, attachments, and schedule-send.',
  ),
  entry(
    'mail-thread-reader',
    'Conversation Thread Reader',
    'page',
    'Mail',
    'Single-column email thread with collapsed history, trimmed quotes, attachments, and quick replies.',
  ),
  entry(
    'shared-team-inbox',
    'Shared Team Inbox',
    'page',
    'Mail',
    'Multi-agent support mailbox with assignment, SLA chips, internal notes, and collision presence.',
  ),
  entry(
    'scheduled-send-outbox',
    'Scheduled & Snoozed Mail',
    'page',
    'Mail',
    'Time-grouped outbox of scheduled sends and snoozed threads with edit-schedule and send-now actions.',
  ),
  entry(
    'spam-quarantine-console',
    'Spam Quarantine Console',
    'page',
    'Mail',
    'Admin quarantine table with spam-score breakdown panel and bulk release/block actions.',
  ),
  entry(
    'mail-search-builder',
    'Advanced Mail Search',
    'page',
    'Mail',
    'Operator-chip mail search with structured filter builder, saved searches, and grouped results.',
  ),
  entry(
    'newsletter-composer',
    'Newsletter Block Composer',
    'page',
    'Mail',
    'Block-based email builder with palette, live canvas, and per-block settings inspector.',
  ),
  entry(
    'sender-profile-rail',
    'Sender Profile Rail',
    'page',
    'Mail',
    'Open email beside a contextual sender-intelligence rail with history, files, and notes.',
  ),
  entry(
    'settings-extension-catalog',
    'Extension Catalog Settings',
    'page',
    'Settings',
    'Marketplace grid and installed-extension list with scope badges and switches.',
  ),
  entry(
    'settings-secrets-env',
    'Secrets & Environment Settings',
    'page',
    'Settings',
    'Collapsible sections for masked secrets, webhooks, and repos with confirm flows.',
  ),
  entry(
    'scheduled-jobs-manager',
    'Scheduled Jobs Manager',
    'page',
    'Settings',
    'Cron job list with health badges plus a detail pane: execution history, autosave editor, version history.',
  ),
  entry(
    'automation-rule-builder',
    'Automation Rule Builder',
    'page',
    'Settings',
    'Hook list with mini switches and a six-color trigger condition editor plus script file tabs.',
  ),
  entry(
    'onboarding-guided-install',
    'Guided Install Wizard',
    'page',
    'Onboarding',
    'CLI-node setup stepper with copy commands, waiting/connected status strip, and troubleshooting accordions.',
  ),
  entry(
    'cli-pairing-console',
    'CLI Pairing Console',
    'page',
    'Onboarding',
    'CLI daemon console with mascot header and status-line variants beside a four-state device-authorization card.',
  ),
  entry(
    'flashcard-review-session',
    'Flashcard Review Session',
    'page',
    'Learning',
    'Flippable Spanish vocab card with 1–4 grade keys, Again requeueing, deck rail, undo, and a per-grade summary.',
  ),
  entry(
    'quiz-exam-runner',
    'Timed Quiz Runner',
    'page',
    'Learning',
    'Countdown-timed 20-question quiz with jump-anywhere palette chips, flag-for-review, unanswered-submit confirm, and graded review with explanations and missed-only filter.',
  ),
  entry(
    'course-lesson-player',
    'Course Lesson Player',
    'page',
    'Learning',
    'Course player with a collapsible curriculum tree, gated module unlocks, an inline quiz checkpoint, and timestamped personal notes.',
  ),
  entry(
    'read-later-library',
    'Read-Later Library',
    'page',
    'Learning',
    'Three-pane read-later queue with tag rail, keyboard triage list, and a progress-tracking reader pane.',
  ),
  entry(
    'recipe-cook-mode',
    'Recipe Cook Mode',
    'page',
    'Lifestyle',
    'Fraction-aware servings rescaling, one-step-at-a-time cook view with inline amounts, and stackable step-spawned timers.',
  ),
  entry(
    'trip-itinerary-planner',
    'Trip Itinerary Planner',
    'page',
    'Lifestyle',
    'Three-region trip planner: day rail, reorderable activity cards with drag + menu moves, docked ideas tray, inline cost edits with live budget, and remove-with-undo.',
  ),
  entry(
    'trip-expense-splitter',
    'Group Trip Expense Splitter',
    'page',
    'Lifestyle',
    'Group cost splitting: payer-filterable expenses, balance cards, SVG who-owes-whom arrows, equal/percent/exact split editor, and a settle-up checklist.',
  ),
  entry(
    'workout-session-logger',
    'Live Workout Session Logger',
    'page',
    'Lifestyle',
    'Live workout logger: editable set tables with ghost previous values, rest timers, live volume and 1RM stats, substitutions, and a finish-summary diff.',
  ),
  entry(
    'habit-streak-tracker',
    'Habit Streak Tracker',
    'page',
    'Lifestyle',
    'Habit tracker with check-offs, flame streaks, a retro-editable completion heatmap, reorder/archive controls, and a derived stats rail.',
  ),
  entry(
    'day-planner-timeblock',
    'Time-Block Day Planner',
    'page',
    'Lifestyle',
    'Time-block planner: movable, resizable, checkable blocks, a backlog rail with drag scheduling, overlap nudge fixes, and a shutdown panel with journal.',
  ),
  entry(
    'product-list',
    'Product List',
    'page',
    'Content',
    'Faceted catalog browse with filter rail, results toolbar, and product card grid.',
  ),
  entry(
    'profile-page',
    'Profile Page',
    'page',
    'Content',
    'Directory profile with identity header, Stat row, and activity/details tabs.',
    'Uses a local Stat shim until the component is released.',
  ),
  entry(
    'timeline',
    'Timeline',
    'page',
    'Content',
    'Chronological activity feed with sticky date headers and event-type filter.',
  ),
  entry(
    'infinite-scroll-feed',
    'Infinite Scroll Page',
    'page',
    'Content',
    'Filterable single-column post feed ending in a skeleton loading group.',
  ),
  entry(
    'slide-deck-viewer',
    'Slide Deck Viewer',
    'page',
    'Content',
    'PPTX-style viewer: header pager, 112px thumbnail rail, centered 4:3 slide stage from shape fixtures.',
  ),
  entry(
    'slide-editor-canvas',
    'Slide Editor Canvas',
    'page',
    'Content',
    'PPTX-style editor: thumbnail rail, selectable-shape 4:3 canvas with selection ring, and a live format panel.',
  ),
  entry(
    'slide-outline-editor',
    'Slide Outline Editor',
    'page',
    'Content',
    'Text-first outline editor: hierarchical slide/bullet rows with inline editing and a live 4:3 mini preview panel.',
  ),
  entry(
    'slide-presenter-view',
    'Slide Presenter View',
    'page',
    'Content',
    'Speaker console: dark stage with current slide, next preview, zoomable speaker notes, timer chip, and a slide-jump grid.',
  ),
  entry(
    'slide-sorter',
    'Slide Sorter',
    'page',
    'Content',
    'Deck light-table: sectioned thumbnail grid with zoom, reorder, skip, duplicate, and delete.',
  ),
  entry(
    'deck-review-comments',
    'Deck Review Comments',
    'page',
    'Content',
    'Slide deck review: thumbnail rail, marker-annotated 4:3 stage, and a resolvable comment-thread panel.',
  ),
  entry(
    'deck-theme-designer',
    'Deck Theme Designer',
    'page',
    'Content',
    'Deck-wide theme controls (palette, fonts, type scale, masters) driving live slide-master previews.',
  ),
  entry(
    'skill-package-detail',
    'Skill Package Detail',
    'page',
    'Content',
    'Package detail: badge-cluster header, file-tab code browser, and version history with inline per-file diffs.',
  ),
  entry(
    'podcast-episode-player',
    'Podcast Episode Player',
    'page',
    'Media',
    'Episode page with synced transcript, chapter rail, and docked audio player bar.',
  ),
  entry(
    'video-watch-page',
    'Video Watch Page',
    'page',
    'Media',
    'Watch page with mock player chrome, up-next rail, description, and comments.',
  ),
  entry(
    'album-tracklist-player',
    'Album Tracklist Player',
    'page',
    'Media',
    'Album page with hero, track table, and persistent now-playing bar.',
  ),
  entry(
    'streaming-browse-home',
    'Streaming Browse Home',
    'page',
    'Media',
    'Dark browse home with hero billboard and horizontal poster carousels.',
  ),
  entry(
    'live-stream-viewer',
    'Live Stream Viewer',
    'page',
    'Media',
    'Live player with chat rail, viewer stats, and follow/sub actions.',
  ),
  entry(
    'media-asset-pipeline',
    'Media Asset Pipeline',
    'page',
    'Media',
    'Upload/transcode manager with folder tree, status table, and renditions panel.',
  ),
  entry(
    'subtitle-cue-editor',
    'Subtitle Cue Editor',
    'page',
    'Media',
    'Caption cue table synced to a mock player with timing validation.',
  ),
  entry(
    'video-clip-timeline',
    'Video Clip Timeline Editor',
    'page',
    'Media',
    'NLE-style editor with tool rail, program monitor, and multi-track timeline dock.',
  ),
  entry(
    'live-event-chat',
    'Live Event Chat',
    'page',
    'Social',
    'Fast-scrolling event chat with mod actions, pinned slot, slow mode, and reaction bursts.',
  ),
  entry(
    'video-call-layout',
    'Video Call Workspace',
    'page',
    'Social',
    'Meeting surface: speaking-glow tile grid or speaker+filmstrip stage, call control bar, and a chat/roster/breakout side panel.',
  ),
  entry(
    'social-post-composer',
    'Cross-Platform Post Composer',
    'page',
    'Social',
    'Crosspost editor with per-platform countdowns, live truncating previews, and a schedule queue.',
  ),
  entry(
    'doc-suggestion-review',
    'Doc Suggestions & Comments',
    'page',
    'Social',
    'Doc review canvas with per-author tracked changes, accept/reject/batch-undo controls, and an anchored comment rail.',
  ),
  entry(
    'threaded-forum-topic',
    'Threaded Forum Topic',
    'page',
    'Social',
    'Forum topic with a vote-ranked nested reply tree, collapsible subtrees, live sorting, inline branch composers, and a jump-to-accepted-answer rail.',
  ),
  entry(
    'poll-survey-builder',
    'Poll & Survey Builder',
    'page',
    'Social',
    'Two-pane survey builder: question editor with reorder and branch rules beside a live preview with a branch-honoring test mode and results tab.',
  ),
  entry(
    'cart-checkout-flow',
    'Cart & Checkout',
    'page',
    'Commerce',
    'Four-step checkout: qty steppers, working promo code, saved addresses and cards, and a live-totals order-summary rail.',
  ),
  entry(
    'order-tracking',
    'Order Tracking',
    'page',
    'Commerce',
    'Post-purchase parcel tracker: five-stage progress stepper, schematic route strip with truck marker, carrier scan timeline, and an items/address/support panel with return and report-issue flows.',
  ),
  entry(
    'product-detail-gallery',
    'Product Detail',
    'page',
    'Commerce',
    'PDP with gradient gallery stage and thumb rail, color/size selectors, sticky buy box with stepper, spec/shipping collapsibles, rating histogram, and related row.',
  ),
  entry(
    'storefront-browse',
    'Storefront Browse',
    'page',
    'Commerce',
    'Faceted storefront grid with filter rail, applied-filter tokens, wishlist toggles, quick-view dialog, and load-more footer.',
  ),
  entry(
    'pricing-plans',
    'Pricing Plans',
    'page',
    'Commerce',
    'Billing toggle with savings badges, 3-up plan cards, seat estimator, frozen-column feature table, and FAQ collapsibles.',
  ),
  entry(
    'subscription-billing-portal',
    'Billing Portal',
    'page',
    'Commerce',
    'Current-plan card with retention-offer cancel dialog, usage meters vs plan limits, payment methods, and invoice table.',
  ),
  entry(
    'returns-exchange-flow',
    'Returns & Exchange',
    'page',
    'Commerce',
    'Guided return flow: item picker with qty steppers, per-item reasons, refund/credit/exchange resolution, drop-off fees, printable label.',
  ),
  entry(
    'product-quickview-showcase',
    'Product Quickview Showcase',
    'page',
    'Commerce',
    '8-product lookbook grid with three switchable quickview dialog variants (modal, wide with details accordion, slide-over drawer), color/size selectors with per-size stock, notify-me for sold-out sizes, and add-to-bag validation with an animated bag count and confirmation toast.',
  ),
  entry(
    'order-history-page',
    'Order History Page',
    'page',
    'Commerce',
    'Account purchase history: lifetime-stat chips, status/year/search filters, switchable card and expandable-table layouts, buy-again cart, invoice dialog, and tracking deep-link toasts.',
  ),
  entry(
    'storefront-promo-navigation',
    'Storefront Promo & Navigation',
    'page',
    'Commerce',
    'Outdoor-gear storefront landing with a mega-menu store nav, rotating promo bar, category tiles, a countdown sale hero, copyable offer codes, and a switchable incentives band.',
  ),
  entry(
    'product-features-reviews',
    'Product Features & Reviews',
    'page',
    'Commerce',
    'Below-the-fold PDP: switchable feature rows / spec table / diagram accordion plus reviews with filtering histogram, combinable sort, helpful votes, and a validated write-a-review form.',
  ),
  entry(
    'marketing-hero-showcase',
    'Hero Section Showcase',
    'page',
    'Marketing',
    'Four labeled hero variants for a dev-tools SaaS with a scroll-spy jump rail, live light/dark scheme toggle, validating email capture, and toast-firing CTAs.',
  ),
  entry(
    'marketing-cta-banners',
    'CTA & Banner Showcase',
    'page',
    'Marketing',
    'Dismissible top bar, gradient promo with live countdown, floating privacy consent banner, and four CTA variants with email capture, restore toolbar, and toast receipts.',
  ),
  entry(
    'marketing-social-proof',
    'Social Proof Sections',
    'page',
    'Marketing',
    'Testimonial grids, spotlight carousel, masonry wall, CSS-wordmark logo clouds, and count-up stat bands with nine switchable sub-variants.',
  ),
  entry(
    'marketing-faq-contact',
    'FAQ & Contact Sections',
    'page',
    'Marketing',
    'Three FAQ variants (expand-all accordion, category-filtered Q&A grid, offset single-open list with support CTA) plus three contact variants: split form with a schematic office map, centered topic-Selector form, and a support-channels grid — both forms validate and show inline success panels.',
  ),
  entry(
    'marketing-team-sections',
    'Team Section Showcase',
    'page',
    'Marketing',
    'Four switchable team-section variants: photo-card grid, leadership spotlight, collapsible department directory, and a dark hiring band with bio popovers.',
  ),
  entry(
    'marketing-blog-content-sections',
    'Blog & Content Sections',
    'page',
    'Marketing',
    'Five-variant blog/content section library: filterable post-card grid, click-to-swap featured split, date-gutter chronological list, centered prose article with newsletter signup, and a scroll-spied sticky-TOC article.',
  ),
  entry(
    'marketing-header-newsletter',
    'Page Headers & Newsletter Sections',
    'page',
    'Marketing',
    'Four page-header variants (centered eyebrow, dark stat chips, split CTA, toggling filter pills) over three validated newsletter signups with distinct success states and a jump rail.',
  ),
  entry(
    'marketing-footer-collection',
    'Footer Collection',
    'page',
    'Marketing',
    'Five Relay footer variants — sitemap with validating newsletter form, slim social row, dark mega-footer with language Selector and status chip, centered minimal, app-style legal/locale-currency row — previewed against a light/dark page-bottom toggle with a live demo-state readout.',
  ),
  entry(
    'error-404-collection',
    '404 & Error Page Collection',
    'page',
    'Marketing',
    'Four framed error screens — minimal 404, lost-robot search over fixture routes, helpful links, and a 5xx incident with retry spinner — behind a variant switcher and 404/500 code toggle.',
  ),
  entry(
    'company-about-page',
    'Company About Page Example',
    'page',
    'Marketing',
    'Company about page with scroll-spy subnav, count-up stats band, alternating milestone timeline, values grid, leadership bio popovers, and a careers CTA panel.',
  ),
  entry(
    'marketing-feature-sections',
    'Feature Section Showcase',
    'page',
    'Marketing',
    'Four feature-section variants — expandable icon grid, scroll-reveal alternating rows, 2x2 grid with tabbed screenshot panel, and a dark spotlight with copyable code card — behind a variant switcher.',
  ),
  entry(
    'marketing-bento-grid',
    'Bento Grid Showcase',
    'page',
    'Marketing',
    'Three bento-section variants — asymmetric 3-column grid with latency hero, dark 5-cell panel with schematic mocks, compact big-number stats grid — with density toggle and scroll-spy jump rail.',
  ),
  entry(
    'marketing-navbar-flyouts',
    'Marketing Navbars & Flyout Menus',
    'page',
    'Marketing',
    'Three framed navbar variants — light centered, dark solid-on-scroll with mega menu, two-tier eyebrow — each with click-open flyouts, a simulated-scroll slider, and 375px hamburger-drawer previews.',
  ),
  entry(
    'saas-landing-page',
    'SaaS Landing Page Example',
    'page',
    'Marketing',
    'Full landing page: dismissible banner, sticky navbar with flyout and scroll-spy anchors, split hero with email capture, feature rows, bento band, testimonial, pricing teaser, FAQ, and sitemap footer.',
  ),
  entry(
    'form-controls-gallery',
    'Form Controls Gallery',
    'page',
    'UI Kit',
    'Section rail plus eight live control-family panels — input groups, selects, textareas, radios, indeterminate checkboxes, toggles, comboboxes, action panels — each with a JSON state readout and a reset-all.',
  ),
  entry(
    'ui-elements-gallery',
    'UI Elements Gallery',
    'page',
    'UI Kit',
    'Five interactive panels of core atoms — avatars, badges, buttons, button groups, dropdown menus — each variant with a copy-ready props strip.',
  ),
  entry(
    'status-feedback-gallery',
    'Status & Feedback Gallery',
    'page',
    'UI Kit',
    'Four-panel UI-kit gallery of live page-state patterns — dismissable alert banners with a restore tray, self-resolving empty states, a slider-driven progress trio plus checkout stepper, and four pagination idioms windowing a fixture invoice list.',
  ),
  entry(
    'layout-primitives-gallery',
    'Layout Primitives Gallery',
    'page',
    'UI Kit',
    'Five-panel structural building-block gallery on a dotted baseline: containers with a live viewport slider, dense/comfortable card variants, sticky-header lists, recursive media threads, and divider patterns with copyable caption chips.',
  ),
  entry(
    'headings-lists-gallery',
    'Headings & List Patterns Gallery',
    'page',
    'UI Kit',
    'Five-panel headings and list patterns gallery — page/card/section headings, description lists, and stacked lists — with a scroll-spying rail, inline edits, filter tabs, and a bulk-select bar.',
  ),
  entry(
    'calendar-month-grid',
    'Month Calendar',
    'page',
    'Calendar',
    'Month day grid with category-colored event chips, filter legend toggles, and a selected-day panel.',
  ),
  entry(
    'calendar-week-agenda',
    'Week Agenda',
    'page',
    'Calendar',
    'Week time-grid with side-by-side overlap columns, an all-day row, a fixed now line, and a click-to-open event detail panel.',
  ),
  entry(
    'booking-availability-picker',
    'Booking Picker',
    'page',
    'Calendar',
    'Calendly-style scheduler: host rail, availability-dot date strip, timezone-shifted slot grid, and confirm form with success state.',
  ),
  entry(
    'event-detail-rsvp',
    'Event RSVP',
    'page',
    'Calendar',
    'Gradient event hero with a sticky Going/Maybe/Cannot-go RSVP card, guest stepper, attendee counts, agenda, schematic map, and discussion.',
  ),
  entry(
    'team-scheduler',
    'Team Scheduler',
    'page',
    'Calendar',
    'Cross-timezone meeting matrix: member-by-hour free/busy cells, a sliding slot highlight, ranked best-slot cards, and a local-times invite summary.',
  ),
  entry(
    'time-off-planner',
    'Time-Off Planner',
    'page',
    'Calendar',
    'PTO balance cards with accrual notes, business-day request form, team absence strip, and approve/deny requests table.',
  ),
  entry(
    'transactions-ledger',
    'Transactions Ledger',
    'page',
    'Finance',
    'Running-balance account register with pending/posted groups, reconcile checkboxes feeding a sticky summary bar, filters, and a transaction detail panel.',
  ),
  entry(
    'invoice-builder',
    'Invoice Builder',
    'page',
    'Finance',
    'Split invoice form with a line-item editor beside a live paper preview computing subtotal, tax, and discount.',
  ),
  entry(
    'expense-approval-queue',
    'Expense Approvals',
    'page',
    'Finance',
    'Approvals inbox: flagged expense-report queue with bulk-approve for clean reports, line-item detail with receipt tiles, and reject-with-required-comment.',
  ),
  entry(
    'budget-tracker',
    'Budget Tracker',
    'page',
    'Finance',
    'Envelope budgeting: month switcher, over-budget alert envelopes, safe-to-spend math, CSS-only burn-down strip, and inline per-envelope transactions.',
  ),
  entry(
    'payout-statements',
    'Payout Statements',
    'page',
    'Finance',
    'Period payout statements with a gross-to-net waterfall detail pane, destination accounts, and CSV/PDF export toasts.',
  ),
  entry(
    'portfolio-holdings',
    'Portfolio Holdings',
    'page',
    'Finance',
    'Signed-summary portfolio: conic-gradient allocation donut, holdings table with lot-level detail panel, and watchlist rail.',
  ),
  entry(
    'crm-contact-record',
    'CRM Contact Record',
    'page',
    'Business',
    '360° contact record: clickable lifecycle stepper, inline-editable field groups, typed Note/Call/Email/Task composer over a filterable timeline, and a deals rail with live open-task count.',
  ),
  entry(
    'fleet-dispatch-board',
    'Fleet Dispatch Board',
    'page',
    'Business',
    'Dispatch queue beside driver time lanes with animated load meters, conflict-override drops, and a route-sequence rail.',
  ),
  entry(
    'org-chart-explorer',
    'Org Chart Explorer',
    'page',
    'Business',
    'Pannable org-chart canvas with SVG edges, collapsible branches, search centering, an inline-edit rail, and confirm-guarded re-parenting with undo.',
  ),
  entry(
    'review-cycle-calibration',
    'Performance Review Calibration',
    'page',
    'Business',
    '9-box calibration grid with draggable reviewee tiles, a live rating histogram with over-target flags, inline rating edits, and finalize/reset controls.',
  ),
  entry(
    'esignature-envelope-flow',
    'E-Signature Envelope Builder',
    'page',
    'Business',
    'Four-step envelope wizard with click-to-place signature fields, live signing-order renumbering, and a simulated delivery tracker.',
  ),
  entry(
    'roadmap-gantt',
    'Roadmap Gantt',
    'page',
    'Planning',
    'Quarter roadmap: zoomable quarter/month axis, team swimlanes with progress-filled bars, milestone diamonds, and SVG dependency arrows.',
  ),
  entry(
    'sprint-board-backlog',
    'Sprint Board',
    'page',
    'Planning',
    'Sprint board with a backlog rail, capacity meter, and accessible story moves.',
  ),
  entry(
    'issue-detail',
    'Issue Detail',
    'page',
    'Planning',
    'Ticket page with editable status, sub-task progress, CI-dotted linked PRs, a metadata rail, and threaded activity.',
  ),
  entry(
    'okr-tree',
    'OKR Tree',
    'page',
    'Planning',
    'Objectives-to-key-results tree: quarter selector, confidence-colored progress rows, at-risk filter, check-in history panel.',
  ),
  entry(
    'release-train-overview',
    'Release Train',
    'page',
    'Planning',
    'Horizontal release-train rail with per-train feature flags, blocking issues, go/no-go sign-offs, and a cherry-pick approval queue.',
  ),
  entry(
    'milestone-burnup',
    'Milestone Burnup',
    'page',
    'Planning',
    'Delivery burnup: stepped scope line over completed area with forecast band, tappable scope-change markers, KPI stats, and expandable milestone table.',
  ),
  entry(
    'coding-terminal-workspace',
    'Terminal Workspace',
    'page',
    'Coding',
    'Multi-tab terminal: session sidebar with activity dots, typed-record scrollback, split panes, scrollback search, and a mod+K palette.',
  ),
  entry(
    'repl-playground',
    'REPL Playground',
    'page',
    'Coding',
    'Two-pane code playground with a tokenized editor, example snippets, and a filterable run console.',
  ),
  entry(
    'code-review-diff-queue',
    'Review Queue',
    'page',
    'Coding',
    'Multi-file PR review with a file tree, viewed progress, inline threads, and a verdict dialog.',
  ),
  entry(
    'git-branch-graph',
    'Branch Graph',
    'page',
    'Coding',
    'Lane-drawn commit DAG with colored rails, ref badges, branch filter, diffstat detail panel, and a compare-range mode.',
  ),
  entry(
    'test-runner-console',
    'Test Runner',
    'page',
    'Coding',
    'Suite tree with per-describe counts, filterable run stream with spinner rows, and a failure panel with stack trace and expected/received diff.',
  ),
  entry(
    'editor-file-tabs-shell',
    'Editor Shell',
    'page',
    'Coding',
    'IDE frame: explorer rail with git-status dots, dirty-dot tab strip, token-tinted code viewport with minimap, jump-to-line problems panel, and status bar.',
  ),
  entry(
    'sql-query-workbench',
    'SQL Query Workbench',
    'page',
    'Data',
    'Database IDE with a connection picker, expandable schema tree, tabbed SQL editors, and a sortable, filterable result grid with canned query results.',
  ),
  entry(
    'schema-designer-erd',
    'Schema Designer (ERD)',
    'page',
    'Data',
    'Pannable ERD canvas of draggable table cards with FK lines, in-card column editing, live DDL panel, and a validation strip.',
  ),
  entry(
    'dag-run-visualizer',
    'Pipeline DAG Run Visualizer',
    'page',
    'Data',
    'Airflow-style orchestration console: run rail, state-colored task DAG, run-history grid, retry/mark-success cascades, and backfill.',
  ),
  entry(
    'data-quality-monitors',
    'Data Quality Monitor Console',
    'page',
    'Data',
    'Pass/warn/fail chip filters, monitor table with SVG sparklines, threshold-slider detail drawer with violation band, snooze/mute section, and incident timeline.',
  ),
  entry(
    'data-catalog-lineage',
    'Data Catalog & Lineage Explorer',
    'page',
    'Data',
    'Dataset catalog with search and tag rail, editable descriptions and tags, pinnable columns, and a clickable SVG lineage graph with column-level edges.',
  ),
  entry(
    'query-plan-profiler',
    'Query Performance Profiler',
    'page',
    'Data',
    'Slow-query profiler: cost-ranked query rail, collapsible EXPLAIN tree with cost bars, index suggestions that swap in optimized plans, and plan compare.',
  ),
  entry(
    'shell-left-sidebar',
    'Shell - Left Sidebar',
    'page',
    'Shell',
    'AppShell with a collapsible grouped SideNav beside a placeholder page.',
  ),
  entry(
    'shell-top-nav',
    'Shell - Top Nav',
    'page',
    'Shell',
    'Horizontal TopNav bar over a full-width content area with a placeholder slot.',
  ),
  entry(
    'shell-top-nav-sidebar',
    'Shell - Top Nav + Left Sidebar',
    'page',
    'Shell',
    'Global TopNav plus a contextual SideNav that swaps groups per active section.',
  ),
  entry(
    'shell-breadcrumb',
    'Shell - Breadcrumb Driven',
    'page',
    'Shell',
    'Drill-down shell where a deep Breadcrumbs trail carries all hierarchy.',
  ),
  entry(
    'messaging-shell',
    'Messaging Shell',
    'page',
    'Shell',
    'Four-column messaging frame with rail, channel list, stream, and thread panel.',
  ),
  entry(
    'notification-center',
    'Notification Center',
    'page',
    'Shell',
    'Navbar bell with unread badge, pinned-open 320px notification popover, corner toast, and state variants.',
  ),
  entry(
    'logs-explorer',
    'Logs Explorer',
    'page',
    'Monitoring',
    'Facet rail, PowerSearch filters, live-tail switch, and expandable log stream.',
    'Uses a local LogStream shim until the lab component is released.',
  ),
  entry(
    'operations-dashboard',
    'Operations Dashboard',
    'page',
    'Operations',
    'Starter dashboard for this package with KPI cards, review queue, and actions.',
  ),
  entry(
    'cloud-cost-analyzer',
    'Cloud Cost Analyzer',
    'page',
    'Operations',
    'Group-by-driven stacked spend chart with drill-down ledger, anomaly popover, and what-if commitment slider.',
  ),
  entry(
    'api-request-explorer',
    'API Request Explorer',
    'page',
    'Operations',
    'Postman-style API client: collection tree with dirty dots, env-variable request builder, canned JSON responses, and a restoring history rail.',
  ),
  entry(
    'webhook-delivery-debugger',
    'Webhook Delivery Debugger',
    'page',
    'Operations',
    'Endpoint health rail, filterable delivery feed, and JSON-tree detail pane with replay and retry-policy drawer.',
  ),
  entry(
    'cert-key-inventory',
    'Certificate & Key Inventory',
    'page',
    'Operations',
    'TLS lifecycle console: filterable cert table and expiry timeline views, a chain-and-deployments drawer, and a rotate wizard with live recompute and undo.',
  ),
  entry(
    'kpi-strip',
    'KPI Strip',
    'block',
    'Operations',
    'Compact metric card strip for dashboard headers.',
  ),
  entry(
    'codeblock-terminal',
    'Code - Terminal',
    'block',
    'Code',
    'Dark terminal-style CodeBlock with a syntax theme wrapper.',
  ),
];
