import {lazy} from 'react';
import type {ComponentType, LazyExoticComponent} from 'react';

export type TemplateKind = 'page' | 'block';

export interface TemplateEntry {
  id: string;
  name: string;
  kind: TemplateKind;
  category: string;
  description: string;
  component: LazyExoticComponent<ComponentType>;
  loadSource: () => Promise<string>;
  preload: () => Promise<unknown>;
  requires?: string;
}

// Vite statically analyzes these template-literal dynamic import paths
// (dynamic-import-vars): every templates/*.tsx match becomes its own lazy
// chunk, and the ?raw variant becomes a lazily fetched source module.
const entry = (
  id: string,
  name: string,
  kind: TemplateKind,
  category: string,
  description: string,
  requires?: string,
): TemplateEntry => ({
  id,
  name,
  kind,
  category,
  description,
  component: lazy(() => import(`../../templates/${id}.tsx`)),
  loadSource: () =>
    import(`../../templates/${id}.tsx?raw`).then(
      (m: {default: string}) => m.default,
    ),
  preload: () => import(`../../templates/${id}.tsx`),
  requires,
});

export const templates: TemplateEntry[] = [
  entry(
    'dashboard-executive-summary',
    'Executive Summary Dashboard',
    'page',
    'Dashboard',
    'Hero quarterly-revenue Stat, sparkline trend rail, and regional breakdown table.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'dashboard-widget-grid',
    'Widget Grid Dashboard',
    'page',
    'Dashboard',
    'Configurable grid of mixed widget cards with edit mode and per-widget menus.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'dashboard-split',
    'Split Dashboard',
    'page',
    'Dashboard',
    'Primary time-series chart beside stacked Stat cards and a plan breakdown list.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'dashboard-tabbed',
    'Tabbed Dashboard',
    'page',
    'Dashboard',
    'Header TabList switching Overview / Traffic / Revenue / Quality dashboard views.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'dashboard-filterable',
    'Filterable Dashboard',
    'page',
    'Dashboard',
    'Collapsible filter panel that live-filters KPI Stats, chart, and accounts table.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'kpi-dashboard',
    'KPI Dashboard',
    'page',
    'Dashboard',
    'KPI row, chart widgets, and compact table using the upcoming Stat pattern.',
    'Uses local demo shims until Stat and ChartV2 are released.',
  ),
  entry(
    'fleet-node-status',
    'Fleet Node Status',
    'page',
    'Dashboard',
    'Node fleet health: status-square density grid, detail table, and per-user rollup with stacked bars.',
  ),
  entry(
    'activation-funnel-analytics',
    'Activation Funnel Analytics',
    'page',
    'Dashboard',
    'Funnel analytics: stat cards, drop-off callouts, comparison funnel bars, cohort heatmap, velocity strip.',
  ),
  entry(
    'table-inline-expansion',
    'Table with Inline Expansion',
    'page',
    'Table',
    'Endpoint registry table with per-row toggles expanding colSpan detail regions.',
  ),
  entry(
    'table-index-detail',
    'Index/Detail Table',
    'page',
    'Table',
    'Master job table whose selected row populates an end-panel detail pane.',
  ),
  entry(
    'table-split-pane',
    'Split Pane List/Detail',
    'page',
    'Table',
    'Email-client split with a resizable ticket list and conversation detail pane.',
  ),
  entry(
    'table-bulk-actions',
    'Table with Bulk Actions',
    'page',
    'Table',
    'Checkbox selection with a sticky action bar for archive, assign, and delete.',
  ),
  entry(
    'table-tree',
    'Tree / Hierarchical Table',
    'page',
    'Table',
    'Expandable hierarchical file table with depth indenting and tree-aware search.',
  ),
  entry(
    'table-comparison',
    'Comparison Table (Frozen Column)',
    'page',
    'Table',
    'Pricing matrix with a frozen label column and scrollable plan columns.',
  ),
  entry(
    'table-chart',
    'Table with Linked Chart',
    'page',
    'Table',
    'Weekly store chart over its product table with metric switch and row overlay.',
    'Uses a local ChartV2 shim until the lab component is released.',
  ),
  entry(
    'form-page',
    'Form Page',
    'page',
    'Form',
    'Centered single-column settings form with grouped sections and sticky footer.',
  ),
  entry(
    'form-wizard',
    'Form Wizard',
    'page',
    'Form',
    'Multi-step setup wizard with step indicator, per-step validation, and review.',
  ),
  entry(
    'form-modal',
    'Modal Overlay Form',
    'page',
    'Form',
    'Create-project Dialog over a dimmed project table, adding rows on submit.',
  ),
  entry(
    'form-side-sheet',
    'Side Sheet Form',
    'page',
    'Form',
    'Discounts table with a slide-in right sheet for creating or editing a record.',
  ),
  entry(
    'form-inline-edit',
    'Inline Edit Form',
    'page',
    'Form',
    'Label/value rows that swap into inline inputs with per-row Save/Cancel.',
  ),
  entry(
    'auth-sign-in-showcase',
    'Sign-in & Registration Showcase',
    'page',
    'Form',
    'Variant-switched auth showcase in a framed viewport: centered and split-brand sign-in, registration with live strength meter, and a passwordless six-box code flow with real validation and demo error paths.',
  ),
  entry(
    'ai-chat-artifact',
    'AI Chat with Artifact',
    'page',
    'AI Chat',
    'Conversation panel beside a generated-code artifact pane with version tools.',
  ),
  entry(
    'ai-chat-tool-stream',
    'AI Chat with Tool Stream',
    'page',
    'AI Chat',
    'Agent chat with collapsed tool-call piles expanding into per-call status rows.',
  ),
  entry(
    'compaction-inspector',
    'Context Compaction Inspector',
    'page',
    'AI Chat',
    'Compaction event inspector with raw/summary comparison, context tree, and stats.',
  ),
  entry(
    'browser-session-replay',
    'Browser Session Replay',
    'page',
    'AI Chat',
    'Agent browser-session dock with play/scrub transport, frame counter, and a 12-step action timeline.',
  ),
  entry(
    'sub-agent-monitor',
    'Sub-Agent Monitor',
    'page',
    'AI Chat',
    'Docked sub-agent status tray with dismiss/restore management and a modal session transcript.',
  ),
  entry(
    'composer-state-gallery',
    'Composer State Gallery',
    'page',
    'AI Chat',
    'Six frozen states of a power chat composer: slash chip, mentions, queued tray, drag-over, force-stop.',
  ),
  entry(
    'artifact-pin-dock',
    'Artifact Pin Dock',
    'page',
    'AI Chat',
    'Pill tab bar with CI status dots over an artifact viewer, GitHub PR card, and a data-sources run panel.',
  ),
  entry(
    'inbox',
    'Inbox',
    'page',
    'Tools',
    'Three-column mail triage with folder rail, message list, and reading pane.',
  ),
  entry(
    'search-results',
    'Search Results Page',
    'page',
    'Tools',
    'Docs search with facet rail, ranked snippet results, sort, and pagination.',
  ),
  entry(
    'diff-viewer',
    'Diff Compare Viewer',
    'page',
    'Tools',
    'Split/unified code diff with gutters, change stats, and an inline comment thread.',
  ),
  entry(
    'notebook-report',
    'Notebook / Report Page',
    'page',
    'Tools',
    'Analytics notebook of prose, SQL, chart, and table blocks with block toolbars.',
    'Uses a local ChartV2 shim until the lab component is released.',
  ),
  entry(
    'incident-console',
    'Incident Console',
    'page',
    'Tools',
    'On-call response console with dense grouped rows and a resizable inspector.',
  ),
  entry(
    'kanban-board',
    'Kanban Board',
    'page',
    'Tools',
    'Product delivery board with fixed-width columns and accessible move controls.',
  ),
  entry(
    'deployment-detail',
    'Deployment Detail',
    'page',
    'Tools',
    'Deployment status header, metadata grid, and terminal-style build logs.',
    'Uses a local LogStream shim until the lab component is released.',
  ),
  entry(
    'command-palette-launcher',
    'Command Palette Launcher',
    'page',
    'Tools',
    'Command palette over a dimmed workspace with fuzzy matching and grouped results.',
  ),
  entry(
    'file-browser-preview',
    'File Browser with Preview',
    'page',
    'Tools',
    'TreeList file navigator beside a code/rendered preview with version history.',
  ),
  entry(
    'memory-relation-explorer',
    'Memory Relation Explorer',
    'page',
    'Tools',
    'Faceted memory-graph browser: filter rail, relation table with weight bars, and a typed detail panel.',
  ),
  entry(
    'feature-gate-console',
    'Feature Gate Console',
    'page',
    'Tools',
    'Feature-flag ops console: KPI cards, batch rollout controls, CSS bar-chart telemetry, gate table with health dots and switches.',
  ),
  entry(
    'transcript-annotator',
    'Transcript Annotator',
    'page',
    'Tools',
    'Session replay transcript with seven block renderers beside a sticky golden/failure/neutral labeling panel.',
  ),
  entry(
    'mail-compose',
    'Email Compose Window',
    'page',
    'Mail',
    'Docked compose window with recipient chips, formatting toolbar, attachments, and schedule-send.',
  ),
  entry(
    'mail-thread-reader',
    'Conversation Thread Reader',
    'page',
    'Mail',
    'Single-column email thread with collapsed history, trimmed quotes, attachments, and quick replies.',
  ),
  entry(
    'shared-team-inbox',
    'Shared Team Inbox',
    'page',
    'Mail',
    'Multi-agent support mailbox with assignment, SLA chips, internal notes, and collision presence.',
  ),
  entry(
    'scheduled-send-outbox',
    'Scheduled & Snoozed Mail',
    'page',
    'Mail',
    'Time-grouped outbox of scheduled sends and snoozed threads with edit-schedule and send-now actions.',
  ),
  entry(
    'spam-quarantine-console',
    'Spam Quarantine Console',
    'page',
    'Mail',
    'Admin quarantine table with spam-score breakdown panel and bulk release/block actions.',
  ),
  entry(
    'mail-search-builder',
    'Advanced Mail Search',
    'page',
    'Mail',
    'Operator-chip mail search with structured filter builder, saved searches, and grouped results.',
  ),
  entry(
    'newsletter-composer',
    'Newsletter Block Composer',
    'page',
    'Mail',
    'Block-based email builder with palette, live canvas, and per-block settings inspector.',
  ),
  entry(
    'sender-profile-rail',
    'Sender Profile Rail',
    'page',
    'Mail',
    'Open email beside a contextual sender-intelligence rail with history, files, and notes.',
  ),
  entry(
    'settings-extension-catalog',
    'Extension Catalog Settings',
    'page',
    'Settings',
    'Marketplace grid and installed-extension list with scope badges and switches.',
  ),
  entry(
    'settings-secrets-env',
    'Secrets & Environment Settings',
    'page',
    'Settings',
    'Collapsible sections for masked secrets, webhooks, and repos with confirm flows.',
  ),
  entry(
    'scheduled-jobs-manager',
    'Scheduled Jobs Manager',
    'page',
    'Settings',
    'Cron job list with health badges plus a detail pane: execution history, autosave editor, version history.',
  ),
  entry(
    'automation-rule-builder',
    'Automation Rule Builder',
    'page',
    'Settings',
    'Hook list with mini switches and a six-color trigger condition editor plus script file tabs.',
  ),
  entry(
    'onboarding-guided-install',
    'Guided Install Wizard',
    'page',
    'Onboarding',
    'CLI-node setup stepper with copy commands, waiting/connected status strip, and troubleshooting accordions.',
  ),
  entry(
    'cli-pairing-console',
    'CLI Pairing Console',
    'page',
    'Onboarding',
    'CLI daemon console with mascot header and status-line variants beside a four-state device-authorization card.',
  ),
  entry(
    'flashcard-review-session',
    'Flashcard Review Session',
    'page',
    'Learning',
    'Flippable Spanish vocab card with 1–4 grade keys, Again requeueing, deck rail, undo, and a per-grade summary.',
  ),
  entry(
    'quiz-exam-runner',
    'Timed Quiz Runner',
    'page',
    'Learning',
    'Countdown-timed 20-question quiz with jump-anywhere palette chips, flag-for-review, unanswered-submit confirm, and graded review with explanations and missed-only filter.',
  ),
  entry(
    'course-lesson-player',
    'Course Lesson Player',
    'page',
    'Learning',
    'Course player with a collapsible curriculum tree, gated module unlocks, an inline quiz checkpoint, and timestamped personal notes.',
  ),
  entry(
    'read-later-library',
    'Read-Later Library',
    'page',
    'Learning',
    'Three-pane read-later queue with tag rail, keyboard triage list, and a progress-tracking reader pane.',
  ),
  entry(
    'recipe-cook-mode',
    'Recipe Cook Mode',
    'page',
    'Lifestyle',
    'Fraction-aware servings rescaling, one-step-at-a-time cook view with inline amounts, and stackable step-spawned timers.',
  ),
  entry(
    'trip-itinerary-planner',
    'Trip Itinerary Planner',
    'page',
    'Lifestyle',
    'Three-region trip planner: day rail, reorderable activity cards with drag + menu moves, docked ideas tray, inline cost edits with live budget, and remove-with-undo.',
  ),
  entry(
    'trip-expense-splitter',
    'Group Trip Expense Splitter',
    'page',
    'Lifestyle',
    'Group cost splitting: payer-filterable expenses, balance cards, SVG who-owes-whom arrows, equal/percent/exact split editor, and a settle-up checklist.',
  ),
  entry(
    'workout-session-logger',
    'Live Workout Session Logger',
    'page',
    'Lifestyle',
    'Live workout logger: editable set tables with ghost previous values, rest timers, live volume and 1RM stats, substitutions, and a finish-summary diff.',
  ),
  entry(
    'habit-streak-tracker',
    'Habit Streak Tracker',
    'page',
    'Lifestyle',
    'Habit tracker with check-offs, flame streaks, a retro-editable completion heatmap, reorder/archive controls, and a derived stats rail.',
  ),
  entry(
    'day-planner-timeblock',
    'Time-Block Day Planner',
    'page',
    'Lifestyle',
    'Time-block planner: movable, resizable, checkable blocks, a backlog rail with drag scheduling, overlap nudge fixes, and a shutdown panel with journal.',
  ),
  entry(
    'product-list',
    'Product List',
    'page',
    'Content',
    'Faceted catalog browse with filter rail, results toolbar, and product card grid.',
  ),
  entry(
    'profile-page',
    'Profile Page',
    'page',
    'Content',
    'Directory profile with identity header, Stat row, and activity/details tabs.',
    'Uses a local Stat shim until the component is released.',
  ),
  entry(
    'timeline',
    'Timeline',
    'page',
    'Content',
    'Chronological activity feed with sticky date headers and event-type filter.',
  ),
  entry(
    'infinite-scroll-feed',
    'Infinite Scroll Page',
    'page',
    'Content',
    'Filterable single-column post feed ending in a skeleton loading group.',
  ),
  entry(
    'slide-deck-viewer',
    'Slide Deck Viewer',
    'page',
    'Content',
    'PPTX-style viewer: header pager, 112px thumbnail rail, centered 4:3 slide stage from shape fixtures.',
  ),
  entry(
    'slide-editor-canvas',
    'Slide Editor Canvas',
    'page',
    'Content',
    'PPTX-style editor: thumbnail rail, selectable-shape 4:3 canvas with selection ring, and a live format panel.',
  ),
  entry(
    'slide-outline-editor',
    'Slide Outline Editor',
    'page',
    'Content',
    'Text-first outline editor: hierarchical slide/bullet rows with inline editing and a live 4:3 mini preview panel.',
  ),
  entry(
    'slide-presenter-view',
    'Slide Presenter View',
    'page',
    'Content',
    'Speaker console: dark stage with current slide, next preview, zoomable speaker notes, timer chip, and a slide-jump grid.',
  ),
  entry(
    'slide-sorter',
    'Slide Sorter',
    'page',
    'Content',
    'Deck light-table: sectioned thumbnail grid with zoom, reorder, skip, duplicate, and delete.',
  ),
  entry(
    'deck-review-comments',
    'Deck Review Comments',
    'page',
    'Content',
    'Slide deck review: thumbnail rail, marker-annotated 4:3 stage, and a resolvable comment-thread panel.',
  ),
  entry(
    'deck-theme-designer',
    'Deck Theme Designer',
    'page',
    'Content',
    'Deck-wide theme controls (palette, fonts, type scale, masters) driving live slide-master previews.',
  ),
  entry(
    'skill-package-detail',
    'Skill Package Detail',
    'page',
    'Content',
    'Package detail: badge-cluster header, file-tab code browser, and version history with inline per-file diffs.',
  ),
  entry(
    'podcast-episode-player',
    'Podcast Episode Player',
    'page',
    'Media',
    'Episode page with synced transcript, chapter rail, and docked audio player bar.',
  ),
  entry(
    'video-watch-page',
    'Video Watch Page',
    'page',
    'Media',
    'Watch page with mock player chrome, up-next rail, description, and comments.',
  ),
  entry(
    'album-tracklist-player',
    'Album Tracklist Player',
    'page',
    'Media',
    'Album page with hero, track table, and persistent now-playing bar.',
  ),
  entry(
    'streaming-browse-home',
    'Streaming Browse Home',
    'page',
    'Media',
    'Dark browse home with hero billboard and horizontal poster carousels.',
  ),
  entry(
    'live-stream-viewer',
    'Live Stream Viewer',
    'page',
    'Media',
    'Live player with chat rail, viewer stats, and follow/sub actions.',
  ),
  entry(
    'media-asset-pipeline',
    'Media Asset Pipeline',
    'page',
    'Media',
    'Upload/transcode manager with folder tree, status table, and renditions panel.',
  ),
  entry(
    'subtitle-cue-editor',
    'Subtitle Cue Editor',
    'page',
    'Media',
    'Caption cue table synced to a mock player with timing validation.',
  ),
  entry(
    'video-clip-timeline',
    'Video Clip Timeline Editor',
    'page',
    'Media',
    'NLE-style editor with tool rail, program monitor, and multi-track timeline dock.',
  ),
  entry(
    'video-editor-project-browser',
    'Project Browser',
    'page',
    'Video Studio',
    'NLE front door: recent-sequence rail, poster-card project grid, sequences table, and a new-project overlay with format presets.',
  ),
  entry(
    'video-editor-workspace',
    'NLE Editing Workspace',
    'page',
    'Video Studio',
    'Full editing cockpit: tool rail, program monitor, transport, mini inspector strip, and a four-track timeline dock with snapping playhead.',
  ),
  entry(
    'video-editor-media-bin',
    'Media Bin',
    'page',
    'Video Studio',
    'Project media browser with bin TreeList, import dropzone, tag/sort filters, and grid/list asset tiles with hover-card previews.',
  ),
  entry(
    'video-editor-effects-panel',
    'Effects Panel',
    'page',
    'Video Studio',
    'Effects browser with categorized catalog and favorites beside a reorderable applied-effect stack with expanded parameter rows.',
  ),
  entry(
    'video-editor-color-grading',
    'Color Grading Suite',
    'page',
    'Video Studio',
    'DaVinci-style color page: shot bin, LUT viewer with reference wipe, waveform/vectorscope panel, and lift/gamma/gain trackball wheels.',
  ),
  entry(
    'video-editor-audio-mixer',
    'Audio Mixer Console',
    'page',
    'Video Studio',
    'DAW-style console of channel and bus strips — faders, meters, pan knobs, mute/solo — with a limiter master strip and channel inspector.',
  ),
  entry(
    'video-editor-titles-designer',
    'Titles Designer',
    'page',
    'Video Studio',
    'Titles and graphics station: layer panel, safe-area canvas, full type-stack inspector with animation presets, and a lower-thirds gallery dock.',
  ),
  entry(
    'video-editor-keyframe-editor',
    'Keyframe Curve Editor',
    'page',
    'Video Studio',
    'Property-animation graph editor: property lanes with diamond keyframes, an SVG bezier curve lane with draggable handles, and easing presets.',
  ),
  entry(
    'video-editor-clip-inspector',
    'Clip Inspector',
    'page',
    'Video Studio',
    'Per-clip attribute editor with Video/Speed/Audio tabs, drag-to-scrub transform fields, a speed-ramp graph, and a live-preview thumbnail.',
  ),
  entry(
    'video-editor-export-queue',
    'Export Queue',
    'page',
    'Video Studio',
    'Delivery surface: export preset cards, custom-settings accordion, live export summary, and a render-queue dock with progress and retries.',
  ),
  entry(
    'live-event-chat',
    'Live Event Chat',
    'page',
    'Social',
    'Fast-scrolling event chat with mod actions, pinned slot, slow mode, and reaction bursts.',
  ),
  entry(
    'video-call-layout',
    'Video Call Workspace',
    'page',
    'Social',
    'Meeting surface: speaking-glow tile grid or speaker+filmstrip stage, call control bar, and a chat/roster/breakout side panel.',
  ),
  entry(
    'social-post-composer',
    'Cross-Platform Post Composer',
    'page',
    'Social',
    'Crosspost editor with per-platform countdowns, live truncating previews, and a schedule queue.',
  ),
  entry(
    'doc-suggestion-review',
    'Doc Suggestions & Comments',
    'page',
    'Social',
    'Doc review canvas with per-author tracked changes, accept/reject/batch-undo controls, and an anchored comment rail.',
  ),
  entry(
    'threaded-forum-topic',
    'Threaded Forum Topic',
    'page',
    'Social',
    'Forum topic with a vote-ranked nested reply tree, collapsible subtrees, live sorting, inline branch composers, and a jump-to-accepted-answer rail.',
  ),
  entry(
    'poll-survey-builder',
    'Poll & Survey Builder',
    'page',
    'Social',
    'Two-pane survey builder: question editor with reorder and branch rules beside a live preview with a branch-honoring test mode and results tab.',
  ),
  entry(
    'cart-checkout-flow',
    'Cart & Checkout',
    'page',
    'Commerce',
    'Four-step checkout: qty steppers, working promo code, saved addresses and cards, and a live-totals order-summary rail.',
  ),
  entry(
    'order-tracking',
    'Order Tracking',
    'page',
    'Commerce',
    'Post-purchase parcel tracker: five-stage progress stepper, schematic route strip with truck marker, carrier scan timeline, and an items/address/support panel with return and report-issue flows.',
  ),
  entry(
    'product-detail-gallery',
    'Product Detail',
    'page',
    'Commerce',
    'PDP with gradient gallery stage and thumb rail, color/size selectors, sticky buy box with stepper, spec/shipping collapsibles, rating histogram, and related row.',
  ),
  entry(
    'storefront-browse',
    'Storefront Browse',
    'page',
    'Commerce',
    'Faceted storefront grid with filter rail, applied-filter tokens, wishlist toggles, quick-view dialog, and load-more footer.',
  ),
  entry(
    'pricing-plans',
    'Pricing Plans',
    'page',
    'Commerce',
    'Billing toggle with savings badges, 3-up plan cards, seat estimator, frozen-column feature table, and FAQ collapsibles.',
  ),
  entry(
    'subscription-billing-portal',
    'Billing Portal',
    'page',
    'Commerce',
    'Current-plan card with retention-offer cancel dialog, usage meters vs plan limits, payment methods, and invoice table.',
  ),
  entry(
    'returns-exchange-flow',
    'Returns & Exchange',
    'page',
    'Commerce',
    'Guided return flow: item picker with qty steppers, per-item reasons, refund/credit/exchange resolution, drop-off fees, printable label.',
  ),
  entry(
    'product-quickview-showcase',
    'Product Quickview Showcase',
    'page',
    'Commerce',
    '8-product lookbook grid with three switchable quickview dialog variants (modal, wide with details accordion, slide-over drawer), color/size selectors with per-size stock, notify-me for sold-out sizes, and add-to-bag validation with an animated bag count and confirmation toast.',
  ),
  entry(
    'order-history-page',
    'Order History Page',
    'page',
    'Commerce',
    'Account purchase history: lifetime-stat chips, status/year/search filters, switchable card and expandable-table layouts, buy-again cart, invoice dialog, and tracking deep-link toasts.',
  ),
  entry(
    'storefront-promo-navigation',
    'Storefront Promo & Navigation',
    'page',
    'Commerce',
    'Outdoor-gear storefront landing with a mega-menu store nav, rotating promo bar, category tiles, a countdown sale hero, copyable offer codes, and a switchable incentives band.',
  ),
  entry(
    'product-features-reviews',
    'Product Features & Reviews',
    'page',
    'Commerce',
    'Below-the-fold PDP: switchable feature rows / spec table / diagram accordion plus reviews with filtering histogram, combinable sort, helpful votes, and a validated write-a-review form.',
  ),
  entry(
    'marketing-hero-showcase',
    'Hero Section Showcase',
    'page',
    'Marketing',
    'Four labeled hero variants for a dev-tools SaaS with a scroll-spy jump rail, live light/dark scheme toggle, validating email capture, and toast-firing CTAs.',
  ),
  entry(
    'marketing-cta-banners',
    'CTA & Banner Showcase',
    'page',
    'Marketing',
    'Dismissible top bar, gradient promo with live countdown, floating privacy consent banner, and four CTA variants with email capture, restore toolbar, and toast receipts.',
  ),
  entry(
    'marketing-social-proof',
    'Social Proof Sections',
    'page',
    'Marketing',
    'Testimonial grids, spotlight carousel, masonry wall, CSS-wordmark logo clouds, and count-up stat bands with nine switchable sub-variants.',
  ),
  entry(
    'marketing-faq-contact',
    'FAQ & Contact Sections',
    'page',
    'Marketing',
    'Three FAQ variants (expand-all accordion, category-filtered Q&A grid, offset single-open list with support CTA) plus three contact variants: split form with a schematic office map, centered topic-Selector form, and a support-channels grid — both forms validate and show inline success panels.',
  ),
  entry(
    'marketing-team-sections',
    'Team Section Showcase',
    'page',
    'Marketing',
    'Four switchable team-section variants: photo-card grid, leadership spotlight, collapsible department directory, and a dark hiring band with bio popovers.',
  ),
  entry(
    'marketing-blog-content-sections',
    'Blog & Content Sections',
    'page',
    'Marketing',
    'Five-variant blog/content section library: filterable post-card grid, click-to-swap featured split, date-gutter chronological list, centered prose article with newsletter signup, and a scroll-spied sticky-TOC article.',
  ),
  entry(
    'marketing-header-newsletter',
    'Page Headers & Newsletter Sections',
    'page',
    'Marketing',
    'Four page-header variants (centered eyebrow, dark stat chips, split CTA, toggling filter pills) over three validated newsletter signups with distinct success states and a jump rail.',
  ),
  entry(
    'marketing-footer-collection',
    'Footer Collection',
    'page',
    'Marketing',
    'Five Relay footer variants — sitemap with validating newsletter form, slim social row, dark mega-footer with language Selector and status chip, centered minimal, app-style legal/locale-currency row — previewed against a light/dark page-bottom toggle with a live demo-state readout.',
  ),
  entry(
    'error-404-collection',
    '404 & Error Page Collection',
    'page',
    'Marketing',
    'Four framed error screens — minimal 404, lost-robot search over fixture routes, helpful links, and a 5xx incident with retry spinner — behind a variant switcher and 404/500 code toggle.',
  ),
  entry(
    'company-about-page',
    'Company About Page Example',
    'page',
    'Marketing',
    'Company about page with scroll-spy subnav, count-up stats band, alternating milestone timeline, values grid, leadership bio popovers, and a careers CTA panel.',
  ),
  entry(
    'marketing-feature-sections',
    'Feature Section Showcase',
    'page',
    'Marketing',
    'Four feature-section variants — expandable icon grid, scroll-reveal alternating rows, 2x2 grid with tabbed screenshot panel, and a dark spotlight with copyable code card — behind a variant switcher.',
  ),
  entry(
    'marketing-bento-grid',
    'Bento Grid Showcase',
    'page',
    'Marketing',
    'Three bento-section variants — asymmetric 3-column grid with latency hero, dark 5-cell panel with schematic mocks, compact big-number stats grid — with density toggle and scroll-spy jump rail.',
  ),
  entry(
    'marketing-navbar-flyouts',
    'Marketing Navbars & Flyout Menus',
    'page',
    'Marketing',
    'Three framed navbar variants — light centered, dark solid-on-scroll with mega menu, two-tier eyebrow — each with click-open flyouts, a simulated-scroll slider, and 375px hamburger-drawer previews.',
  ),
  entry(
    'saas-landing-page',
    'SaaS Landing Page Example',
    'page',
    'Marketing',
    'Full landing page: dismissible banner, sticky navbar with flyout and scroll-spy anchors, split hero with email capture, feature rows, bento band, testimonial, pricing teaser, FAQ, and sitemap footer.',
  ),
  entry(
    'form-controls-gallery',
    'Form Controls Gallery',
    'page',
    'UI Kit',
    'Section rail plus eight live control-family panels — input groups, selects, textareas, radios, indeterminate checkboxes, toggles, comboboxes, action panels — each with a JSON state readout and a reset-all.',
  ),
  entry(
    'ui-elements-gallery',
    'UI Elements Gallery',
    'page',
    'UI Kit',
    'Five interactive panels of core atoms — avatars, badges, buttons, button groups, dropdown menus — each variant with a copy-ready props strip.',
  ),
  entry(
    'status-feedback-gallery',
    'Status & Feedback Gallery',
    'page',
    'UI Kit',
    'Four-panel UI-kit gallery of live page-state patterns — dismissable alert banners with a restore tray, self-resolving empty states, a slider-driven progress trio plus checkout stepper, and four pagination idioms windowing a fixture invoice list.',
  ),
  entry(
    'layout-primitives-gallery',
    'Layout Primitives Gallery',
    'page',
    'UI Kit',
    'Five-panel structural building-block gallery on a dotted baseline: containers with a live viewport slider, dense/comfortable card variants, sticky-header lists, recursive media threads, and divider patterns with copyable caption chips.',
  ),
  entry(
    'headings-lists-gallery',
    'Headings & List Patterns Gallery',
    'page',
    'UI Kit',
    'Five-panel headings and list patterns gallery — page/card/section headings, description lists, and stacked lists — with a scroll-spying rail, inline edits, filter tabs, and a bulk-select bar.',
  ),
  entry(
    'calendar-month-grid',
    'Month Calendar',
    'page',
    'Calendar',
    'Month day grid with category-colored event chips, filter legend toggles, and a selected-day panel.',
  ),
  entry(
    'calendar-week-agenda',
    'Week Agenda',
    'page',
    'Calendar',
    'Week time-grid with side-by-side overlap columns, an all-day row, a fixed now line, and a click-to-open event detail panel.',
  ),
  entry(
    'booking-availability-picker',
    'Booking Picker',
    'page',
    'Calendar',
    'Calendly-style scheduler: host rail, availability-dot date strip, timezone-shifted slot grid, and confirm form with success state.',
  ),
  entry(
    'event-detail-rsvp',
    'Event RSVP',
    'page',
    'Calendar',
    'Gradient event hero with a sticky Going/Maybe/Cannot-go RSVP card, guest stepper, attendee counts, agenda, schematic map, and discussion.',
  ),
  entry(
    'team-scheduler',
    'Team Scheduler',
    'page',
    'Calendar',
    'Cross-timezone meeting matrix: member-by-hour free/busy cells, a sliding slot highlight, ranked best-slot cards, and a local-times invite summary.',
  ),
  entry(
    'time-off-planner',
    'Time-Off Planner',
    'page',
    'Calendar',
    'PTO balance cards with accrual notes, business-day request form, team absence strip, and approve/deny requests table.',
  ),
  entry(
    'transactions-ledger',
    'Transactions Ledger',
    'page',
    'Finance',
    'Running-balance account register with pending/posted groups, reconcile checkboxes feeding a sticky summary bar, filters, and a transaction detail panel.',
  ),
  entry(
    'invoice-builder',
    'Invoice Builder',
    'page',
    'Finance',
    'Split invoice form with a line-item editor beside a live paper preview computing subtotal, tax, and discount.',
  ),
  entry(
    'expense-approval-queue',
    'Expense Approvals',
    'page',
    'Finance',
    'Approvals inbox: flagged expense-report queue with bulk-approve for clean reports, line-item detail with receipt tiles, and reject-with-required-comment.',
  ),
  entry(
    'budget-tracker',
    'Budget Tracker',
    'page',
    'Finance',
    'Envelope budgeting: month switcher, over-budget alert envelopes, safe-to-spend math, CSS-only burn-down strip, and inline per-envelope transactions.',
  ),
  entry(
    'payout-statements',
    'Payout Statements',
    'page',
    'Finance',
    'Period payout statements with a gross-to-net waterfall detail pane, destination accounts, and CSV/PDF export toasts.',
  ),
  entry(
    'portfolio-holdings',
    'Portfolio Holdings',
    'page',
    'Finance',
    'Signed-summary portfolio: conic-gradient allocation donut, holdings table with lot-level detail panel, and watchlist rail.',
  ),
  entry(
    'crm-contact-record',
    'CRM Contact Record',
    'page',
    'Business',
    '360° contact record: clickable lifecycle stepper, inline-editable field groups, typed Note/Call/Email/Task composer over a filterable timeline, and a deals rail with live open-task count.',
  ),
  entry(
    'fleet-dispatch-board',
    'Fleet Dispatch Board',
    'page',
    'Business',
    'Dispatch queue beside driver time lanes with animated load meters, conflict-override drops, and a route-sequence rail.',
  ),
  entry(
    'org-chart-explorer',
    'Org Chart Explorer',
    'page',
    'Business',
    'Pannable org-chart canvas with SVG edges, collapsible branches, search centering, an inline-edit rail, and confirm-guarded re-parenting with undo.',
  ),
  entry(
    'review-cycle-calibration',
    'Performance Review Calibration',
    'page',
    'Business',
    '9-box calibration grid with draggable reviewee tiles, a live rating histogram with over-target flags, inline rating edits, and finalize/reset controls.',
  ),
  entry(
    'esignature-envelope-flow',
    'E-Signature Envelope Builder',
    'page',
    'Business',
    'Four-step envelope wizard with click-to-place signature fields, live signing-order renumbering, and a simulated delivery tracker.',
  ),
  entry(
    'roadmap-gantt',
    'Roadmap Gantt',
    'page',
    'Planning',
    'Quarter roadmap: zoomable quarter/month axis, team swimlanes with progress-filled bars, milestone diamonds, and SVG dependency arrows.',
  ),
  entry(
    'sprint-board-backlog',
    'Sprint Board',
    'page',
    'Planning',
    'Sprint board with a backlog rail, capacity meter, and accessible story moves.',
  ),
  entry(
    'issue-detail',
    'Issue Detail',
    'page',
    'Planning',
    'Ticket page with editable status, sub-task progress, CI-dotted linked PRs, a metadata rail, and threaded activity.',
  ),
  entry(
    'okr-tree',
    'OKR Tree',
    'page',
    'Planning',
    'Objectives-to-key-results tree: quarter selector, confidence-colored progress rows, at-risk filter, check-in history panel.',
  ),
  entry(
    'release-train-overview',
    'Release Train',
    'page',
    'Planning',
    'Horizontal release-train rail with per-train feature flags, blocking issues, go/no-go sign-offs, and a cherry-pick approval queue.',
  ),
  entry(
    'milestone-burnup',
    'Milestone Burnup',
    'page',
    'Planning',
    'Delivery burnup: stepped scope line over completed area with forecast band, tappable scope-change markers, KPI stats, and expandable milestone table.',
  ),
  entry(
    'coding-terminal-workspace',
    'Terminal Workspace',
    'page',
    'Coding',
    'Multi-tab terminal: session sidebar with activity dots, typed-record scrollback, split panes, scrollback search, and a mod+K palette.',
  ),
  entry(
    'repl-playground',
    'REPL Playground',
    'page',
    'Coding',
    'Two-pane code playground with a tokenized editor, example snippets, and a filterable run console.',
  ),
  entry(
    'code-review-diff-queue',
    'Review Queue',
    'page',
    'Coding',
    'Multi-file PR review with a file tree, viewed progress, inline threads, and a verdict dialog.',
  ),
  entry(
    'git-branch-graph',
    'Branch Graph',
    'page',
    'Coding',
    'Lane-drawn commit DAG with colored rails, ref badges, branch filter, diffstat detail panel, and a compare-range mode.',
  ),
  entry(
    'test-runner-console',
    'Test Runner',
    'page',
    'Coding',
    'Suite tree with per-describe counts, filterable run stream with spinner rows, and a failure panel with stack trace and expected/received diff.',
  ),
  entry(
    'editor-file-tabs-shell',
    'Editor Shell',
    'page',
    'Coding',
    'IDE frame: explorer rail with git-status dots, dirty-dot tab strip, token-tinted code viewport with minimap, jump-to-line problems panel, and status bar.',
  ),
  entry(
    'sql-query-workbench',
    'SQL Query Workbench',
    'page',
    'Data',
    'Database IDE with a connection picker, expandable schema tree, tabbed SQL editors, and a sortable, filterable result grid with canned query results.',
  ),
  entry(
    'schema-designer-erd',
    'Schema Designer (ERD)',
    'page',
    'Data',
    'Pannable ERD canvas of draggable table cards with FK lines, in-card column editing, live DDL panel, and a validation strip.',
  ),
  entry(
    'dag-run-visualizer',
    'Pipeline DAG Run Visualizer',
    'page',
    'Data',
    'Airflow-style orchestration console: run rail, state-colored task DAG, run-history grid, retry/mark-success cascades, and backfill.',
  ),
  entry(
    'data-quality-monitors',
    'Data Quality Monitor Console',
    'page',
    'Data',
    'Pass/warn/fail chip filters, monitor table with SVG sparklines, threshold-slider detail drawer with violation band, snooze/mute section, and incident timeline.',
  ),
  entry(
    'data-catalog-lineage',
    'Data Catalog & Lineage Explorer',
    'page',
    'Data',
    'Dataset catalog with search and tag rail, editable descriptions and tags, pinnable columns, and a clickable SVG lineage graph with column-level edges.',
  ),
  entry(
    'query-plan-profiler',
    'Query Performance Profiler',
    'page',
    'Data',
    'Slow-query profiler: cost-ranked query rail, collapsible EXPLAIN tree with cost bars, index suggestions that swap in optimized plans, and plan compare.',
  ),
  entry(
    'shell-left-sidebar',
    'Shell - Left Sidebar',
    'page',
    'Shell',
    'AppShell with a collapsible grouped SideNav beside a placeholder page.',
  ),
  entry(
    'shell-top-nav',
    'Shell - Top Nav',
    'page',
    'Shell',
    'Horizontal TopNav bar over a full-width content area with a placeholder slot.',
  ),
  entry(
    'shell-top-nav-sidebar',
    'Shell - Top Nav + Left Sidebar',
    'page',
    'Shell',
    'Global TopNav plus a contextual SideNav that swaps groups per active section.',
  ),
  entry(
    'shell-breadcrumb',
    'Shell - Breadcrumb Driven',
    'page',
    'Shell',
    'Drill-down shell where a deep Breadcrumbs trail carries all hierarchy.',
  ),
  entry(
    'messaging-shell',
    'Messaging Shell',
    'page',
    'Shell',
    'Four-column messaging frame with rail, channel list, stream, and thread panel.',
  ),
  entry(
    'notification-center',
    'Notification Center',
    'page',
    'Shell',
    'Navbar bell with unread badge, pinned-open 320px notification popover, corner toast, and state variants.',
  ),
  entry(
    'logs-explorer',
    'Logs Explorer',
    'page',
    'Monitoring',
    'Facet rail, PowerSearch filters, live-tail switch, and expandable log stream.',
    'Uses a local LogStream shim until the lab component is released.',
  ),
  entry(
    'operations-dashboard',
    'Operations Dashboard',
    'page',
    'Operations',
    'Starter dashboard for this package with KPI cards, review queue, and actions.',
  ),
  entry(
    'cloud-cost-analyzer',
    'Cloud Cost Analyzer',
    'page',
    'Operations',
    'Group-by-driven stacked spend chart with drill-down ledger, anomaly popover, and what-if commitment slider.',
  ),
  entry(
    'api-request-explorer',
    'API Request Explorer',
    'page',
    'Operations',
    'Postman-style API client: collection tree with dirty dots, env-variable request builder, canned JSON responses, and a restoring history rail.',
  ),
  entry(
    'webhook-delivery-debugger',
    'Webhook Delivery Debugger',
    'page',
    'Operations',
    'Endpoint health rail, filterable delivery feed, and JSON-tree detail pane with replay and retry-policy drawer.',
  ),
  entry(
    'cert-key-inventory',
    'Certificate & Key Inventory',
    'page',
    'Operations',
    'TLS lifecycle console: filterable cert table and expiry timeline views, a chain-and-deployments drawer, and a rotate wizard with live recompute and undo.',
  ),
  entry(
    'kpi-strip',
    'KPI Strip',
    'block',
    'Operations',
    'Compact metric card strip for dashboard headers.',
  ),
  entry(
    'codeblock-terminal',
    'Code - Terminal',
    'block',
    'Code',
    'Dark terminal-style CodeBlock with a syntax theme wrapper.',
  ),
  entry(
    'swipe-triage-stack',
    'Swipe Triage Stack',
    'page',
    'Interaction',
    'Gesture-quality swipe card stack: 1:1 pointer drag with progressive verdict stamps, threshold snap-back with overshoot, off-canvas flings, undoable history rail, and full button/arrow-key parity.',
  ),
  entry(
    'bottom-sheet-snap-explorer',
    'Snap-Point Bottom Sheet Explorer',
    'page',
    'Interaction',
    'Mobile-first place explorer: SVG map under a draggable bottom sheet with peek/half/full snaps, velocity-aware fling settle, drag-vs-scroll handoff, and keyboard-cycled snap points.',
  ),
  entry(
    'drag-rank-list',
    'Drag-to-Rank Board',
    'page',
    'Interaction',
    'Drag-to-rank priority board: pointer-drag sortable with live FLIP slot preview, overshoot settle, long-press touch lift, Space/arrows grab mode, undo chips, and a top-3 analysis rail.',
  ),
  entry(
    'metric-brush-explorer',
    'Brushing & Linking Metric Lab',
    'page',
    'Explorables',
    'SVG scatter with a draggable rectangle brush bidirectionally linked to a spend histogram, segment bars, live lasso stats, filter chips, and a brushed-accounts table.',
  ),
  entry(
    'cpu-flame-graph',
    'Zoomable CPU Flame Graph',
    'page',
    'Explorables',
    'Icicle flame graph with click-to-re-root zoom, ancestor breadcrumb, frame search with dimmed non-matches, red/blue baseline diff, and a hottest-frames detail rail.',
  ),
  entry(
    'service-blast-radius',
    'Service Graph Blast-Radius Sandbox',
    'page',
    'Explorables',
    'Kill-switch outage sandbox over a 21-service SVG graph: deterministic BFS blast radius with Play/Step waves, mitigation reroutes, preset scenarios, and a lost-RPS impact panel.',
  ),
  entry(
    'multiplayer-whiteboard-replay',
    'Multiplayer Whiteboard Replay',
    'page',
    'Collaboration',
    'Whiteboard replay where collaborator cursors glide along keyframe paths as notes and comments appear — state is a pure function of the scrub tick, with follow-mode panning, a minimap, and a who-wins conflict.',
  ),
  entry(
    'offline-sync-outbox',
    'Offline Sync Outbox',
    'page',
    'Tools',
    'Offline-first field-notes app beside its sync internals: airplane-mode toggle, optimistic outbox chips, scripted drain with ack/retry/conflict, a per-field merge resolver, and rollback with undo.',
  ),
  entry(
    'wheel-picker-scheduler',
    'Wheel Picker Scheduler',
    'page',
    'Interaction',
    'iOS-style scroll-snap wheel pickers with a center lens, distance-from-center row transforms, coordinated preset smooth-scrolls, a tweening conic duration ring, and a reorderable session queue.',
  ),
  entry(
    'wallet-card-fan',
    'Wallet Card Fan',
    'page',
    'Interaction',
    'Apple-Wallet card fan: five token-gradient cards promote/compress with staggered spring choreography, 3D-flip to masked details, drag-down or Esc to re-stack, and a cascading per-card ledger.',
  ),
  entry(
    'story-progress-viewer',
    'Story Progress Viewer',
    'page',
    'Interaction',
    'Full-bleed stories stage with keyframe-timed segment bars, hold-to-pause, cube-turn author switching, working polls, and a recap grid.',
  ),
  entry(
    'attribution-sankey-what-if',
    'Attribution Sankey What-If',
    'page',
    'Explorables',
    'Three-column attribution sankey with hand-rolled bezier ribbons, path-tracing hover/pin highlights, and a what-if panel that re-flows volumes through deterministic redistribution rules.',
  ),
  entry(
    'region-tile-cartogram',
    'Tile Cartogram Metric Atlas',
    'page',
    'Explorables',
    'Choropleth tile cartogram of 50 states: switchable metric ramps, pin-to-compare chips with sparklines, linked ranking bars, bucket-filter legend, and a five-year playback transport.',
  ),
  entry(
    'deploy-impact-scrubber',
    'Deploy Impact Scrubber',
    'page',
    'Explorables',
    'Shared-axis deploy forensics: glyph-coded event timeline with a snap-to-event playhead and brush-to-zoom over three linked charts, synced crosshair, and event-by-event playback.',
  ),
  entry(
    'live-auction-room',
    'Live Auction Room',
    'page',
    'Collaboration',
    'Live auction lot on a replayable bid tape — anti-snipe countdown, proxy auto-counters, per-paddle ladder, and a going-once/twice/hammer finale.',
  ),
  entry(
    'ops-wall-display',
    'NOC Wall Display',
    'page',
    'Collaboration',
    'Kiosk NOC wall on a 48-tick fixture tape — tweened oversized numerals over EKG heartbeats, pulsing region grid, auto-cycling spotlight, incident ticker, and a SEV1 takeover banner.',
  ),
  entry(
    'venue-seat-picker',
    'Venue Seat Map Picker',
    'page',
    'Spatial',
    'SVG theater seat map with a four-tier price ramp, section tap-to-zoom, a best-available block finder, and a tier-grouped cart — the StyleX pilot.',
    'Uses @stylexjs/stylex for the hand-rolled seat map — consumers need @stylexjs/unplugin (or another StyleX compiler) in their build.',
  ),
  entry(
    'step-sequencer-groovebox',
    'Step Sequencer Groovebox',
    'page',
    'Creative',
    'Drum-machine groovebox: an 8x16 velocity pad grid, mute/solo LEDs, pattern banks A-D, and a FLIP-reordering chain lane where cursor, hit flashes, and swing-skewed columns derive from one tick counter.',
  ),
  entry(
    'podcast-word-splicer',
    'Transcript-Linked Podcast Splicer',
    'page',
    'Creative',
    'Text-first podcast editor: drag-select timed transcript words mirrored on a two-speaker waveform, cut/restore with ripple-close collapses, a remove-all-fillers sweep, and chapter times re-derived from the edit list.',
  ),
  entry(
    'bezier-easing-studio',
    'Easing Curve Studio',
    'page',
    'Creative',
    'Motion-design workbench: draggable SVG cubic-bezier editor with overshoot bands, preset rail, ghost-curve compare, spring-to-linear() export, and a tick-pure preview stage with play/step/scrub transport.',
  ),
  entry(
    'theme-token-studio',
    'Theme Token Studio',
    'page',
    'Creative',
    'Design-token workbench: a token tree with inline ramp/stepper editors live-restyling a mini app rendered twice in forced-light and forced-dark panes, with a changes rail, brand presets, and a JSON/CSS/diff export drawer.',
  ),
  entry(
    'nonogram-pixel-reveal',
    'Nonogram Picture Logic',
    'page',
    'Play',
    '10x10 picross with clue ledges derived from a fixture fox, pointer-capture stroke painting, hearts, scripted hints, and a row-by-row color bloom on solve.',
  ),
  entry(
    'sudoku-logic-coach',
    'Sudoku with Pencil Marks',
    'page',
    'Play',
    'Playable 9x9 sudoku with pencil-mark notes, atomic auto-erase undo, conflict rings, and a step/play logic coach that replays an authored solve path.',
  ),
  entry(
    'office-home-launcher',
    'Suite Home & App Launcher',
    'page',
    'Office Suite',
    'Suite front door: global search with an open recents dropdown, six-tile app launcher grid, upcoming-meetings strip, recent-files rail, templates row, and a stacked storage meter.',
  ),
  entry(
    'office-shared-drive',
    'Shared Drive Manager',
    'page',
    'Office Suite',
    'Drive surface with a folder-tree rail and quota strip, sortable multi-select file table with bulk actions, and a Details/Activity panel covering sharing, metadata, and storage.',
  ),
  entry(
    'doc-comments-review',
    'Document Comments & Review',
    'page',
    'Office Suite',
    'Paper canvas with comment-anchored highlights and suggestion spans beside a filterable margin rail of threaded comments, reactions, and an accept/reject suggestions queue.',
  ),
  entry(
    'doc-version-history',
    'Doc Version History',
    'page',
    'Office Suite',
    'Day-grouped version rail with named-version stars, change-size sparkbars, and autosave collapses beside a diff-highlighted paper preview with rename, show-changes, and restore.',
  ),
  entry(
    'doc-share-publish',
    'Doc Sharing & Publish Panel',
    'page',
    'Office Suite',
    'Share dialog over a dimmed doc preview: invite composer, per-person role Selectors, general-access and copy-link rows, plus a Publish tab with web toggle, embed snippet, and access requests.',
  ),
  entry(
    'meet-precall-lobby',
    'Meeting Pre-call Lobby',
    'page',
    'Office Suite',
    'Pre-join greenroom: dark camera-preview stage with mic pulse, device Selectors with live input meter, background-effects gallery, meeting-info panel, and a health-check footer strip.',
  ),
  entry(
    'meet-live-stage',
    'Live Meeting Stage — Captions & Participation',
    'page',
    'Office Suite',
    'Dark call stage with layout switching, speaker-attributed live captions, floating reactions, host controls, a breakout banner, and a raised-hands queue panel with invite-to-speak.',
  ),
  entry(
    'meet-breakout-manager',
    'Breakout Rooms Manager',
    'page',
    'Office Suite',
    'Host breakout console: draggable participant chips across timed room cards, rooms/duration steppers with an unassigned tray, broadcast composer, and a distribution status column.',
  ),
  entry(
    'meet-recap',
    'Meeting Recap & Transcript',
    'page',
    'Office Suite',
    'Post-meeting review: recording player with chapter markers and scrubber, searchable speaker-filtered transcript synced to the playhead, AI summary, action items, and talk-time analytics.',
  ),
  entry(
    'office-universal-search',
    'Suite Universal Search',
    'page',
    'Office Suite',
    'Cross-app results page for one executed query: faceted filter rail with agreeing counts, best-match hero card, per-app result groups with expanders, and a related-people rail.',
  ),
  entry(
    'hr-onboarding-flow',
    'New-Hire Onboarding Flow',
    'page',
    'Workforce HR',
    'Per-hire onboarding command center: in-flight-hire rail, phase chip timeline, cross-team task checklist, day-1 agenda strip, e-sign document statuses, and an equipment shipment tracker.',
  ),
  entry(
    'hr-offboarding-flow',
    'Offboarding & Access Revocation',
    'page',
    'Workforce HR',
    'Departure runbook: countdown header, phase rail, access-revocation checklist with per-row revoke, asset-return tiles with tracking, knowledge-transfer tasks, and a final-pay panel with terminate-access confirm.',
  ),
  entry(
    'hr-employee-profile',
    'Employee Record',
    'page',
    'Workforce HR',
    'HR-admin profile: identity band with manager chain, comp-visibility masking toggle, and jump-scroll sections for job & comp, documents, devices & apps, and time-off balances.',
  ),
  entry(
    'hr-headcount-planning',
    'Headcount Planning',
    'page',
    'Workforce HR',
    'Plan-vs-actuals console: KPI strip, per-department table with stacked utilization bars, quarterly hiring-cost strip, and an open-req pipeline panel re-computed by a base/stretch scenario toggle.',
  ),
  entry(
    'hr-time-attendance',
    'Time & Attendance Approvals',
    'page',
    'Workforce HR',
    'Timesheet approval console: week selector, pay-period lock banner, multi-select table with daily punch chips and overtime flags, exception-aware bulk approve, and a punch-detail drawer.',
  ),
  entry(
    'hr-leave-policies',
    'Leave Policy Administration',
    'page',
    'Workforce HR',
    'Admin leave-policy console: policy rail with accrual summaries, pending-change banner with publish/discard, tenure-band accrual table, edit-gated toggles, and a holiday-calendar panel.',
  ),
  entry(
    'hr-performance-review',
    'Performance Review Authoring',
    'page',
    'Workforce HR',
    'Manager review-writing surface: reports rail, competency ratings with last-cycle ghosts and deltas, word-count-gated narratives, goal-outcome attainment, and a peer-feedback rail.',
  ),
  entry(
    'hr-recruiting-pipeline',
    'Recruiting Pipeline (ATS)',
    'page',
    'Workforce HR',
    'Single-requisition ATS board: req header with panel facepile, funnel pass-through strip, and five stage columns of candidate cards with drag-and-drop, stalled rings, and conversion footers.',
  ),
  entry(
    'hr-candidate-profile',
    'Candidate Profile & Scorecards',
    'page',
    'Workforce HR',
    'Onsite-stage candidate detail: identity band with stage stepper, resume-excerpt card, four-interview loop panel with scorecard statuses, competency-rated scorecard detail, offer-prep card vs band, and an activity timeline.',
  ),
  entry(
    'hr-compensation-bands',
    'Compensation Bands',
    'page',
    'Workforce HR',
    'Comp-admin band explorer: level x geo band matrix, range bar with market-percentile ticks and employee dots, band-detail panel, and a proposed-adjustment approval queue.',
  ),
  entry(
    'hr-benefits-enrollment',
    'Benefits Enrollment Admin',
    'page',
    'Workforce HR',
    'Open-enrollment console: window banner with completion meter, plan cards with cost-split bars, status-segmented employee table with nudges, QLE exceptions, and a dependent-verification queue.',
  ),
  entry(
    'hr-compliance-training',
    'Compliance Training Tracker',
    'page',
    'Workforce HR',
    'Training admin console: course cards with completion rings, department x course heat table, overdue-employees panel with reminders, and auto-assignment rule tiles.',
  ),
  entry(
    'hr-engagement-survey',
    'Engagement Survey Results',
    'page',
    'Workforce HR',
    'Pulse-survey readout: response-rate header, eNPS arc gauge with promoter split bars, benchmarked category score board, anonymity-aware team heat strip, driver callout, and a top-themes panel.',
  ),
  entry(
    'hr-i9-compliance',
    'I-9 & Work Authorization',
    'page',
    'Workforce HR',
    'Work-authorization tracker: completion summary strip, pending-verification queue with List A/B/C document checklist, reverification countdowns, E-Verify case table, and an audit-readiness panel.',
  ),
  entry(
    'it-device-inventory',
    'Device Fleet Inventory',
    'page',
    'Workforce IT',
    'MDM endpoint posture: summary chips scoping a sortable multi-select device table, violation pill row, bulk lock/update actions, and a quick panel with warranty, storage, and shipment tracking.',
  ),
  entry(
    'it-device-detail',
    'Device Detail & Remote Actions',
    'page',
    'Workforce IT',
    'Single-endpoint drill-down: identity band with posture chips, compliance checklist with remediation, installed-apps table, lifecycle timeline, and a remote-actions rail with gated wipe.',
  ),
  entry(
    'it-app-provisioning',
    'SaaS App Catalog & Provisioning',
    'page',
    'Workforce IT',
    'Seat-management console: KPI strip, app card grid with SSO badges and utilization bars, and a selected-app panel with renewal countdown, assignment rules, and a seat-reclaim action.',
  ),
  entry(
    'it-access-requests',
    'Access Request Approvals',
    'page',
    'Workforce IT',
    'Approval queue: request table with policy-check pills and SLA aging, checkbox gating that keeps flagged rows out of bulk approve, and an end panel with approval-chain stepper and policy checks.',
  ),
  entry(
    'it-identity-sso',
    'Identity & SSO Administration',
    'page',
    'Workforce IT',
    'IdP console: posture chips scoping an SSO connections table with sign-in sparkbars and cert countdowns, connection detail with working cert rotate, plus directory-sync, password-policy, and session cards.',
  ),
  entry(
    'it-security-policies',
    'Endpoint Security Policies',
    'page',
    'Workforce IT',
    'Policy center: enforcement-pill policy cards with coverage bars, department x policy compliance matrix with drill-in inspector, exceptions table, draft-change banner, and a checks-passing trend chart.',
  ),
  entry(
    'it-inventory-orders',
    'Hardware Orders & Logistics',
    'page',
    'Workforce IT',
    'Procurement console: stock-on-hand grid with low-stock chips, purchase-order table with a working Receive action, inbound-shipment tracker, and a logistics panel with budget meter and allocation queues.',
  ),
  entry(
    'it-onboarding-provisioning',
    'Day-1 Provisioning Status',
    'page',
    'Workforce IT',
    'Provisioning run console: run rail with segmented progress tracks and SLA strip, step-chip pipeline with timestamps, failed-step error region with retry/skip, and kit-template diffs.',
  ),
  entry(
    'workflow-studio-canvas',
    'Workflow Studio (Automation Canvas)',
    'page',
    'Workforce Platform',
    'Workforce-automation studio: palette rail, pannable canvas with bezier edges, branching lifecycle workflow with per-node run stats and a validation badge, node config panel, and a run-history strip.',
  ),
  entry(
    'workforce-audit-log',
    'Admin Audit Log',
    'page',
    'Workforce Platform',
    'Tamper-evident action trail: filter bar, expandable event table with hash-chain marks and masked comp diffs, suspicious-activity banner, export controls, and a retention-policy footer.',
  ),
  entry(
    'workforce-analytics',
    'Workforce Analytics Dashboard',
    'page',
    'Workforce Platform',
    'Cross-pillar analytics: KPI row, 2x2 chart grid (headcount vs plan, attrition bars, diversity donuts, payroll stacked area), cross-highlighting month clicks, and a cited insights rail.',
  ),
  entry(
    'workforce-approvals-inbox',
    'Unified Approvals Inbox',
    'page',
    'Workforce Platform',
    'Cross-domain approvals: type-grouped queue with SLA chips and j/k/a/r shortcuts, and type-specific detail panes — PTO coverage calendars, expense line items, access chains, and comp-vs-band meters.',
  ),
  entry(
    'workforce-employee-home',
    'Employee Self-Service Home',
    'page',
    'Workforce Platform',
    'Employee home hub: payday countdown, quick actions, my-pay card with deduction breakdown, time-off balances, benefits strip with a 401k quick-change editor, announcements, and a tasks rail.',
  ),
  entry(
    'fin-payroll-run',
    'Payroll Run Review',
    'page',
    'Workforce Finance',
    'Pay-run console: run-status stepper, reconciling summary cards, sortable pay-register table, anomaly review queue with resolve actions, dual-approver status, and a gated approve-and-submit bar.',
  ),
  entry(
    'fin-paystub-detail',
    'Employee Pay Statement',
    'page',
    'Workforce Finance',
    'Gross-to-net paystub: net-pay hero with equation strip and deposit split, sectioned earnings/deductions/taxes tables with YTD columns, a USD/% view toggle, and an employer-cost sidebar.',
  ),
  entry(
    'fin-corporate-cards',
    'Corporate Card Program',
    'page',
    'Workforce Finance',
    'Card program console: KPI rail with spend donut, sortable card table with limit meters and receipt flags, and a selected-card panel with freeze confirm, controls, and a reconciling transaction ledger.',
  ),
  entry(
    'fin-spend-policies',
    'Spend Policy Builder',
    'page',
    'Workforce Finance',
    'Spend-policy console: policy rail with violation badges, effectiveness stats, per-category limits table, node-and-spine approval-chain builder, receipt rules, and a 30-day violation feed.',
  ),
  entry(
    'fin-invoices-billpay',
    'Bill Pay & Invoice Inbox',
    'page',
    'Workforce Finance',
    'AP console: invoice inbox table with aging colors, cash-out forecast strip, and a review panel with OCR field confirms, three-way-match tiles, payment scheduling, and approval-chain status.',
  ),
  entry(
    'fin-contractor-payments',
    'Global Contractor Payments',
    'page',
    'Workforce Finance',
    'Contractor payout batch: blocked-payout banner, reconciling summary tiles with FX-lock countdown, per-country groupings with locked rates and local rails, classification callout, and a confirm-gated approve bar.',
  ),
  entry(
    'fin-global-payroll',
    'Global Payroll & Entities',
    'page',
    'Workforce Finance',
    'Multi-entity console: entity cards with local-currency totals, filing-deadline calendar strip, per-entity compliance register, and an end panel with FX hedging and expansion-request cards.',
  ),
  entry(
    'fin-tax-filings',
    'Payroll Tax Filings Tracker',
    'page',
    'Workforce Finance',
    'Tax compliance console: quarter toggle, reconciling summary tiles, filings table with status pills, agency-notice inbox, deposit schedule, and a filing-detail panel with form-line summary.',
  ),
  entry(
    'payments-platform-overview',
    'Payments Platform Overview',
    'page',
    'Startup Showcase',
    'Stripe-style payments home: gross-volume area chart with period compare, balance and payout schedule card, fraud radar, filterable payments table, disputes panel, and a test-mode switch.',
  ),
  entry(
    'hosted-checkout-flow',
    'Hosted Checkout & Payment Element',
    'page',
    'Startup Showcase',
    'PSP-hosted payment page: brand-tinted order summary with promo token beside a tabbed payment element with card-brand detection, inline validation states, wallet and bank-debit methods.',
  ),
  entry(
    'vacation-rental-listing',
    'Vacation Rental Listing',
    'page',
    'Startup Showcase',
    'Airbnb-style listing detail: photo mosaic with dialog gallery, amenities grid, availability calendar, sticky booking card with recomputing fee math, reviews with rating histogram, and host card.',
  ),
  entry(
    'music-discovery-home',
    'Music Discovery Home',
    'page',
    'Startup Showcase',
    'Music-streaming home on a dark stage: mix-tile grid, made-for-you and new-release shelves, friend-activity rail, and a pinned now-playing transport bar with scrub and volume sliders.',
  ),
  entry(
    'apm-trace-waterfall',
    'Distributed Trace Waterfall',
    'page',
    'Startup Showcase',
    'APM trace view: depth-indented span waterfall with a failed span and retry, latency percentile strip, span inspector with timing breakdown and tags, and a service-map mini graph that filters rows.',
  ),
  entry(
    'support-chat-copilot',
    'Support Inbox with AI Copilot',
    'page',
    'Startup Showcase',
    'Intercom-style live-support inbox: SLA-tracked conversation rail, chat thread with internal notes and macros, and an AI copilot rail with suggested replies, summaries, and customer context.',
  ),
  entry(
    'storefront-admin-home',
    'Storefront Admin Home',
    'page',
    'Startup Showcase',
    'Merchant admin home: live-view strip, reconciling stat cards, setup-guide checklist, working pick/pack fulfillment queue, low-stock reorder alerts, and a top-products mini table.',
  ),
  entry(
    'language-learning-path',
    'Language Learning Path',
    'page',
    'Startup Showcase',
    'Duolingo-style skill path: serpentine lesson trail with start/review bubbles, unit banner with guidebook phrases, and a rail of streak, league leaderboard, and claimable daily-quest cards.',
  ),
  entry(
    'fitness-activity-feed',
    'Fitness Activity Feed',
    'page',
    'Startup Showcase',
    'Strava-style social feed: activity cards with SVG route maps, stat rows, kudos and comment threads, weekly goal ring, climbing-challenge leaderboard, and suggested-athlete follow toggles.',
  ),
  entry(
    'design-collab-dashboard',
    'Design Collaboration Dashboard',
    'page',
    'Startup Showcase',
    'Design-tool workspace home: project rail with editor seats, recents row, file cards with canvas-gradient thumbnails and presence facepiles, branching indicators, activity feed, and shared libraries.',
  ),
  entry(
    'notes-workspace-home',
    'Notes Workspace Home',
    'page',
    'Startup Showcase',
    'Notion-style workspace: nested page-tree sidebar, block canvas with callouts, toggles, and a synced block, plus an inline database rendered as reconciling Table and Board views with backlinks.',
  ),
  entry(
    'crypto-exchange-trade',
    'Exchange Trading View',
    'page',
    'Startup Showcase',
    'Crypto trading desk: SVG candlestick chart with interval control, cumulative-depth order book, trades ticker, buy/sell ticket with fee breakdown, and an open-orders strip with cancels.',
  ),
  entry(
    'subscription-paywall-sheet',
    'Subscription Paywall Sheet',
    'block',
    'Startup Showcase',
    'Mobile bottom-sheet paywall pair for a meditation app: plan toggle with reconciling per-week math, benefit rows, free-trial timeline stepper, and a post-trial confirmation specimen.',
  ),
  entry(
    'otp-verification-screen',
    'OTP Verification Screen',
    'block',
    'Startup Showcase',
    'Phone-frame OTP state sheet: entering state with six code boxes and resend countdown, expired state with error banner and shake-frozen boxes, and a compact verified state.',
  ),
  entry(
    'boarding-pass-wallet',
    'Boarding Pass Wallet Card',
    'block',
    'Startup Showcase',
    'Wallet-style airline boarding pass with route hero, fact grid, boarding status strip, perforation divider, deterministic QR pattern, and a frozen flight-delay variant.',
  ),
  entry(
    'ride-trip-status',
    'Ride Trip Status Card',
    'block',
    'Startup Showcase',
    'Phone-width live-trip card: night-map strip with ETA chip, driver row, trip stepper, safety toolkit with guarded emergency action, and an arrived plate-verification specimen.',
  ),
  entry(
    'tipping-terminal-screen',
    'Tipping Terminal Screen',
    'block',
    'Startup Showcase',
    'Counter-facing POS tip prompt: big percentage tiles with computed amounts, live new-total bar, signature strip, and a frozen custom-tip numpad specimen.',
  ),
  entry(
    'permission-primer-card',
    'Notification Permission Primer',
    'block',
    'Startup Showcase',
    'Pre-permission primer card with benefit bullets and brand CTA over a dimmed faux iOS system-dialog specimen that un-dims on accept, plus a snoozed Maybe-later state with undo.',
  ),
  entry(
    'referral-rewards-card',
    'Referral & Rewards Card',
    'block',
    'Startup Showcase',
    'Phone-width referral card: dashed copy-code pill with toast, tier progress bar, invited-friends list with nudge, share row, and a confetti reward-unlocked specimen with reconciling earnings.',
  ),
  entry(
    'live-activity-widget',
    'Live Activity Widgets',
    'block',
    'Startup Showcase',
    'Three lock-screen glance widgets on a blurred-gradient stage: delivery ETA with courier progress track, live basketball score, and an SVG-ring focus timer.',
  ),
  entry(
    'app-rating-prompt',
    'In-App Rating Flow',
    'block',
    'Startup Showcase',
    'Three live specimens of a rate-us card: star-hover initial ask, low-rating feedback branch with category chips, and high-rating store-review ask — each re-branches on tap.',
  ),
  entry(
    'password-signup-strength',
    'Signup with Password Strength',
    'block',
    'Startup Showcase',
    'Signup state sheet: good vs weak specimens with live strength meter, four-rule checklist, email typo-suggestion chip, match indicator, and a gated create-account CTA.',
  ),
  entry(
    'email-campaign-builder',
    'Email Campaign Builder',
    'page',
    'Startup Showcase',
    'Mailchimp-style campaign console: step rail, audience segment builder with live match count, styled newsletter mock, send-time optimizer histogram, A/B split slider, and a pre-send checklist strip.',
  ),
  entry(
    'team-password-vault',
    'Team Password Vault',
    'page',
    'Startup Showcase',
    '1Password-style credential manager: vault rail with security check, login item list, detail pane with concealed password and TOTP countdown ring, shared-with facepile, and a security-report strip.',
  ),
  entry(
    'inbox-zero-triage',
    'Inbox Zero Triage',
    'block',
    'Startup Showcase',
    'Phone-frame email triage pair: mid-swipe archive stamp with undo snackbar and peek cards, plus an inbox-zero celebration with reconciling session stats and a streak chip.',
  ),
  entry(
    'team-hub-home',
    'Team Hub Home',
    'page',
    'Team Workspace',
    "Program-team front door: presence facepile with launch countdown, today's meetings strip, pinned-docs rail, grouped activity feed, and a channel-digest plus OKR-snapshot panel.",
  ),
  entry(
    'project-workspace-overview',
    'Project Workspace Overview',
    'page',
    'Team Workspace',
    'Single-project home: at-risk health header, shared-scale milestone timeline with a slipped marker, linked-resource tiles with staleness chips, workstream cards, risks list, and a recent-decisions rail.',
  ),
  entry(
    'team-wiki-knowledge-base',
    'Team Wiki & Knowledge Base',
    'page',
    'Team Workspace',
    'Wiki surface: page-tree rail, verified runbook article with editing presence and freshness badges, stale-page review banner, backlinks section, and a scroll-spy mini-TOC.',
  ),
  entry(
    'sprint-retro-board',
    'Sprint Retrospective Board',
    'page',
    'Team Workspace',
    'Retro pinned on the vote phase: dot-vote budget strip, participation meter, three sentiment columns with anonymous cards and a bundled group, and an action-items panel.',
  ),
  entry(
    'brainstorm-whiteboard',
    'Brainstorm Whiteboard',
    'page',
    'Team Workspace',
    'Live pannable brainstorm canvas: theme-cluster frames with reconciling counts, working select/sticky/text/connector/frame tools, live cursors, a comment-pin thread, zoom controls, and a minimap.',
  ),
  entry(
    'decision-log-rfc',
    'Decision Log & RFC Review',
    'page',
    'Team Workspace',
    'Split-pane decision register: filterable RFC list, styled decision doc with an anchored comment thread and reviewer stances, metadata panel with decide-by countdown, and supersede cross-links.',
  ),
  entry(
    'async-standup-feed',
    'Async Standup Feed',
    'page',
    'Team Workspace',
    'Daily async check-ins: completion meter, blocker-rollup banner, a posting composer that re-derives counts, timezone-ordered Yesterday/Today/Blockers cards, streak chips, and a week-participation rail.',
  ),
  entry(
    'townhall-announcements',
    'Townhall & Announcements',
    'page',
    'Team Workspace',
    'Company comms hub: featured announcement hero with reactions and read progress, category-filtered post list, upvotable moderated Q&A panel, and a townhalls rail with recap-artifact chips.',
  ),
  entry(
    'team-directory-timezones',
    'Team Directory & Working Hours',
    'page',
    'Team Workspace',
    'Distributed-team directory: timezone-overlap strip with a golden window, out-today strip, filterable person cards with working-hour bars, and a compare tray computing the next mutual free slot.',
  ),
  entry(
    'comment-thread-popover',
    'Comment Thread Popover',
    'block',
    'Team Workspace',
    'Three frozen anchored comment-popover specimens — open thread with @mention autocomplete, resolved pill, and new-comment composer — beneath dimmed doc excerpts.',
  ),
  entry(
    'poll-composer-card',
    'Poll Composer & Results',
    'block',
    'Team Workspace',
    'Channel-poll card in three specimens: gated composer with option rows and settings, open poll with movable vote and live tallies, and a closed winner state.',
  ),
  entry(
    'meeting-notes-ai-card',
    'AI Meeting Notes Card',
    'block',
    'Team Workspace',
    'AI recap card in three specimens: ready summary with action items and share button, processing state with skeleton shimmer, and a low-confidence verify-this variant.',
  ),
  entry(
    'focus-status-sheet',
    'Focus & Status Sheet',
    'block',
    'Team Workspace',
    'Focus and status flow in three phone-width specimens: preset-grid bottom sheet with DND and duration chips, active-focus ring card with snooze/end, and a teammate-view badge row.',
  ),
  entry(
    'invite-teammates-modal',
    'Invite Teammates Modal',
    'block',
    'Team Workspace',
    'Workspace-invite modal in three specimens: email-chip composer with role selectors and an expiring join link, sent confirmation with pending badges, and a guest-warning variant.',
  ),
  entry(
    'legal-ai-assistant-workspace',
    'Legal AI Assistant Workspace',
    'page',
    'Legal AI',
    'Matter-scoped legal Q&A under a privilege strip: matter-context rail, cited answer with confidence bands and verification chips, sources panel, and an Ask/Draft/Summarize composer.',
  ),
  entry(
    'legal-doc-review-analysis',
    'Contract Review & Risk Analysis',
    'page',
    'Legal AI',
    'Single-contract AI review: serif paper with risk-tinted clause highlights cross-linked to an analysis rail of risk pills, market comparisons, and tracked-change redline suggestions.',
  ),
  entry(
    'legal-research-memo',
    'AI Research Memo',
    'page',
    'Legal AI',
    'Generated memo under verification: serif canvas with treatment-badged citation chips, an aligned margin verification rail, sources panel, and a citation meter gating export.',
  ),
  entry(
    'contract-diff-negotiation',
    'Negotiation Diff & Turn History',
    'page',
    'Legal AI',
    'Clause-aligned side-by-side contract redlines with per-side attribution, a turn-history band, changed-clause navigator, AI turn summary, and a negotiation position tracker.',
  ),
  entry(
    'due-diligence-data-room',
    'Due Diligence Data Room Review',
    'page',
    'Legal AI',
    'Data-room review: folder tree with progress rings, document status table, and a severity-grouped AI findings panel with citations, verification states, and report progress.',
  ),
  entry(
    'matter-workspace',
    'Matter Workspace',
    'page',
    'Legal AI',
    'Matter hub under a privilege strip: key-date countdown chips, workstream checklist, documents grid with expandable AI summaries, verified activity digest, and a team + billing rail.',
  ),
  entry(
    'clause-library-playbook',
    'Clause Library & Playbook',
    'page',
    'Legal AI',
    'Firm clause-standards base: clause-type rail, preferred-language paper block with fallback ladder and market-deviation bars, deviations table, and an AI deviation-analysis panel.',
  ),
  entry(
    'discovery-review-queue',
    'Discovery Review Queue',
    'page',
    'Legal AI',
    'Doc-by-doc discovery coding: Bates-stamped email paper with AI relevance/privilege washes, a coding rail with accept/override suggestions, working j/k/r/p keys, and a privilege-log drawer.',
  ),
  entry(
    'citations-authority-checker',
    'Citation & Authority Checker',
    'page',
    'Legal AI',
    'Cite-check audit table: treatment badges, depth-of-support pips, verification provenance, and an expanded negative-treatment row with a confirm-gated replace-suggestion workflow.',
  ),
  entry(
    'legal-request-intake',
    'Legal Request Intake & Triage',
    'page',
    'Legal AI',
    'Legal ops intake queue: SLA-countdown request list, deflection stats, and an AI triage panel with classification, route tiles, extracted key terms, and a pinned assignment footer.',
  ),
  entry(
    'source-citation-popover',
    'Source Citation Popover',
    'block',
    'Legal AI',
    'Three frozen citation-popover specimens — verified good-law, caution with distinguishing cases, and source-not-found — pinned over dimmed serif memo excerpts.',
  ),
  entry(
    'ai-drafting-sidebar',
    'AI Drafting Sidebar',
    'block',
    'Legal AI',
    'Drafting-assistant panel in three states — tracked-change suggestion, inserted-with-undo receipt, and redline-conflict hold — each beside a dimmed serif contract excerpt.',
  ),
  entry(
    'risk-flag-annotations',
    'Inline Risk Flag Annotations',
    'block',
    'Legal AI',
    'One clause-anchored risk flag in three lifecycle states — high-risk margin card, resolved redline chip, and dismissed-with-audit-trail — on the same serif contract paragraph.',
  ),
  entry(
    'conflict-check-card',
    'Conflicts Check Card',
    'block',
    'Legal AI',
    'New-matter conflicts run in three specimens — scanning databases, amber potential-conflict with a relationship mini-diagram, and cleared-to-engage — with escalate and log actions.',
  ),
  entry(
    'claims-adjudication-workbench',
    'Claims Adjudication Workbench',
    'page',
    'Vertical Ops',
    'Payer-side claims examiner cockpit: pended-claims rail, CPT lines with scrubable billed-to-paid EOB waterfalls, and a rule-trace ladder that re-fires on every what-if.',
  ),
  entry(
    'lims-plate-workbench',
    'LIMS Plate Workbench',
    'page',
    'Vertical Ops',
    'Bench-scientist LIMS console: inline-SVG 96-well plate beside the sample manifest, spatial selection filters the table, and a QC flag cascades holds through lineage to the release gate.',
  ),
  entry(
    'grid-feeder-console',
    'Grid Feeder Console',
    'page',
    'Vertical Ops',
    'Distribution-grid SCADA console: one-line diagram with toggleable breakers, feeder load-headroom rail, and an interlocked switching order — tripping BKR-4 backfeeds the tie and floods the alarm bar.',
  ),
  entry(
    'ham-contest-logger',
    'Ham Contest Logger',
    'page',
    'Vertical Ops',
    'Contest-weekend logging cockpit: type-to-resolve callsign entry with dupe/mult tinting, 32px QSO log, multiplier grid, beam-heading dial, and a live score derived from the same fold.',
  ),
];
